
(IN-PACKAGE :CVK)

(ADP:IN-FILE #P"docs/api/functions")

(DEFMACRO VULKAN-DEFCFUN ((FOREIGN-NAME NAME) RET-TYPE &BODY ARGS)
  (LET ((FUNCALL-NAME (INTERN (FORMAT NIL "FUNCALL-~a" (SYMBOL-NAME NAME))))
        (NAME-ARGS (MAPCAR #'CAR ARGS))
        (ORDERED-ARGS (MAPCAN (LAMBDA (ARG) (LIST (CADR ARG) (CAR ARG))) ARGS)))
    (WITH-GENSYMS (FUNC-PTR)
      `(PROGN
        (DEFUN ,NAME ,NAME-ARGS
          (CFFI:FOREIGN-FUNCALL ,FOREIGN-NAME ,@ORDERED-ARGS ,RET-TYPE))
        (DEFUN ,FUNCALL-NAME ,(CONS FUNC-PTR NAME-ARGS)
          (CFFI:FOREIGN-FUNCALL-POINTER ,FUNC-PTR NIL ,@ORDERED-ARGS
                                        ,RET-TYPE))))))

(VULKAN-DEFCFUN ("vkCreateInstance" VKCREATEINSTANCE) VKRESULT
 (PCREATEINFO :POINTER) (PALLOCATOR :POINTER) (PINSTANCE :POINTER))

(VULKAN-DEFCFUN ("vkDestroyInstance" VKDESTROYINSTANCE) :VOID
 (INSTANCE VKINSTANCE) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkEnumeratePhysicalDevices" VKENUMERATEPHYSICALDEVICES)
 VKRESULT (INSTANCE VKINSTANCE) (PPHYSICALDEVICECOUNT :POINTER)
 (PPHYSICALDEVICES :POINTER))

(VULKAN-DEFCFUN ("vkGetPhysicalDeviceFeatures" VKGETPHYSICALDEVICEFEATURES)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PFEATURES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceFormatProperties" VKGETPHYSICALDEVICEFORMATPROPERTIES)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (FORMAT VKFORMAT)
 (PFORMATPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceImageFormatProperties"
  VKGETPHYSICALDEVICEIMAGEFORMATPROPERTIES)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (FORMAT VKFORMAT)
 (TYPE VKIMAGETYPE) (TILING VKIMAGETILING) (USAGE VKIMAGEUSAGEFLAGS)
 (FLAGS VKIMAGECREATEFLAGS) (PIMAGEFORMATPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkGetPhysicalDeviceProperties" VKGETPHYSICALDEVICEPROPERTIES)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceQueueFamilyProperties"
  VKGETPHYSICALDEVICEQUEUEFAMILYPROPERTIES)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PQUEUEFAMILYPROPERTYCOUNT :POINTER)
 (PQUEUEFAMILYPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceMemoryProperties" VKGETPHYSICALDEVICEMEMORYPROPERTIES)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PMEMORYPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkGetInstanceProcAddr" VKGETINSTANCEPROCADDR)
 PFN_VKVOIDFUNCTION (INSTANCE VKINSTANCE) (PNAME :POINTER))

(VULKAN-DEFCFUN ("vkGetDeviceProcAddr" VKGETDEVICEPROCADDR) PFN_VKVOIDFUNCTION
 (DEVICE VKDEVICE) (PNAME :POINTER))

(VULKAN-DEFCFUN ("vkCreateDevice" VKCREATEDEVICE) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PDEVICE :POINTER))

(VULKAN-DEFCFUN ("vkDestroyDevice" VKDESTROYDEVICE) :VOID (DEVICE VKDEVICE)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN
 ("vkEnumerateInstanceExtensionProperties"
  VKENUMERATEINSTANCEEXTENSIONPROPERTIES)
 VKRESULT (PLAYERNAME :POINTER) (PPROPERTYCOUNT :POINTER)
 (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkEnumerateDeviceExtensionProperties" VKENUMERATEDEVICEEXTENSIONPROPERTIES)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PLAYERNAME :POINTER)
 (PPROPERTYCOUNT :POINTER) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkEnumerateInstanceLayerProperties" VKENUMERATEINSTANCELAYERPROPERTIES)
 VKRESULT (PPROPERTYCOUNT :POINTER) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkEnumerateDeviceLayerProperties" VKENUMERATEDEVICELAYERPROPERTIES) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (PPROPERTYCOUNT :POINTER)
 (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkGetDeviceQueue" VKGETDEVICEQUEUE) :VOID (DEVICE VKDEVICE)
 (QUEUEFAMILYINDEX :UINT32) (QUEUEINDEX :UINT32) (PQUEUE :POINTER))

(VULKAN-DEFCFUN ("vkQueueSubmit" VKQUEUESUBMIT) VKRESULT (QUEUE VKQUEUE)
 (SUBMITCOUNT :UINT32) (PSUBMITS :POINTER) (FENCE VKFENCE))

(VULKAN-DEFCFUN ("vkQueueWaitIdle" VKQUEUEWAITIDLE) VKRESULT (QUEUE VKQUEUE))

(VULKAN-DEFCFUN ("vkDeviceWaitIdle" VKDEVICEWAITIDLE) VKRESULT
 (DEVICE VKDEVICE))

(VULKAN-DEFCFUN ("vkAllocateMemory" VKALLOCATEMEMORY) VKRESULT
 (DEVICE VKDEVICE) (PALLOCATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PMEMORY :POINTER))

(VULKAN-DEFCFUN ("vkFreeMemory" VKFREEMEMORY) :VOID (DEVICE VKDEVICE)
 (MEMORY VKDEVICEMEMORY) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkMapMemory" VKMAPMEMORY) VKRESULT (DEVICE VKDEVICE)
 (MEMORY VKDEVICEMEMORY) (OFFSET VKDEVICESIZE) (SIZE VKDEVICESIZE)
 (FLAGS VKMEMORYMAPFLAGS) (PPDATA :POINTER))

(VULKAN-DEFCFUN ("vkUnmapMemory" VKUNMAPMEMORY) :VOID (DEVICE VKDEVICE)
 (MEMORY VKDEVICEMEMORY))

(VULKAN-DEFCFUN ("vkFlushMappedMemoryRanges" VKFLUSHMAPPEDMEMORYRANGES)
 VKRESULT (DEVICE VKDEVICE) (MEMORYRANGECOUNT :UINT32) (PMEMORYRANGES :POINTER))

(VULKAN-DEFCFUN
 ("vkInvalidateMappedMemoryRanges" VKINVALIDATEMAPPEDMEMORYRANGES) VKRESULT
 (DEVICE VKDEVICE) (MEMORYRANGECOUNT :UINT32) (PMEMORYRANGES :POINTER))

(VULKAN-DEFCFUN ("vkGetDeviceMemoryCommitment" VKGETDEVICEMEMORYCOMMITMENT)
 :VOID (DEVICE VKDEVICE) (MEMORY VKDEVICEMEMORY)
 (PCOMMITTEDMEMORYINBYTES :POINTER))

(VULKAN-DEFCFUN ("vkBindBufferMemory" VKBINDBUFFERMEMORY) VKRESULT
 (DEVICE VKDEVICE) (BUFFER VKBUFFER) (MEMORY VKDEVICEMEMORY)
 (MEMORYOFFSET VKDEVICESIZE))

(VULKAN-DEFCFUN ("vkBindImageMemory" VKBINDIMAGEMEMORY) VKRESULT
 (DEVICE VKDEVICE) (IMAGE VKIMAGE) (MEMORY VKDEVICEMEMORY)
 (MEMORYOFFSET VKDEVICESIZE))

(VULKAN-DEFCFUN ("vkGetBufferMemoryRequirements" VKGETBUFFERMEMORYREQUIREMENTS)
 :VOID (DEVICE VKDEVICE) (BUFFER VKBUFFER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN ("vkGetImageMemoryRequirements" VKGETIMAGEMEMORYREQUIREMENTS)
 :VOID (DEVICE VKDEVICE) (IMAGE VKIMAGE) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetImageSparseMemoryRequirements" VKGETIMAGESPARSEMEMORYREQUIREMENTS)
 :VOID (DEVICE VKDEVICE) (IMAGE VKIMAGE)
 (PSPARSEMEMORYREQUIREMENTCOUNT :POINTER) (PSPARSEMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSparseImageFormatProperties"
  VKGETPHYSICALDEVICESPARSEIMAGEFORMATPROPERTIES)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (FORMAT VKFORMAT) (TYPE VKIMAGETYPE)
 (SAMPLES VKSAMPLECOUNTFLAGBITS) (USAGE VKIMAGEUSAGEFLAGS)
 (TILING VKIMAGETILING) (PPROPERTYCOUNT :POINTER) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkQueueBindSparse" VKQUEUEBINDSPARSE) VKRESULT
 (QUEUE VKQUEUE) (BINDINFOCOUNT :UINT32) (PBINDINFO :POINTER) (FENCE VKFENCE))

(VULKAN-DEFCFUN ("vkCreateFence" VKCREATEFENCE) VKRESULT (DEVICE VKDEVICE)
 (PCREATEINFO :POINTER) (PALLOCATOR :POINTER) (PFENCE :POINTER))

(VULKAN-DEFCFUN ("vkDestroyFence" VKDESTROYFENCE) :VOID (DEVICE VKDEVICE)
 (FENCE VKFENCE) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkResetFences" VKRESETFENCES) VKRESULT (DEVICE VKDEVICE)
 (FENCECOUNT :UINT32) (PFENCES :POINTER))

(VULKAN-DEFCFUN ("vkGetFenceStatus" VKGETFENCESTATUS) VKRESULT
 (DEVICE VKDEVICE) (FENCE VKFENCE))

(VULKAN-DEFCFUN ("vkWaitForFences" VKWAITFORFENCES) VKRESULT (DEVICE VKDEVICE)
 (FENCECOUNT :UINT32) (PFENCES :POINTER) (WAITALL VKBOOL32) (TIMEOUT :UINT64))

(VULKAN-DEFCFUN ("vkCreateSemaphore" VKCREATESEMAPHORE) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PSEMAPHORE :POINTER))

(VULKAN-DEFCFUN ("vkDestroySemaphore" VKDESTROYSEMAPHORE) :VOID
 (DEVICE VKDEVICE) (SEMAPHORE VKSEMAPHORE) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreateEvent" VKCREATEEVENT) VKRESULT (DEVICE VKDEVICE)
 (PCREATEINFO :POINTER) (PALLOCATOR :POINTER) (PEVENT :POINTER))

(VULKAN-DEFCFUN ("vkDestroyEvent" VKDESTROYEVENT) :VOID (DEVICE VKDEVICE)
 (EVENT VKEVENT) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkGetEventStatus" VKGETEVENTSTATUS) VKRESULT
 (DEVICE VKDEVICE) (EVENT VKEVENT))

(VULKAN-DEFCFUN ("vkSetEvent" VKSETEVENT) VKRESULT (DEVICE VKDEVICE)
 (EVENT VKEVENT))

(VULKAN-DEFCFUN ("vkResetEvent" VKRESETEVENT) VKRESULT (DEVICE VKDEVICE)
 (EVENT VKEVENT))

(VULKAN-DEFCFUN ("vkCreateQueryPool" VKCREATEQUERYPOOL) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PQUERYPOOL :POINTER))

(VULKAN-DEFCFUN ("vkDestroyQueryPool" VKDESTROYQUERYPOOL) :VOID
 (DEVICE VKDEVICE) (QUERYPOOL VKQUERYPOOL) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkGetQueryPoolResults" VKGETQUERYPOOLRESULTS) VKRESULT
 (DEVICE VKDEVICE) (QUERYPOOL VKQUERYPOOL) (FIRSTQUERY :UINT32)
 (QUERYCOUNT :UINT32) (DATASIZE :SIZE) (PDATA :POINTER) (STRIDE VKDEVICESIZE)
 (FLAGS VKQUERYRESULTFLAGS))

(VULKAN-DEFCFUN ("vkCreateBuffer" VKCREATEBUFFER) VKRESULT (DEVICE VKDEVICE)
 (PCREATEINFO :POINTER) (PALLOCATOR :POINTER) (PBUFFER :POINTER))

(VULKAN-DEFCFUN ("vkDestroyBuffer" VKDESTROYBUFFER) :VOID (DEVICE VKDEVICE)
 (BUFFER VKBUFFER) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreateBufferView" VKCREATEBUFFERVIEW) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PVIEW :POINTER))

(VULKAN-DEFCFUN ("vkDestroyBufferView" VKDESTROYBUFFERVIEW) :VOID
 (DEVICE VKDEVICE) (BUFFERVIEW VKBUFFERVIEW) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreateImage" VKCREATEIMAGE) VKRESULT (DEVICE VKDEVICE)
 (PCREATEINFO :POINTER) (PALLOCATOR :POINTER) (PIMAGE :POINTER))

(VULKAN-DEFCFUN ("vkDestroyImage" VKDESTROYIMAGE) :VOID (DEVICE VKDEVICE)
 (IMAGE VKIMAGE) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkGetImageSubresourceLayout" VKGETIMAGESUBRESOURCELAYOUT)
 :VOID (DEVICE VKDEVICE) (IMAGE VKIMAGE) (PSUBRESOURCE :POINTER)
 (PLAYOUT :POINTER))

(VULKAN-DEFCFUN ("vkCreateImageView" VKCREATEIMAGEVIEW) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PVIEW :POINTER))

(VULKAN-DEFCFUN ("vkDestroyImageView" VKDESTROYIMAGEVIEW) :VOID
 (DEVICE VKDEVICE) (IMAGEVIEW VKIMAGEVIEW) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreateShaderModule" VKCREATESHADERMODULE) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PSHADERMODULE :POINTER))

(VULKAN-DEFCFUN ("vkDestroyShaderModule" VKDESTROYSHADERMODULE) :VOID
 (DEVICE VKDEVICE) (SHADERMODULE VKSHADERMODULE) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreatePipelineCache" VKCREATEPIPELINECACHE) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PPIPELINECACHE :POINTER))

(VULKAN-DEFCFUN ("vkDestroyPipelineCache" VKDESTROYPIPELINECACHE) :VOID
 (DEVICE VKDEVICE) (PIPELINECACHE VKPIPELINECACHE) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkGetPipelineCacheData" VKGETPIPELINECACHEDATA) VKRESULT
 (DEVICE VKDEVICE) (PIPELINECACHE VKPIPELINECACHE) (PDATASIZE :POINTER)
 (PDATA :POINTER))

(VULKAN-DEFCFUN ("vkMergePipelineCaches" VKMERGEPIPELINECACHES) VKRESULT
 (DEVICE VKDEVICE) (DSTCACHE VKPIPELINECACHE) (SRCCACHECOUNT :UINT32)
 (PSRCCACHES :POINTER))

(VULKAN-DEFCFUN ("vkCreateGraphicsPipelines" VKCREATEGRAPHICSPIPELINES)
 VKRESULT (DEVICE VKDEVICE) (PIPELINECACHE VKPIPELINECACHE)
 (CREATEINFOCOUNT :UINT32) (PCREATEINFOS :POINTER) (PALLOCATOR :POINTER)
 (PPIPELINES :POINTER))

(VULKAN-DEFCFUN ("vkCreateComputePipelines" VKCREATECOMPUTEPIPELINES) VKRESULT
 (DEVICE VKDEVICE) (PIPELINECACHE VKPIPELINECACHE) (CREATEINFOCOUNT :UINT32)
 (PCREATEINFOS :POINTER) (PALLOCATOR :POINTER) (PPIPELINES :POINTER))

(VULKAN-DEFCFUN ("vkDestroyPipeline" VKDESTROYPIPELINE) :VOID (DEVICE VKDEVICE)
 (PIPELINE VKPIPELINE) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreatePipelineLayout" VKCREATEPIPELINELAYOUT) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PPIPELINELAYOUT :POINTER))

(VULKAN-DEFCFUN ("vkDestroyPipelineLayout" VKDESTROYPIPELINELAYOUT) :VOID
 (DEVICE VKDEVICE) (PIPELINELAYOUT VKPIPELINELAYOUT) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreateSampler" VKCREATESAMPLER) VKRESULT (DEVICE VKDEVICE)
 (PCREATEINFO :POINTER) (PALLOCATOR :POINTER) (PSAMPLER :POINTER))

(VULKAN-DEFCFUN ("vkDestroySampler" VKDESTROYSAMPLER) :VOID (DEVICE VKDEVICE)
 (SAMPLER VKSAMPLER) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreateDescriptorSetLayout" VKCREATEDESCRIPTORSETLAYOUT)
 VKRESULT (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PSETLAYOUT :POINTER))

(VULKAN-DEFCFUN ("vkDestroyDescriptorSetLayout" VKDESTROYDESCRIPTORSETLAYOUT)
 :VOID (DEVICE VKDEVICE) (DESCRIPTORSETLAYOUT VKDESCRIPTORSETLAYOUT)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreateDescriptorPool" VKCREATEDESCRIPTORPOOL) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PDESCRIPTORPOOL :POINTER))

(VULKAN-DEFCFUN ("vkDestroyDescriptorPool" VKDESTROYDESCRIPTORPOOL) :VOID
 (DEVICE VKDEVICE) (DESCRIPTORPOOL VKDESCRIPTORPOOL) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkResetDescriptorPool" VKRESETDESCRIPTORPOOL) VKRESULT
 (DEVICE VKDEVICE) (DESCRIPTORPOOL VKDESCRIPTORPOOL)
 (FLAGS VKDESCRIPTORPOOLRESETFLAGS))

(VULKAN-DEFCFUN ("vkAllocateDescriptorSets" VKALLOCATEDESCRIPTORSETS) VKRESULT
 (DEVICE VKDEVICE) (PALLOCATEINFO :POINTER) (PDESCRIPTORSETS :POINTER))

(VULKAN-DEFCFUN ("vkFreeDescriptorSets" VKFREEDESCRIPTORSETS) VKRESULT
 (DEVICE VKDEVICE) (DESCRIPTORPOOL VKDESCRIPTORPOOL)
 (DESCRIPTORSETCOUNT :UINT32) (PDESCRIPTORSETS :POINTER))

(VULKAN-DEFCFUN ("vkUpdateDescriptorSets" VKUPDATEDESCRIPTORSETS) :VOID
 (DEVICE VKDEVICE) (DESCRIPTORWRITECOUNT :UINT32) (PDESCRIPTORWRITES :POINTER)
 (DESCRIPTORCOPYCOUNT :UINT32) (PDESCRIPTORCOPIES :POINTER))

(VULKAN-DEFCFUN ("vkCreateFramebuffer" VKCREATEFRAMEBUFFER) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PFRAMEBUFFER :POINTER))

(VULKAN-DEFCFUN ("vkDestroyFramebuffer" VKDESTROYFRAMEBUFFER) :VOID
 (DEVICE VKDEVICE) (FRAMEBUFFER VKFRAMEBUFFER) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCreateRenderPass" VKCREATERENDERPASS) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PRENDERPASS :POINTER))

(VULKAN-DEFCFUN ("vkDestroyRenderPass" VKDESTROYRENDERPASS) :VOID
 (DEVICE VKDEVICE) (RENDERPASS VKRENDERPASS) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkGetRenderAreaGranularity" VKGETRENDERAREAGRANULARITY) :VOID
 (DEVICE VKDEVICE) (RENDERPASS VKRENDERPASS) (PGRANULARITY :POINTER))

(VULKAN-DEFCFUN ("vkCreateCommandPool" VKCREATECOMMANDPOOL) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PCOMMANDPOOL :POINTER))

(VULKAN-DEFCFUN ("vkDestroyCommandPool" VKDESTROYCOMMANDPOOL) :VOID
 (DEVICE VKDEVICE) (COMMANDPOOL VKCOMMANDPOOL) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkResetCommandPool" VKRESETCOMMANDPOOL) VKRESULT
 (DEVICE VKDEVICE) (COMMANDPOOL VKCOMMANDPOOL) (FLAGS VKCOMMANDPOOLRESETFLAGS))

(VULKAN-DEFCFUN ("vkAllocateCommandBuffers" VKALLOCATECOMMANDBUFFERS) VKRESULT
 (DEVICE VKDEVICE) (PALLOCATEINFO :POINTER) (PCOMMANDBUFFERS :POINTER))

(VULKAN-DEFCFUN ("vkFreeCommandBuffers" VKFREECOMMANDBUFFERS) :VOID
 (DEVICE VKDEVICE) (COMMANDPOOL VKCOMMANDPOOL) (COMMANDBUFFERCOUNT :UINT32)
 (PCOMMANDBUFFERS :POINTER))

(VULKAN-DEFCFUN ("vkBeginCommandBuffer" VKBEGINCOMMANDBUFFER) VKRESULT
 (COMMANDBUFFER VKCOMMANDBUFFER) (PBEGININFO :POINTER))

(VULKAN-DEFCFUN ("vkEndCommandBuffer" VKENDCOMMANDBUFFER) VKRESULT
 (COMMANDBUFFER VKCOMMANDBUFFER))

(VULKAN-DEFCFUN ("vkResetCommandBuffer" VKRESETCOMMANDBUFFER) VKRESULT
 (COMMANDBUFFER VKCOMMANDBUFFER) (FLAGS VKCOMMANDBUFFERRESETFLAGS))

(VULKAN-DEFCFUN ("vkCmdBindPipeline" VKCMDBINDPIPELINE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PIPELINEBINDPOINT VKPIPELINEBINDPOINT)
 (PIPELINE VKPIPELINE))

(VULKAN-DEFCFUN ("vkCmdSetViewport" VKCMDSETVIEWPORT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTVIEWPORT :UINT32)
 (VIEWPORTCOUNT :UINT32) (PVIEWPORTS :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetScissor" VKCMDSETSCISSOR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTSCISSOR :UINT32) (SCISSORCOUNT :UINT32)
 (PSCISSORS :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetLineWidth" VKCMDSETLINEWIDTH) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (LINEWIDTH :FLOAT))

(VULKAN-DEFCFUN ("vkCmdSetDepthBias" VKCMDSETDEPTHBIAS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHBIASCONSTANTFACTOR :FLOAT)
 (DEPTHBIASCLAMP :FLOAT) (DEPTHBIASSLOPEFACTOR :FLOAT))

(VULKAN-DEFCFUN ("vkCmdSetBlendConstants" VKCMDSETBLENDCONSTANTS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BLENDCONSTANTS :FLOAT))

(VULKAN-DEFCFUN ("vkCmdSetDepthBounds" VKCMDSETDEPTHBOUNDS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (MINDEPTHBOUNDS :FLOAT)
 (MAXDEPTHBOUNDS :FLOAT))

(VULKAN-DEFCFUN ("vkCmdSetStencilCompareMask" VKCMDSETSTENCILCOMPAREMASK) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FACEMASK VKSTENCILFACEFLAGS)
 (COMPAREMASK :UINT32))

(VULKAN-DEFCFUN ("vkCmdSetStencilWriteMask" VKCMDSETSTENCILWRITEMASK) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FACEMASK VKSTENCILFACEFLAGS)
 (WRITEMASK :UINT32))

(VULKAN-DEFCFUN ("vkCmdSetStencilReference" VKCMDSETSTENCILREFERENCE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FACEMASK VKSTENCILFACEFLAGS)
 (REFERENCE :UINT32))

(VULKAN-DEFCFUN ("vkCmdBindDescriptorSets" VKCMDBINDDESCRIPTORSETS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PIPELINEBINDPOINT VKPIPELINEBINDPOINT)
 (LAYOUT VKPIPELINELAYOUT) (FIRSTSET :UINT32) (DESCRIPTORSETCOUNT :UINT32)
 (PDESCRIPTORSETS :POINTER) (DYNAMICOFFSETCOUNT :UINT32)
 (PDYNAMICOFFSETS :POINTER))

(VULKAN-DEFCFUN ("vkCmdBindIndexBuffer" VKCMDBINDINDEXBUFFER) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (INDEXTYPE VKINDEXTYPE))

(VULKAN-DEFCFUN ("vkCmdBindVertexBuffers" VKCMDBINDVERTEXBUFFERS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTBINDING :UINT32) (BINDINGCOUNT :UINT32)
 (PBUFFERS :POINTER) (POFFSETS :POINTER))

(VULKAN-DEFCFUN ("vkCmdDraw" VKCMDDRAW) :VOID (COMMANDBUFFER VKCOMMANDBUFFER)
 (VERTEXCOUNT :UINT32) (INSTANCECOUNT :UINT32) (FIRSTVERTEX :UINT32)
 (FIRSTINSTANCE :UINT32))

(VULKAN-DEFCFUN ("vkCmdDrawIndexed" VKCMDDRAWINDEXED) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (INDEXCOUNT :UINT32) (INSTANCECOUNT :UINT32)
 (FIRSTINDEX :UINT32) (VERTEXOFFSET :INT32) (FIRSTINSTANCE :UINT32))

(VULKAN-DEFCFUN ("vkCmdDrawIndirect" VKCMDDRAWINDIRECT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (DRAWCOUNT :UINT32) (STRIDE :UINT32))

(VULKAN-DEFCFUN ("vkCmdDrawIndexedIndirect" VKCMDDRAWINDEXEDINDIRECT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (DRAWCOUNT :UINT32) (STRIDE :UINT32))

(VULKAN-DEFCFUN ("vkCmdDispatch" VKCMDDISPATCH) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (GROUPCOUNTX :UINT32) (GROUPCOUNTY :UINT32)
 (GROUPCOUNTZ :UINT32))

(VULKAN-DEFCFUN ("vkCmdDispatchIndirect" VKCMDDISPATCHINDIRECT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE))

(VULKAN-DEFCFUN ("vkCmdCopyBuffer" VKCMDCOPYBUFFER) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (SRCBUFFER VKBUFFER) (DSTBUFFER VKBUFFER)
 (REGIONCOUNT :UINT32) (PREGIONS :POINTER))

(VULKAN-DEFCFUN ("vkCmdCopyImage" VKCMDCOPYIMAGE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (SRCIMAGE VKIMAGE)
 (SRCIMAGELAYOUT VKIMAGELAYOUT) (DSTIMAGE VKIMAGE)
 (DSTIMAGELAYOUT VKIMAGELAYOUT) (REGIONCOUNT :UINT32) (PREGIONS :POINTER))

(VULKAN-DEFCFUN ("vkCmdBlitImage" VKCMDBLITIMAGE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (SRCIMAGE VKIMAGE)
 (SRCIMAGELAYOUT VKIMAGELAYOUT) (DSTIMAGE VKIMAGE)
 (DSTIMAGELAYOUT VKIMAGELAYOUT) (REGIONCOUNT :UINT32) (PREGIONS :POINTER)
 (FILTER VKFILTER))

(VULKAN-DEFCFUN ("vkCmdCopyBufferToImage" VKCMDCOPYBUFFERTOIMAGE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (SRCBUFFER VKBUFFER) (DSTIMAGE VKIMAGE)
 (DSTIMAGELAYOUT VKIMAGELAYOUT) (REGIONCOUNT :UINT32) (PREGIONS :POINTER))

(VULKAN-DEFCFUN ("vkCmdCopyImageToBuffer" VKCMDCOPYIMAGETOBUFFER) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (SRCIMAGE VKIMAGE)
 (SRCIMAGELAYOUT VKIMAGELAYOUT) (DSTBUFFER VKBUFFER) (REGIONCOUNT :UINT32)
 (PREGIONS :POINTER))

(VULKAN-DEFCFUN ("vkCmdUpdateBuffer" VKCMDUPDATEBUFFER) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DSTBUFFER VKBUFFER) (DSTOFFSET VKDEVICESIZE)
 (DATASIZE VKDEVICESIZE) (PDATA :POINTER))

(VULKAN-DEFCFUN ("vkCmdFillBuffer" VKCMDFILLBUFFER) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DSTBUFFER VKBUFFER) (DSTOFFSET VKDEVICESIZE)
 (SIZE VKDEVICESIZE) (DATA :UINT32))

(VULKAN-DEFCFUN ("vkCmdClearColorImage" VKCMDCLEARCOLORIMAGE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (IMAGE VKIMAGE) (IMAGELAYOUT VKIMAGELAYOUT)
 (PCOLOR :POINTER) (RANGECOUNT :UINT32) (PRANGES :POINTER))

(VULKAN-DEFCFUN ("vkCmdClearDepthStencilImage" VKCMDCLEARDEPTHSTENCILIMAGE)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (IMAGE VKIMAGE)
 (IMAGELAYOUT VKIMAGELAYOUT) (PDEPTHSTENCIL :POINTER) (RANGECOUNT :UINT32)
 (PRANGES :POINTER))

(VULKAN-DEFCFUN ("vkCmdClearAttachments" VKCMDCLEARATTACHMENTS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (ATTACHMENTCOUNT :UINT32)
 (PATTACHMENTS :POINTER) (RECTCOUNT :UINT32) (PRECTS :POINTER))

(VULKAN-DEFCFUN ("vkCmdResolveImage" VKCMDRESOLVEIMAGE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (SRCIMAGE VKIMAGE)
 (SRCIMAGELAYOUT VKIMAGELAYOUT) (DSTIMAGE VKIMAGE)
 (DSTIMAGELAYOUT VKIMAGELAYOUT) (REGIONCOUNT :UINT32) (PREGIONS :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetEvent" VKCMDSETEVENT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (EVENT VKEVENT)
 (STAGEMASK VKPIPELINESTAGEFLAGS))

(VULKAN-DEFCFUN ("vkCmdResetEvent" VKCMDRESETEVENT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (EVENT VKEVENT)
 (STAGEMASK VKPIPELINESTAGEFLAGS))

(VULKAN-DEFCFUN ("vkCmdWaitEvents" VKCMDWAITEVENTS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (EVENTCOUNT :UINT32) (PEVENTS :POINTER)
 (SRCSTAGEMASK VKPIPELINESTAGEFLAGS) (DSTSTAGEMASK VKPIPELINESTAGEFLAGS)
 (MEMORYBARRIERCOUNT :UINT32) (PMEMORYBARRIERS :POINTER)
 (BUFFERMEMORYBARRIERCOUNT :UINT32) (PBUFFERMEMORYBARRIERS :POINTER)
 (IMAGEMEMORYBARRIERCOUNT :UINT32) (PIMAGEMEMORYBARRIERS :POINTER))

(VULKAN-DEFCFUN ("vkCmdPipelineBarrier" VKCMDPIPELINEBARRIER) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (SRCSTAGEMASK VKPIPELINESTAGEFLAGS)
 (DSTSTAGEMASK VKPIPELINESTAGEFLAGS) (DEPENDENCYFLAGS VKDEPENDENCYFLAGS)
 (MEMORYBARRIERCOUNT :UINT32) (PMEMORYBARRIERS :POINTER)
 (BUFFERMEMORYBARRIERCOUNT :UINT32) (PBUFFERMEMORYBARRIERS :POINTER)
 (IMAGEMEMORYBARRIERCOUNT :UINT32) (PIMAGEMEMORYBARRIERS :POINTER))

(VULKAN-DEFCFUN ("vkCmdBeginQuery" VKCMDBEGINQUERY) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (QUERYPOOL VKQUERYPOOL) (QUERY :UINT32)
 (FLAGS VKQUERYCONTROLFLAGS))

(VULKAN-DEFCFUN ("vkCmdEndQuery" VKCMDENDQUERY) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (QUERYPOOL VKQUERYPOOL) (QUERY :UINT32))

(VULKAN-DEFCFUN ("vkCmdResetQueryPool" VKCMDRESETQUERYPOOL) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (QUERYPOOL VKQUERYPOOL) (FIRSTQUERY :UINT32)
 (QUERYCOUNT :UINT32))

(VULKAN-DEFCFUN ("vkCmdWriteTimestamp" VKCMDWRITETIMESTAMP) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PIPELINESTAGE VKPIPELINESTAGEFLAGBITS)
 (QUERYPOOL VKQUERYPOOL) (QUERY :UINT32))

(VULKAN-DEFCFUN ("vkCmdCopyQueryPoolResults" VKCMDCOPYQUERYPOOLRESULTS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (QUERYPOOL VKQUERYPOOL) (FIRSTQUERY :UINT32)
 (QUERYCOUNT :UINT32) (DSTBUFFER VKBUFFER) (DSTOFFSET VKDEVICESIZE)
 (STRIDE VKDEVICESIZE) (FLAGS VKQUERYRESULTFLAGS))

(VULKAN-DEFCFUN ("vkCmdPushConstants" VKCMDPUSHCONSTANTS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (LAYOUT VKPIPELINELAYOUT)
 (STAGEFLAGS VKSHADERSTAGEFLAGS) (OFFSET :UINT32) (SIZE :UINT32)
 (PVALUES :POINTER))

(VULKAN-DEFCFUN ("vkCmdBeginRenderPass" VKCMDBEGINRENDERPASS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRENDERPASSBEGIN :POINTER)
 (CONTENTS VKSUBPASSCONTENTS))

(VULKAN-DEFCFUN ("vkCmdNextSubpass" VKCMDNEXTSUBPASS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (CONTENTS VKSUBPASSCONTENTS))

(VULKAN-DEFCFUN ("vkCmdEndRenderPass" VKCMDENDRENDERPASS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER))

(VULKAN-DEFCFUN ("vkCmdExecuteCommands" VKCMDEXECUTECOMMANDS) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (COMMANDBUFFERCOUNT :UINT32)
 (PCOMMANDBUFFERS :POINTER))

(VULKAN-DEFCFUN ("vkEnumerateInstanceVersion" VKENUMERATEINSTANCEVERSION)
 VKRESULT (PAPIVERSION :POINTER))

(VULKAN-DEFCFUN ("vkBindBufferMemory2" VKBINDBUFFERMEMORY2) VKRESULT
 (DEVICE VKDEVICE) (BINDINFOCOUNT :UINT32) (PBINDINFOS :POINTER))

(VULKAN-DEFCFUN ("vkBindImageMemory2" VKBINDIMAGEMEMORY2) VKRESULT
 (DEVICE VKDEVICE) (BINDINFOCOUNT :UINT32) (PBINDINFOS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceGroupPeerMemoryFeatures" VKGETDEVICEGROUPPEERMEMORYFEATURES)
 :VOID (DEVICE VKDEVICE) (HEAPINDEX :UINT32) (LOCALDEVICEINDEX :UINT32)
 (REMOTEDEVICEINDEX :UINT32) (PPEERMEMORYFEATURES :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetDeviceMask" VKCMDSETDEVICEMASK) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEVICEMASK :UINT32))

(VULKAN-DEFCFUN ("vkCmdDispatchBase" VKCMDDISPATCHBASE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BASEGROUPX :UINT32) (BASEGROUPY :UINT32)
 (BASEGROUPZ :UINT32) (GROUPCOUNTX :UINT32) (GROUPCOUNTY :UINT32)
 (GROUPCOUNTZ :UINT32))

(VULKAN-DEFCFUN
 ("vkEnumeratePhysicalDeviceGroups" VKENUMERATEPHYSICALDEVICEGROUPS) VKRESULT
 (INSTANCE VKINSTANCE) (PPHYSICALDEVICEGROUPCOUNT :POINTER)
 (PPHYSICALDEVICEGROUPPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkGetImageMemoryRequirements2" VKGETIMAGEMEMORYREQUIREMENTS2)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetBufferMemoryRequirements2" VKGETBUFFERMEMORYREQUIREMENTS2) :VOID
 (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetImageSparseMemoryRequirements2" VKGETIMAGESPARSEMEMORYREQUIREMENTS2)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER)
 (PSPARSEMEMORYREQUIREMENTCOUNT :POINTER) (PSPARSEMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN ("vkGetPhysicalDeviceFeatures2" VKGETPHYSICALDEVICEFEATURES2)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PFEATURES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceProperties2" VKGETPHYSICALDEVICEPROPERTIES2) :VOID
 (PHYSICALDEVICE VKPHYSICALDEVICE) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceFormatProperties2" VKGETPHYSICALDEVICEFORMATPROPERTIES2)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (FORMAT VKFORMAT)
 (PFORMATPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceImageFormatProperties2"
  VKGETPHYSICALDEVICEIMAGEFORMATPROPERTIES2)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PIMAGEFORMATINFO :POINTER)
 (PIMAGEFORMATPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceQueueFamilyProperties2"
  VKGETPHYSICALDEVICEQUEUEFAMILYPROPERTIES2)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PQUEUEFAMILYPROPERTYCOUNT :POINTER)
 (PQUEUEFAMILYPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceMemoryProperties2" VKGETPHYSICALDEVICEMEMORYPROPERTIES2)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PMEMORYPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSparseImageFormatProperties2"
  VKGETPHYSICALDEVICESPARSEIMAGEFORMATPROPERTIES2)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PFORMATINFO :POINTER)
 (PPROPERTYCOUNT :POINTER) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkTrimCommandPool" VKTRIMCOMMANDPOOL) :VOID (DEVICE VKDEVICE)
 (COMMANDPOOL VKCOMMANDPOOL) (FLAGS VKCOMMANDPOOLTRIMFLAGS))

(VULKAN-DEFCFUN ("vkGetDeviceQueue2" VKGETDEVICEQUEUE2) :VOID (DEVICE VKDEVICE)
 (PQUEUEINFO :POINTER) (PQUEUE :POINTER))

(VULKAN-DEFCFUN
 ("vkCreateSamplerYcbcrConversion" VKCREATESAMPLERYCBCRCONVERSION) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PYCBCRCONVERSION :POINTER))

(VULKAN-DEFCFUN
 ("vkDestroySamplerYcbcrConversion" VKDESTROYSAMPLERYCBCRCONVERSION) :VOID
 (DEVICE VKDEVICE) (YCBCRCONVERSION VKSAMPLERYCBCRCONVERSION)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN
 ("vkCreateDescriptorUpdateTemplate" VKCREATEDESCRIPTORUPDATETEMPLATE) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PDESCRIPTORUPDATETEMPLATE :POINTER))

(VULKAN-DEFCFUN
 ("vkDestroyDescriptorUpdateTemplate" VKDESTROYDESCRIPTORUPDATETEMPLATE) :VOID
 (DEVICE VKDEVICE) (DESCRIPTORUPDATETEMPLATE VKDESCRIPTORUPDATETEMPLATE)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN
 ("vkUpdateDescriptorSetWithTemplate" VKUPDATEDESCRIPTORSETWITHTEMPLATE) :VOID
 (DEVICE VKDEVICE) (DESCRIPTORSET VKDESCRIPTORSET)
 (DESCRIPTORUPDATETEMPLATE VKDESCRIPTORUPDATETEMPLATE) (PDATA :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceExternalBufferProperties"
  VKGETPHYSICALDEVICEEXTERNALBUFFERPROPERTIES)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PEXTERNALBUFFERINFO :POINTER)
 (PEXTERNALBUFFERPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceExternalFenceProperties"
  VKGETPHYSICALDEVICEEXTERNALFENCEPROPERTIES)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PEXTERNALFENCEINFO :POINTER)
 (PEXTERNALFENCEPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceExternalSemaphoreProperties"
  VKGETPHYSICALDEVICEEXTERNALSEMAPHOREPROPERTIES)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PEXTERNALSEMAPHOREINFO :POINTER)
 (PEXTERNALSEMAPHOREPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDescriptorSetLayoutSupport" VKGETDESCRIPTORSETLAYOUTSUPPORT) :VOID
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PSUPPORT :POINTER))

(VULKAN-DEFCFUN ("vkCmdDrawIndirectCount" VKCMDDRAWINDIRECTCOUNT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (COUNTBUFFER VKBUFFER) (COUNTBUFFEROFFSET VKDEVICESIZE) (MAXDRAWCOUNT :UINT32)
 (STRIDE :UINT32))

(VULKAN-DEFCFUN ("vkCmdDrawIndexedIndirectCount" VKCMDDRAWINDEXEDINDIRECTCOUNT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (COUNTBUFFER VKBUFFER) (COUNTBUFFEROFFSET VKDEVICESIZE) (MAXDRAWCOUNT :UINT32)
 (STRIDE :UINT32))

(VULKAN-DEFCFUN ("vkCreateRenderPass2" VKCREATERENDERPASS2) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PRENDERPASS :POINTER))

(VULKAN-DEFCFUN ("vkCmdBeginRenderPass2" VKCMDBEGINRENDERPASS2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRENDERPASSBEGIN :POINTER)
 (PSUBPASSBEGININFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdNextSubpass2" VKCMDNEXTSUBPASS2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PSUBPASSBEGININFO :POINTER)
 (PSUBPASSENDINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdEndRenderPass2" VKCMDENDRENDERPASS2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PSUBPASSENDINFO :POINTER))

(VULKAN-DEFCFUN ("vkResetQueryPool" VKRESETQUERYPOOL) :VOID (DEVICE VKDEVICE)
 (QUERYPOOL VKQUERYPOOL) (FIRSTQUERY :UINT32) (QUERYCOUNT :UINT32))

(VULKAN-DEFCFUN ("vkGetSemaphoreCounterValue" VKGETSEMAPHORECOUNTERVALUE)
 VKRESULT (DEVICE VKDEVICE) (SEMAPHORE VKSEMAPHORE) (PVALUE :POINTER))

(VULKAN-DEFCFUN ("vkWaitSemaphores" VKWAITSEMAPHORES) VKRESULT
 (DEVICE VKDEVICE) (PWAITINFO :POINTER) (TIMEOUT :UINT64))

(VULKAN-DEFCFUN ("vkSignalSemaphore" VKSIGNALSEMAPHORE) VKRESULT
 (DEVICE VKDEVICE) (PSIGNALINFO :POINTER))

(VULKAN-DEFCFUN ("vkGetBufferDeviceAddress" VKGETBUFFERDEVICEADDRESS)
 VKDEVICEADDRESS (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetBufferOpaqueCaptureAddress" VKGETBUFFEROPAQUECAPTUREADDRESS) :UINT64
 (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceMemoryOpaqueCaptureAddress"
  VKGETDEVICEMEMORYOPAQUECAPTUREADDRESS)
 :UINT64 (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceToolProperties" VKGETPHYSICALDEVICETOOLPROPERTIES)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PTOOLCOUNT :POINTER)
 (PTOOLPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkCreatePrivateDataSlot" VKCREATEPRIVATEDATASLOT) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PPRIVATEDATASLOT :POINTER))

(VULKAN-DEFCFUN ("vkDestroyPrivateDataSlot" VKDESTROYPRIVATEDATASLOT) :VOID
 (DEVICE VKDEVICE) (PRIVATEDATASLOT VKPRIVATEDATASLOT) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkSetPrivateData" VKSETPRIVATEDATA) VKRESULT
 (DEVICE VKDEVICE) (OBJECTTYPE VKOBJECTTYPE) (OBJECTHANDLE :UINT64)
 (PRIVATEDATASLOT VKPRIVATEDATASLOT) (DATA :UINT64))

(VULKAN-DEFCFUN ("vkGetPrivateData" VKGETPRIVATEDATA) :VOID (DEVICE VKDEVICE)
 (OBJECTTYPE VKOBJECTTYPE) (OBJECTHANDLE :UINT64)
 (PRIVATEDATASLOT VKPRIVATEDATASLOT) (PDATA :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetEvent2" VKCMDSETEVENT2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (EVENT VKEVENT) (PDEPENDENCYINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdResetEvent2" VKCMDRESETEVENT2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (EVENT VKEVENT)
 (STAGEMASK VKPIPELINESTAGEFLAGS2))

(VULKAN-DEFCFUN ("vkCmdWaitEvents2" VKCMDWAITEVENTS2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (EVENTCOUNT :UINT32) (PEVENTS :POINTER)
 (PDEPENDENCYINFOS :POINTER))

(VULKAN-DEFCFUN ("vkCmdPipelineBarrier2" VKCMDPIPELINEBARRIER2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PDEPENDENCYINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdWriteTimestamp2" VKCMDWRITETIMESTAMP2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (STAGE VKPIPELINESTAGEFLAGS2)
 (QUERYPOOL VKQUERYPOOL) (QUERY :UINT32))

(VULKAN-DEFCFUN ("vkQueueSubmit2" VKQUEUESUBMIT2) VKRESULT (QUEUE VKQUEUE)
 (SUBMITCOUNT :UINT32) (PSUBMITS :POINTER) (FENCE VKFENCE))

(VULKAN-DEFCFUN ("vkCmdCopyBuffer2" VKCMDCOPYBUFFER2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCOPYBUFFERINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdCopyImage2" VKCMDCOPYIMAGE2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCOPYIMAGEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdCopyBufferToImage2" VKCMDCOPYBUFFERTOIMAGE2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCOPYBUFFERTOIMAGEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdCopyImageToBuffer2" VKCMDCOPYIMAGETOBUFFER2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCOPYIMAGETOBUFFERINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdBlitImage2" VKCMDBLITIMAGE2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PBLITIMAGEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdResolveImage2" VKCMDRESOLVEIMAGE2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRESOLVEIMAGEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdBeginRendering" VKCMDBEGINRENDERING) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRENDERINGINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdEndRendering" VKCMDENDRENDERING) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER))

(VULKAN-DEFCFUN ("vkCmdSetCullMode" VKCMDSETCULLMODE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (CULLMODE VKCULLMODEFLAGS))

(VULKAN-DEFCFUN ("vkCmdSetFrontFace" VKCMDSETFRONTFACE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FRONTFACE VKFRONTFACE))

(VULKAN-DEFCFUN ("vkCmdSetPrimitiveTopology" VKCMDSETPRIMITIVETOPOLOGY) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRIMITIVETOPOLOGY VKPRIMITIVETOPOLOGY))

(VULKAN-DEFCFUN ("vkCmdSetViewportWithCount" VKCMDSETVIEWPORTWITHCOUNT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (VIEWPORTCOUNT :UINT32) (PVIEWPORTS :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetScissorWithCount" VKCMDSETSCISSORWITHCOUNT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (SCISSORCOUNT :UINT32) (PSCISSORS :POINTER))

(VULKAN-DEFCFUN ("vkCmdBindVertexBuffers2" VKCMDBINDVERTEXBUFFERS2) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTBINDING :UINT32) (BINDINGCOUNT :UINT32)
 (PBUFFERS :POINTER) (POFFSETS :POINTER) (PSIZES :POINTER) (PSTRIDES :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetDepthTestEnable" VKCMDSETDEPTHTESTENABLE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHTESTENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetDepthWriteEnable" VKCMDSETDEPTHWRITEENABLE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHWRITEENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetDepthCompareOp" VKCMDSETDEPTHCOMPAREOP) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHCOMPAREOP VKCOMPAREOP))

(VULKAN-DEFCFUN ("vkCmdSetDepthBoundsTestEnable" VKCMDSETDEPTHBOUNDSTESTENABLE)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHBOUNDSTESTENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetStencilTestEnable" VKCMDSETSTENCILTESTENABLE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (STENCILTESTENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetStencilOp" VKCMDSETSTENCILOP) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FACEMASK VKSTENCILFACEFLAGS)
 (FAILOP VKSTENCILOP) (PASSOP VKSTENCILOP) (DEPTHFAILOP VKSTENCILOP)
 (COMPAREOP VKCOMPAREOP))

(VULKAN-DEFCFUN
 ("vkCmdSetRasterizerDiscardEnable" VKCMDSETRASTERIZERDISCARDENABLE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (RASTERIZERDISCARDENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetDepthBiasEnable" VKCMDSETDEPTHBIASENABLE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHBIASENABLE VKBOOL32))

(VULKAN-DEFCFUN
 ("vkCmdSetPrimitiveRestartEnable" VKCMDSETPRIMITIVERESTARTENABLE) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRIMITIVERESTARTENABLE VKBOOL32))

(VULKAN-DEFCFUN
 ("vkGetDeviceBufferMemoryRequirements" VKGETDEVICEBUFFERMEMORYREQUIREMENTS)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceImageMemoryRequirements" VKGETDEVICEIMAGEMEMORYREQUIREMENTS)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceImageSparseMemoryRequirements"
  VKGETDEVICEIMAGESPARSEMEMORYREQUIREMENTS)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER)
 (PSPARSEMEMORYREQUIREMENTCOUNT :POINTER) (PSPARSEMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN ("vkDestroySurfaceKHR" VKDESTROYSURFACEKHR) :VOID
 (INSTANCE VKINSTANCE) (SURFACE VKSURFACEKHR) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSurfaceSupportKHR" VKGETPHYSICALDEVICESURFACESUPPORTKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (QUEUEFAMILYINDEX :UINT32)
 (SURFACE VKSURFACEKHR) (PSUPPORTED :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSurfaceCapabilitiesKHR"
  VKGETPHYSICALDEVICESURFACECAPABILITIESKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (SURFACE VKSURFACEKHR)
 (PSURFACECAPABILITIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSurfaceFormatsKHR" VKGETPHYSICALDEVICESURFACEFORMATSKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (SURFACE VKSURFACEKHR)
 (PSURFACEFORMATCOUNT :POINTER) (PSURFACEFORMATS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSurfacePresentModesKHR"
  VKGETPHYSICALDEVICESURFACEPRESENTMODESKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (SURFACE VKSURFACEKHR)
 (PPRESENTMODECOUNT :POINTER) (PPRESENTMODES :POINTER))

(VULKAN-DEFCFUN ("vkCreateSwapchainKHR" VKCREATESWAPCHAINKHR) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PSWAPCHAIN :POINTER))

(VULKAN-DEFCFUN ("vkDestroySwapchainKHR" VKDESTROYSWAPCHAINKHR) :VOID
 (DEVICE VKDEVICE) (SWAPCHAIN VKSWAPCHAINKHR) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkGetSwapchainImagesKHR" VKGETSWAPCHAINIMAGESKHR) VKRESULT
 (DEVICE VKDEVICE) (SWAPCHAIN VKSWAPCHAINKHR) (PSWAPCHAINIMAGECOUNT :POINTER)
 (PSWAPCHAINIMAGES :POINTER))

(VULKAN-DEFCFUN ("vkAcquireNextImageKHR" VKACQUIRENEXTIMAGEKHR) VKRESULT
 (DEVICE VKDEVICE) (SWAPCHAIN VKSWAPCHAINKHR) (TIMEOUT :UINT64)
 (SEMAPHORE VKSEMAPHORE) (FENCE VKFENCE) (PIMAGEINDEX :POINTER))

(VULKAN-DEFCFUN ("vkQueuePresentKHR" VKQUEUEPRESENTKHR) VKRESULT
 (QUEUE VKQUEUE) (PPRESENTINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceGroupPresentCapabilitiesKHR"
  VKGETDEVICEGROUPPRESENTCAPABILITIESKHR)
 VKRESULT (DEVICE VKDEVICE) (PDEVICEGROUPPRESENTCAPABILITIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceGroupSurfacePresentModesKHR"
  VKGETDEVICEGROUPSURFACEPRESENTMODESKHR)
 VKRESULT (DEVICE VKDEVICE) (SURFACE VKSURFACEKHR) (PMODES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDevicePresentRectanglesKHR"
  VKGETPHYSICALDEVICEPRESENTRECTANGLESKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (SURFACE VKSURFACEKHR)
 (PRECTCOUNT :POINTER) (PRECTS :POINTER))

(VULKAN-DEFCFUN ("vkAcquireNextImage2KHR" VKACQUIRENEXTIMAGE2KHR) VKRESULT
 (DEVICE VKDEVICE) (PACQUIREINFO :POINTER) (PIMAGEINDEX :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceDisplayPropertiesKHR"
  VKGETPHYSICALDEVICEDISPLAYPROPERTIESKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PPROPERTYCOUNT :POINTER)
 (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceDisplayPlanePropertiesKHR"
  VKGETPHYSICALDEVICEDISPLAYPLANEPROPERTIESKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PPROPERTYCOUNT :POINTER)
 (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDisplayPlaneSupportedDisplaysKHR"
  VKGETDISPLAYPLANESUPPORTEDDISPLAYSKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PLANEINDEX :UINT32)
 (PDISPLAYCOUNT :POINTER) (PDISPLAYS :POINTER))

(VULKAN-DEFCFUN ("vkGetDisplayModePropertiesKHR" VKGETDISPLAYMODEPROPERTIESKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (DISPLAY VKDISPLAYKHR)
 (PPROPERTYCOUNT :POINTER) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkCreateDisplayModeKHR" VKCREATEDISPLAYMODEKHR) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (DISPLAY VKDISPLAYKHR)
 (PCREATEINFO :POINTER) (PALLOCATOR :POINTER) (PMODE :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDisplayPlaneCapabilitiesKHR" VKGETDISPLAYPLANECAPABILITIESKHR) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (MODE VKDISPLAYMODEKHR) (PLANEINDEX :UINT32)
 (PCAPABILITIES :POINTER))

(VULKAN-DEFCFUN
 ("vkCreateDisplayPlaneSurfaceKHR" VKCREATEDISPLAYPLANESURFACEKHR) VKRESULT
 (INSTANCE VKINSTANCE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PSURFACE :POINTER))

(VULKAN-DEFCFUN ("vkCreateSharedSwapchainsKHR" VKCREATESHAREDSWAPCHAINSKHR)
 VKRESULT (DEVICE VKDEVICE) (SWAPCHAINCOUNT :UINT32) (PCREATEINFOS :POINTER)
 (PALLOCATOR :POINTER) (PSWAPCHAINS :POINTER))

(VULKAN-DEFCFUN ("vkCmdBeginRenderingKHR" VKCMDBEGINRENDERINGKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRENDERINGINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdEndRenderingKHR" VKCMDENDRENDERINGKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceFeatures2KHR" VKGETPHYSICALDEVICEFEATURES2KHR) :VOID
 (PHYSICALDEVICE VKPHYSICALDEVICE) (PFEATURES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceProperties2KHR" VKGETPHYSICALDEVICEPROPERTIES2KHR) :VOID
 (PHYSICALDEVICE VKPHYSICALDEVICE) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceFormatProperties2KHR"
  VKGETPHYSICALDEVICEFORMATPROPERTIES2KHR)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (FORMAT VKFORMAT)
 (PFORMATPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceImageFormatProperties2KHR"
  VKGETPHYSICALDEVICEIMAGEFORMATPROPERTIES2KHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PIMAGEFORMATINFO :POINTER)
 (PIMAGEFORMATPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceQueueFamilyProperties2KHR"
  VKGETPHYSICALDEVICEQUEUEFAMILYPROPERTIES2KHR)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PQUEUEFAMILYPROPERTYCOUNT :POINTER)
 (PQUEUEFAMILYPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceMemoryProperties2KHR"
  VKGETPHYSICALDEVICEMEMORYPROPERTIES2KHR)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PMEMORYPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSparseImageFormatProperties2KHR"
  VKGETPHYSICALDEVICESPARSEIMAGEFORMATPROPERTIES2KHR)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PFORMATINFO :POINTER)
 (PPROPERTYCOUNT :POINTER) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceGroupPeerMemoryFeaturesKHR"
  VKGETDEVICEGROUPPEERMEMORYFEATURESKHR)
 :VOID (DEVICE VKDEVICE) (HEAPINDEX :UINT32) (LOCALDEVICEINDEX :UINT32)
 (REMOTEDEVICEINDEX :UINT32) (PPEERMEMORYFEATURES :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetDeviceMaskKHR" VKCMDSETDEVICEMASKKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEVICEMASK :UINT32))

(VULKAN-DEFCFUN ("vkCmdDispatchBaseKHR" VKCMDDISPATCHBASEKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BASEGROUPX :UINT32) (BASEGROUPY :UINT32)
 (BASEGROUPZ :UINT32) (GROUPCOUNTX :UINT32) (GROUPCOUNTY :UINT32)
 (GROUPCOUNTZ :UINT32))

(VULKAN-DEFCFUN ("vkTrimCommandPoolKHR" VKTRIMCOMMANDPOOLKHR) :VOID
 (DEVICE VKDEVICE) (COMMANDPOOL VKCOMMANDPOOL) (FLAGS VKCOMMANDPOOLTRIMFLAGS))

(VULKAN-DEFCFUN
 ("vkEnumeratePhysicalDeviceGroupsKHR" VKENUMERATEPHYSICALDEVICEGROUPSKHR)
 VKRESULT (INSTANCE VKINSTANCE) (PPHYSICALDEVICEGROUPCOUNT :POINTER)
 (PPHYSICALDEVICEGROUPPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceExternalBufferPropertiesKHR"
  VKGETPHYSICALDEVICEEXTERNALBUFFERPROPERTIESKHR)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PEXTERNALBUFFERINFO :POINTER)
 (PEXTERNALBUFFERPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkGetMemoryFdKHR" VKGETMEMORYFDKHR) VKRESULT
 (DEVICE VKDEVICE) (PGETFDINFO :POINTER) (PFD :POINTER))

(VULKAN-DEFCFUN ("vkGetMemoryFdPropertiesKHR" VKGETMEMORYFDPROPERTIESKHR)
 VKRESULT (DEVICE VKDEVICE) (HANDLETYPE VKEXTERNALMEMORYHANDLETYPEFLAGBITS)
 (FD :INT) (PMEMORYFDPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceExternalSemaphorePropertiesKHR"
  VKGETPHYSICALDEVICEEXTERNALSEMAPHOREPROPERTIESKHR)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PEXTERNALSEMAPHOREINFO :POINTER)
 (PEXTERNALSEMAPHOREPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkImportSemaphoreFdKHR" VKIMPORTSEMAPHOREFDKHR) VKRESULT
 (DEVICE VKDEVICE) (PIMPORTSEMAPHOREFDINFO :POINTER))

(VULKAN-DEFCFUN ("vkGetSemaphoreFdKHR" VKGETSEMAPHOREFDKHR) VKRESULT
 (DEVICE VKDEVICE) (PGETFDINFO :POINTER) (PFD :POINTER))

(VULKAN-DEFCFUN ("vkCmdPushDescriptorSetKHR" VKCMDPUSHDESCRIPTORSETKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PIPELINEBINDPOINT VKPIPELINEBINDPOINT)
 (LAYOUT VKPIPELINELAYOUT) (SET :UINT32) (DESCRIPTORWRITECOUNT :UINT32)
 (PDESCRIPTORWRITES :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdPushDescriptorSetWithTemplateKHR"
  VKCMDPUSHDESCRIPTORSETWITHTEMPLATEKHR)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER)
 (DESCRIPTORUPDATETEMPLATE VKDESCRIPTORUPDATETEMPLATE)
 (LAYOUT VKPIPELINELAYOUT) (SET :UINT32) (PDATA :POINTER))

(VULKAN-DEFCFUN
 ("vkCreateDescriptorUpdateTemplateKHR" VKCREATEDESCRIPTORUPDATETEMPLATEKHR)
 VKRESULT (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PDESCRIPTORUPDATETEMPLATE :POINTER))

(VULKAN-DEFCFUN
 ("vkDestroyDescriptorUpdateTemplateKHR" VKDESTROYDESCRIPTORUPDATETEMPLATEKHR)
 :VOID (DEVICE VKDEVICE) (DESCRIPTORUPDATETEMPLATE VKDESCRIPTORUPDATETEMPLATE)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN
 ("vkUpdateDescriptorSetWithTemplateKHR" VKUPDATEDESCRIPTORSETWITHTEMPLATEKHR)
 :VOID (DEVICE VKDEVICE) (DESCRIPTORSET VKDESCRIPTORSET)
 (DESCRIPTORUPDATETEMPLATE VKDESCRIPTORUPDATETEMPLATE) (PDATA :POINTER))

(VULKAN-DEFCFUN ("vkCreateRenderPass2KHR" VKCREATERENDERPASS2KHR) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PRENDERPASS :POINTER))

(VULKAN-DEFCFUN ("vkCmdBeginRenderPass2KHR" VKCMDBEGINRENDERPASS2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRENDERPASSBEGIN :POINTER)
 (PSUBPASSBEGININFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdNextSubpass2KHR" VKCMDNEXTSUBPASS2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PSUBPASSBEGININFO :POINTER)
 (PSUBPASSENDINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdEndRenderPass2KHR" VKCMDENDRENDERPASS2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PSUBPASSENDINFO :POINTER))

(VULKAN-DEFCFUN ("vkGetSwapchainStatusKHR" VKGETSWAPCHAINSTATUSKHR) VKRESULT
 (DEVICE VKDEVICE) (SWAPCHAIN VKSWAPCHAINKHR))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceExternalFencePropertiesKHR"
  VKGETPHYSICALDEVICEEXTERNALFENCEPROPERTIESKHR)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PEXTERNALFENCEINFO :POINTER)
 (PEXTERNALFENCEPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkImportFenceFdKHR" VKIMPORTFENCEFDKHR) VKRESULT
 (DEVICE VKDEVICE) (PIMPORTFENCEFDINFO :POINTER))

(VULKAN-DEFCFUN ("vkGetFenceFdKHR" VKGETFENCEFDKHR) VKRESULT (DEVICE VKDEVICE)
 (PGETFDINFO :POINTER) (PFD :POINTER))

(VULKAN-DEFCFUN
 ("vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR"
  VKENUMERATEPHYSICALDEVICEQUEUEFAMILYPERFORMANCEQUERYCOUNTERSKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (QUEUEFAMILYINDEX :UINT32)
 (PCOUNTERCOUNT :POINTER) (PCOUNTERS :POINTER) (PCOUNTERDESCRIPTIONS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR"
  VKGETPHYSICALDEVICEQUEUEFAMILYPERFORMANCEQUERYPASSESKHR)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (PPERFORMANCEQUERYCREATEINFO :POINTER)
 (PNUMPASSES :POINTER))

(VULKAN-DEFCFUN ("vkAcquireProfilingLockKHR" VKACQUIREPROFILINGLOCKKHR)
 VKRESULT (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN ("vkReleaseProfilingLockKHR" VKRELEASEPROFILINGLOCKKHR) :VOID
 (DEVICE VKDEVICE))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSurfaceCapabilities2KHR"
  VKGETPHYSICALDEVICESURFACECAPABILITIES2KHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PSURFACEINFO :POINTER)
 (PSURFACECAPABILITIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSurfaceFormats2KHR"
  VKGETPHYSICALDEVICESURFACEFORMATS2KHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PSURFACEINFO :POINTER)
 (PSURFACEFORMATCOUNT :POINTER) (PSURFACEFORMATS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceDisplayProperties2KHR"
  VKGETPHYSICALDEVICEDISPLAYPROPERTIES2KHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PPROPERTYCOUNT :POINTER)
 (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceDisplayPlaneProperties2KHR"
  VKGETPHYSICALDEVICEDISPLAYPLANEPROPERTIES2KHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PPROPERTYCOUNT :POINTER)
 (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDisplayModeProperties2KHR" VKGETDISPLAYMODEPROPERTIES2KHR) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (DISPLAY VKDISPLAYKHR)
 (PPROPERTYCOUNT :POINTER) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDisplayPlaneCapabilities2KHR" VKGETDISPLAYPLANECAPABILITIES2KHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PDISPLAYPLANEINFO :POINTER)
 (PCAPABILITIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetImageMemoryRequirements2KHR" VKGETIMAGEMEMORYREQUIREMENTS2KHR) :VOID
 (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetBufferMemoryRequirements2KHR" VKGETBUFFERMEMORYREQUIREMENTS2KHR) :VOID
 (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetImageSparseMemoryRequirements2KHR"
  VKGETIMAGESPARSEMEMORYREQUIREMENTS2KHR)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER)
 (PSPARSEMEMORYREQUIREMENTCOUNT :POINTER) (PSPARSEMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkCreateSamplerYcbcrConversionKHR" VKCREATESAMPLERYCBCRCONVERSIONKHR)
 VKRESULT (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PYCBCRCONVERSION :POINTER))

(VULKAN-DEFCFUN
 ("vkDestroySamplerYcbcrConversionKHR" VKDESTROYSAMPLERYCBCRCONVERSIONKHR)
 :VOID (DEVICE VKDEVICE) (YCBCRCONVERSION VKSAMPLERYCBCRCONVERSION)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkBindBufferMemory2KHR" VKBINDBUFFERMEMORY2KHR) VKRESULT
 (DEVICE VKDEVICE) (BINDINFOCOUNT :UINT32) (PBINDINFOS :POINTER))

(VULKAN-DEFCFUN ("vkBindImageMemory2KHR" VKBINDIMAGEMEMORY2KHR) VKRESULT
 (DEVICE VKDEVICE) (BINDINFOCOUNT :UINT32) (PBINDINFOS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDescriptorSetLayoutSupportKHR" VKGETDESCRIPTORSETLAYOUTSUPPORTKHR)
 :VOID (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PSUPPORT :POINTER))

(VULKAN-DEFCFUN ("vkCmdDrawIndirectCountKHR" VKCMDDRAWINDIRECTCOUNTKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (COUNTBUFFER VKBUFFER) (COUNTBUFFEROFFSET VKDEVICESIZE) (MAXDRAWCOUNT :UINT32)
 (STRIDE :UINT32))

(VULKAN-DEFCFUN
 ("vkCmdDrawIndexedIndirectCountKHR" VKCMDDRAWINDEXEDINDIRECTCOUNTKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (COUNTBUFFER VKBUFFER) (COUNTBUFFEROFFSET VKDEVICESIZE) (MAXDRAWCOUNT :UINT32)
 (STRIDE :UINT32))

(VULKAN-DEFCFUN ("vkGetSemaphoreCounterValueKHR" VKGETSEMAPHORECOUNTERVALUEKHR)
 VKRESULT (DEVICE VKDEVICE) (SEMAPHORE VKSEMAPHORE) (PVALUE :POINTER))

(VULKAN-DEFCFUN ("vkWaitSemaphoresKHR" VKWAITSEMAPHORESKHR) VKRESULT
 (DEVICE VKDEVICE) (PWAITINFO :POINTER) (TIMEOUT :UINT64))

(VULKAN-DEFCFUN ("vkSignalSemaphoreKHR" VKSIGNALSEMAPHOREKHR) VKRESULT
 (DEVICE VKDEVICE) (PSIGNALINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceFragmentShadingRatesKHR"
  VKGETPHYSICALDEVICEFRAGMENTSHADINGRATESKHR)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE)
 (PFRAGMENTSHADINGRATECOUNT :POINTER) (PFRAGMENTSHADINGRATES :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdSetFragmentShadingRateKHR" VKCMDSETFRAGMENTSHADINGRATEKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PFRAGMENTSIZE :POINTER)
 (COMBINEROPS VKFRAGMENTSHADINGRATECOMBINEROPKHR))

(VULKAN-DEFCFUN ("vkWaitForPresentKHR" VKWAITFORPRESENTKHR) VKRESULT
 (DEVICE VKDEVICE) (SWAPCHAIN VKSWAPCHAINKHR) (PRESENTID :UINT64)
 (TIMEOUT :UINT64))

(VULKAN-DEFCFUN ("vkGetBufferDeviceAddressKHR" VKGETBUFFERDEVICEADDRESSKHR)
 VKDEVICEADDRESS (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetBufferOpaqueCaptureAddressKHR" VKGETBUFFEROPAQUECAPTUREADDRESSKHR)
 :UINT64 (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceMemoryOpaqueCaptureAddressKHR"
  VKGETDEVICEMEMORYOPAQUECAPTUREADDRESSKHR)
 :UINT64 (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN ("vkCreateDeferredOperationKHR" VKCREATEDEFERREDOPERATIONKHR)
 VKRESULT (DEVICE VKDEVICE) (PALLOCATOR :POINTER) (PDEFERREDOPERATION :POINTER))

(VULKAN-DEFCFUN ("vkDestroyDeferredOperationKHR" VKDESTROYDEFERREDOPERATIONKHR)
 :VOID (DEVICE VKDEVICE) (OPERATION VKDEFERREDOPERATIONKHR)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeferredOperationMaxConcurrencyKHR"
  VKGETDEFERREDOPERATIONMAXCONCURRENCYKHR)
 :UINT32 (DEVICE VKDEVICE) (OPERATION VKDEFERREDOPERATIONKHR))

(VULKAN-DEFCFUN
 ("vkGetDeferredOperationResultKHR" VKGETDEFERREDOPERATIONRESULTKHR) VKRESULT
 (DEVICE VKDEVICE) (OPERATION VKDEFERREDOPERATIONKHR))

(VULKAN-DEFCFUN ("vkDeferredOperationJoinKHR" VKDEFERREDOPERATIONJOINKHR)
 VKRESULT (DEVICE VKDEVICE) (OPERATION VKDEFERREDOPERATIONKHR))

(VULKAN-DEFCFUN
 ("vkGetPipelineExecutablePropertiesKHR" VKGETPIPELINEEXECUTABLEPROPERTIESKHR)
 VKRESULT (DEVICE VKDEVICE) (PPIPELINEINFO :POINTER)
 (PEXECUTABLECOUNT :POINTER) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPipelineExecutableStatisticsKHR" VKGETPIPELINEEXECUTABLESTATISTICSKHR)
 VKRESULT (DEVICE VKDEVICE) (PEXECUTABLEINFO :POINTER)
 (PSTATISTICCOUNT :POINTER) (PSTATISTICS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPipelineExecutableInternalRepresentationsKHR"
  VKGETPIPELINEEXECUTABLEINTERNALREPRESENTATIONSKHR)
 VKRESULT (DEVICE VKDEVICE) (PEXECUTABLEINFO :POINTER)
 (PINTERNALREPRESENTATIONCOUNT :POINTER) (PINTERNALREPRESENTATIONS :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetEvent2KHR" VKCMDSETEVENT2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (EVENT VKEVENT) (PDEPENDENCYINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdResetEvent2KHR" VKCMDRESETEVENT2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (EVENT VKEVENT)
 (STAGEMASK VKPIPELINESTAGEFLAGS2))

(VULKAN-DEFCFUN ("vkCmdWaitEvents2KHR" VKCMDWAITEVENTS2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (EVENTCOUNT :UINT32) (PEVENTS :POINTER)
 (PDEPENDENCYINFOS :POINTER))

(VULKAN-DEFCFUN ("vkCmdPipelineBarrier2KHR" VKCMDPIPELINEBARRIER2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PDEPENDENCYINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdWriteTimestamp2KHR" VKCMDWRITETIMESTAMP2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (STAGE VKPIPELINESTAGEFLAGS2)
 (QUERYPOOL VKQUERYPOOL) (QUERY :UINT32))

(VULKAN-DEFCFUN ("vkQueueSubmit2KHR" VKQUEUESUBMIT2KHR) VKRESULT
 (QUEUE VKQUEUE) (SUBMITCOUNT :UINT32) (PSUBMITS :POINTER) (FENCE VKFENCE))

(VULKAN-DEFCFUN ("vkCmdWriteBufferMarker2AMD" VKCMDWRITEBUFFERMARKER2AMD) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (STAGE VKPIPELINESTAGEFLAGS2)
 (DSTBUFFER VKBUFFER) (DSTOFFSET VKDEVICESIZE) (MARKER :UINT32))

(VULKAN-DEFCFUN ("vkGetQueueCheckpointData2NV" VKGETQUEUECHECKPOINTDATA2NV)
 :VOID (QUEUE VKQUEUE) (PCHECKPOINTDATACOUNT :POINTER)
 (PCHECKPOINTDATA :POINTER))

(VULKAN-DEFCFUN ("vkCmdCopyBuffer2KHR" VKCMDCOPYBUFFER2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCOPYBUFFERINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdCopyImage2KHR" VKCMDCOPYIMAGE2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCOPYIMAGEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdCopyBufferToImage2KHR" VKCMDCOPYBUFFERTOIMAGE2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCOPYBUFFERTOIMAGEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdCopyImageToBuffer2KHR" VKCMDCOPYIMAGETOBUFFER2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCOPYIMAGETOBUFFERINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdBlitImage2KHR" VKCMDBLITIMAGE2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PBLITIMAGEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdResolveImage2KHR" VKCMDRESOLVEIMAGE2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRESOLVEIMAGEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdTraceRaysIndirect2KHR" VKCMDTRACERAYSINDIRECT2KHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (INDIRECTDEVICEADDRESS VKDEVICEADDRESS))

(VULKAN-DEFCFUN
 ("vkGetDeviceBufferMemoryRequirementsKHR"
  VKGETDEVICEBUFFERMEMORYREQUIREMENTSKHR)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceImageMemoryRequirementsKHR"
  VKGETDEVICEIMAGEMEMORYREQUIREMENTSKHR)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceImageSparseMemoryRequirementsKHR"
  VKGETDEVICEIMAGESPARSEMEMORYREQUIREMENTSKHR)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER)
 (PSPARSEMEMORYREQUIREMENTCOUNT :POINTER) (PSPARSEMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkCreateDebugReportCallbackEXT" VKCREATEDEBUGREPORTCALLBACKEXT) VKRESULT
 (INSTANCE VKINSTANCE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PCALLBACK :POINTER))

(VULKAN-DEFCFUN
 ("vkDestroyDebugReportCallbackEXT" VKDESTROYDEBUGREPORTCALLBACKEXT) :VOID
 (INSTANCE VKINSTANCE) (CALLBACK VKDEBUGREPORTCALLBACKEXT)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkDebugReportMessageEXT" VKDEBUGREPORTMESSAGEEXT) :VOID
 (INSTANCE VKINSTANCE) (FLAGS VKDEBUGREPORTFLAGSEXT)
 (OBJECTTYPE VKDEBUGREPORTOBJECTTYPEEXT) (OBJECT :UINT64) (LOCATION :SIZE)
 (MESSAGECODE :INT32) (PLAYERPREFIX :POINTER) (PMESSAGE :POINTER))

(VULKAN-DEFCFUN ("vkDebugMarkerSetObjectTagEXT" VKDEBUGMARKERSETOBJECTTAGEXT)
 VKRESULT (DEVICE VKDEVICE) (PTAGINFO :POINTER))

(VULKAN-DEFCFUN ("vkDebugMarkerSetObjectNameEXT" VKDEBUGMARKERSETOBJECTNAMEEXT)
 VKRESULT (DEVICE VKDEVICE) (PNAMEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdDebugMarkerBeginEXT" VKCMDDEBUGMARKERBEGINEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PMARKERINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdDebugMarkerEndEXT" VKCMDDEBUGMARKERENDEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER))

(VULKAN-DEFCFUN ("vkCmdDebugMarkerInsertEXT" VKCMDDEBUGMARKERINSERTEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PMARKERINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdBindTransformFeedbackBuffersEXT" VKCMDBINDTRANSFORMFEEDBACKBUFFERSEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTBINDING :UINT32)
 (BINDINGCOUNT :UINT32) (PBUFFERS :POINTER) (POFFSETS :POINTER)
 (PSIZES :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdBeginTransformFeedbackEXT" VKCMDBEGINTRANSFORMFEEDBACKEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTCOUNTERBUFFER :UINT32)
 (COUNTERBUFFERCOUNT :UINT32) (PCOUNTERBUFFERS :POINTER)
 (PCOUNTERBUFFEROFFSETS :POINTER))

(VULKAN-DEFCFUN ("vkCmdEndTransformFeedbackEXT" VKCMDENDTRANSFORMFEEDBACKEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTCOUNTERBUFFER :UINT32)
 (COUNTERBUFFERCOUNT :UINT32) (PCOUNTERBUFFERS :POINTER)
 (PCOUNTERBUFFEROFFSETS :POINTER))

(VULKAN-DEFCFUN ("vkCmdBeginQueryIndexedEXT" VKCMDBEGINQUERYINDEXEDEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (QUERYPOOL VKQUERYPOOL) (QUERY :UINT32)
 (FLAGS VKQUERYCONTROLFLAGS) (INDEX :UINT32))

(VULKAN-DEFCFUN ("vkCmdEndQueryIndexedEXT" VKCMDENDQUERYINDEXEDEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (QUERYPOOL VKQUERYPOOL) (QUERY :UINT32)
 (INDEX :UINT32))

(VULKAN-DEFCFUN ("vkCmdDrawIndirectByteCountEXT" VKCMDDRAWINDIRECTBYTECOUNTEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (INSTANCECOUNT :UINT32)
 (FIRSTINSTANCE :UINT32) (COUNTERBUFFER VKBUFFER)
 (COUNTERBUFFEROFFSET VKDEVICESIZE) (COUNTEROFFSET :UINT32)
 (VERTEXSTRIDE :UINT32))

(VULKAN-DEFCFUN ("vkCreateCuModuleNVX" VKCREATECUMODULENVX) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PMODULE :POINTER))

(VULKAN-DEFCFUN ("vkCreateCuFunctionNVX" VKCREATECUFUNCTIONNVX) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PFUNCTION :POINTER))

(VULKAN-DEFCFUN ("vkDestroyCuModuleNVX" VKDESTROYCUMODULENVX) :VOID
 (DEVICE VKDEVICE) (MODULE VKCUMODULENVX) (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkDestroyCuFunctionNVX" VKDESTROYCUFUNCTIONNVX) :VOID
 (DEVICE VKDEVICE) #'VKCUFUNCTIONNVX (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkCmdCuLaunchKernelNVX" VKCMDCULAUNCHKERNELNVX) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PLAUNCHINFO :POINTER))

(VULKAN-DEFCFUN ("vkGetImageViewHandleNVX" VKGETIMAGEVIEWHANDLENVX) :UINT32
 (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN ("vkGetImageViewAddressNVX" VKGETIMAGEVIEWADDRESSNVX) VKRESULT
 (DEVICE VKDEVICE) (IMAGEVIEW VKIMAGEVIEW) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkCmdDrawIndirectCountAMD" VKCMDDRAWINDIRECTCOUNTAMD) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (COUNTBUFFER VKBUFFER) (COUNTBUFFEROFFSET VKDEVICESIZE) (MAXDRAWCOUNT :UINT32)
 (STRIDE :UINT32))

(VULKAN-DEFCFUN
 ("vkCmdDrawIndexedIndirectCountAMD" VKCMDDRAWINDEXEDINDIRECTCOUNTAMD) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (COUNTBUFFER VKBUFFER) (COUNTBUFFEROFFSET VKDEVICESIZE) (MAXDRAWCOUNT :UINT32)
 (STRIDE :UINT32))

(VULKAN-DEFCFUN ("vkGetShaderInfoAMD" VKGETSHADERINFOAMD) VKRESULT
 (DEVICE VKDEVICE) (PIPELINE VKPIPELINE) (SHADERSTAGE VKSHADERSTAGEFLAGBITS)
 (INFOTYPE VKSHADERINFOTYPEAMD) (PINFOSIZE :POINTER) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceExternalImageFormatPropertiesNV"
  VKGETPHYSICALDEVICEEXTERNALIMAGEFORMATPROPERTIESNV)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (FORMAT VKFORMAT)
 (TYPE VKIMAGETYPE) (TILING VKIMAGETILING) (USAGE VKIMAGEUSAGEFLAGS)
 (FLAGS VKIMAGECREATEFLAGS)
 (EXTERNALHANDLETYPE VKEXTERNALMEMORYHANDLETYPEFLAGSNV)
 (PEXTERNALIMAGEFORMATPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdBeginConditionalRenderingEXT" VKCMDBEGINCONDITIONALRENDERINGEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCONDITIONALRENDERINGBEGIN :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdEndConditionalRenderingEXT" VKCMDENDCONDITIONALRENDERINGEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER))

(VULKAN-DEFCFUN ("vkCmdSetViewportWScalingNV" VKCMDSETVIEWPORTWSCALINGNV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTVIEWPORT :UINT32)
 (VIEWPORTCOUNT :UINT32) (PVIEWPORTWSCALINGS :POINTER))

(VULKAN-DEFCFUN ("vkReleaseDisplayEXT" VKRELEASEDISPLAYEXT) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (DISPLAY VKDISPLAYKHR))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSurfaceCapabilities2EXT"
  VKGETPHYSICALDEVICESURFACECAPABILITIES2EXT)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (SURFACE VKSURFACEKHR)
 (PSURFACECAPABILITIES :POINTER))

(VULKAN-DEFCFUN ("vkDisplayPowerControlEXT" VKDISPLAYPOWERCONTROLEXT) VKRESULT
 (DEVICE VKDEVICE) (DISPLAY VKDISPLAYKHR) (PDISPLAYPOWERINFO :POINTER))

(VULKAN-DEFCFUN ("vkRegisterDeviceEventEXT" VKREGISTERDEVICEEVENTEXT) VKRESULT
 (DEVICE VKDEVICE) (PDEVICEEVENTINFO :POINTER) (PALLOCATOR :POINTER)
 (PFENCE :POINTER))

(VULKAN-DEFCFUN ("vkRegisterDisplayEventEXT" VKREGISTERDISPLAYEVENTEXT)
 VKRESULT (DEVICE VKDEVICE) (DISPLAY VKDISPLAYKHR) (PDISPLAYEVENTINFO :POINTER)
 (PALLOCATOR :POINTER) (PFENCE :POINTER))

(VULKAN-DEFCFUN ("vkGetSwapchainCounterEXT" VKGETSWAPCHAINCOUNTEREXT) VKRESULT
 (DEVICE VKDEVICE) (SWAPCHAIN VKSWAPCHAINKHR)
 (COUNTER VKSURFACECOUNTERFLAGBITSEXT) (PCOUNTERVALUE :POINTER))

(VULKAN-DEFCFUN
 ("vkGetRefreshCycleDurationGOOGLE" VKGETREFRESHCYCLEDURATIONGOOGLE) VKRESULT
 (DEVICE VKDEVICE) (SWAPCHAIN VKSWAPCHAINKHR)
 (PDISPLAYTIMINGPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPastPresentationTimingGOOGLE" VKGETPASTPRESENTATIONTIMINGGOOGLE)
 VKRESULT (DEVICE VKDEVICE) (SWAPCHAIN VKSWAPCHAINKHR)
 (PPRESENTATIONTIMINGCOUNT :POINTER) (PPRESENTATIONTIMINGS :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetDiscardRectangleEXT" VKCMDSETDISCARDRECTANGLEEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTDISCARDRECTANGLE :UINT32)
 (DISCARDRECTANGLECOUNT :UINT32) (PDISCARDRECTANGLES :POINTER))

(VULKAN-DEFCFUN ("vkSetHdrMetadataEXT" VKSETHDRMETADATAEXT) :VOID
 (DEVICE VKDEVICE) (SWAPCHAINCOUNT :UINT32) (PSWAPCHAINS :POINTER)
 (PMETADATA :POINTER))

(VULKAN-DEFCFUN ("vkSetDebugUtilsObjectNameEXT" VKSETDEBUGUTILSOBJECTNAMEEXT)
 VKRESULT (DEVICE VKDEVICE) (PNAMEINFO :POINTER))

(VULKAN-DEFCFUN ("vkSetDebugUtilsObjectTagEXT" VKSETDEBUGUTILSOBJECTTAGEXT)
 VKRESULT (DEVICE VKDEVICE) (PTAGINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkQueueBeginDebugUtilsLabelEXT" VKQUEUEBEGINDEBUGUTILSLABELEXT) :VOID
 (QUEUE VKQUEUE) (PLABELINFO :POINTER))

(VULKAN-DEFCFUN ("vkQueueEndDebugUtilsLabelEXT" VKQUEUEENDDEBUGUTILSLABELEXT)
 :VOID (QUEUE VKQUEUE))

(VULKAN-DEFCFUN
 ("vkQueueInsertDebugUtilsLabelEXT" VKQUEUEINSERTDEBUGUTILSLABELEXT) :VOID
 (QUEUE VKQUEUE) (PLABELINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdBeginDebugUtilsLabelEXT" VKCMDBEGINDEBUGUTILSLABELEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (PLABELINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdEndDebugUtilsLabelEXT" VKCMDENDDEBUGUTILSLABELEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER))

(VULKAN-DEFCFUN ("vkCmdInsertDebugUtilsLabelEXT" VKCMDINSERTDEBUGUTILSLABELEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (PLABELINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCreateDebugUtilsMessengerEXT" VKCREATEDEBUGUTILSMESSENGEREXT) VKRESULT
 (INSTANCE VKINSTANCE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PMESSENGER :POINTER))

(VULKAN-DEFCFUN
 ("vkDestroyDebugUtilsMessengerEXT" VKDESTROYDEBUGUTILSMESSENGEREXT) :VOID
 (INSTANCE VKINSTANCE) (MESSENGER VKDEBUGUTILSMESSENGEREXT)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkSubmitDebugUtilsMessageEXT" VKSUBMITDEBUGUTILSMESSAGEEXT)
 :VOID (INSTANCE VKINSTANCE)
 (MESSAGESEVERITY VKDEBUGUTILSMESSAGESEVERITYFLAGBITSEXT)
 (MESSAGETYPES VKDEBUGUTILSMESSAGETYPEFLAGSEXT) (PCALLBACKDATA :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetSampleLocationsEXT" VKCMDSETSAMPLELOCATIONSEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PSAMPLELOCATIONSINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceMultisamplePropertiesEXT"
  VKGETPHYSICALDEVICEMULTISAMPLEPROPERTIESEXT)
 :VOID (PHYSICALDEVICE VKPHYSICALDEVICE) (SAMPLES VKSAMPLECOUNTFLAGBITS)
 (PMULTISAMPLEPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetImageDrmFormatModifierPropertiesEXT"
  VKGETIMAGEDRMFORMATMODIFIERPROPERTIESEXT)
 VKRESULT (DEVICE VKDEVICE) (IMAGE VKIMAGE) (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkCreateValidationCacheEXT" VKCREATEVALIDATIONCACHEEXT)
 VKRESULT (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PVALIDATIONCACHE :POINTER))

(VULKAN-DEFCFUN ("vkDestroyValidationCacheEXT" VKDESTROYVALIDATIONCACHEEXT)
 :VOID (DEVICE VKDEVICE) (VALIDATIONCACHE VKVALIDATIONCACHEEXT)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkMergeValidationCachesEXT" VKMERGEVALIDATIONCACHESEXT)
 VKRESULT (DEVICE VKDEVICE) (DSTCACHE VKVALIDATIONCACHEEXT)
 (SRCCACHECOUNT :UINT32) (PSRCCACHES :POINTER))

(VULKAN-DEFCFUN ("vkGetValidationCacheDataEXT" VKGETVALIDATIONCACHEDATAEXT)
 VKRESULT (DEVICE VKDEVICE) (VALIDATIONCACHE VKVALIDATIONCACHEEXT)
 (PDATASIZE :POINTER) (PDATA :POINTER))

(VULKAN-DEFCFUN ("vkCmdBindShadingRateImageNV" VKCMDBINDSHADINGRATEIMAGENV)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (IMAGEVIEW VKIMAGEVIEW)
 (IMAGELAYOUT VKIMAGELAYOUT))

(VULKAN-DEFCFUN
 ("vkCmdSetViewportShadingRatePaletteNV" VKCMDSETVIEWPORTSHADINGRATEPALETTENV)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTVIEWPORT :UINT32)
 (VIEWPORTCOUNT :UINT32) (PSHADINGRATEPALETTES :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetCoarseSampleOrderNV" VKCMDSETCOARSESAMPLEORDERNV)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER)
 (SAMPLEORDERTYPE VKCOARSESAMPLEORDERTYPENV) (CUSTOMSAMPLEORDERCOUNT :UINT32)
 (PCUSTOMSAMPLEORDERS :POINTER))

(VULKAN-DEFCFUN
 ("vkCreateAccelerationStructureNV" VKCREATEACCELERATIONSTRUCTURENV) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PACCELERATIONSTRUCTURE :POINTER))

(VULKAN-DEFCFUN
 ("vkDestroyAccelerationStructureNV" VKDESTROYACCELERATIONSTRUCTURENV) :VOID
 (DEVICE VKDEVICE) (ACCELERATIONSTRUCTURE VKACCELERATIONSTRUCTURENV)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN
 ("vkGetAccelerationStructureMemoryRequirementsNV"
  VKGETACCELERATIONSTRUCTUREMEMORYREQUIREMENTSNV)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkBindAccelerationStructureMemoryNV" VKBINDACCELERATIONSTRUCTUREMEMORYNV)
 VKRESULT (DEVICE VKDEVICE) (BINDINFOCOUNT :UINT32) (PBINDINFOS :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdBuildAccelerationStructureNV" VKCMDBUILDACCELERATIONSTRUCTURENV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PINFO :POINTER) (INSTANCEDATA VKBUFFER)
 (INSTANCEOFFSET VKDEVICESIZE) (UPDATE VKBOOL32)
 (DST VKACCELERATIONSTRUCTURENV) (SRC VKACCELERATIONSTRUCTURENV)
 (SCRATCH VKBUFFER) (SCRATCHOFFSET VKDEVICESIZE))

(VULKAN-DEFCFUN
 ("vkCmdCopyAccelerationStructureNV" VKCMDCOPYACCELERATIONSTRUCTURENV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DST VKACCELERATIONSTRUCTURENV)
 (SRC VKACCELERATIONSTRUCTURENV) (MODE VKCOPYACCELERATIONSTRUCTUREMODEKHR))

(VULKAN-DEFCFUN ("vkCmdTraceRaysNV" VKCMDTRACERAYSNV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (RAYGENSHADERBINDINGTABLEBUFFER VKBUFFER)
 (RAYGENSHADERBINDINGOFFSET VKDEVICESIZE)
 (MISSSHADERBINDINGTABLEBUFFER VKBUFFER) (MISSSHADERBINDINGOFFSET VKDEVICESIZE)
 (MISSSHADERBINDINGSTRIDE VKDEVICESIZE) (HITSHADERBINDINGTABLEBUFFER VKBUFFER)
 (HITSHADERBINDINGOFFSET VKDEVICESIZE) (HITSHADERBINDINGSTRIDE VKDEVICESIZE)
 (CALLABLESHADERBINDINGTABLEBUFFER VKBUFFER)
 (CALLABLESHADERBINDINGOFFSET VKDEVICESIZE)
 (CALLABLESHADERBINDINGSTRIDE VKDEVICESIZE) (WIDTH :UINT32) (HEIGHT :UINT32)
 (DEPTH :UINT32))

(VULKAN-DEFCFUN ("vkCreateRayTracingPipelinesNV" VKCREATERAYTRACINGPIPELINESNV)
 VKRESULT (DEVICE VKDEVICE) (PIPELINECACHE VKPIPELINECACHE)
 (CREATEINFOCOUNT :UINT32) (PCREATEINFOS :POINTER) (PALLOCATOR :POINTER)
 (PPIPELINES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetRayTracingShaderGroupHandlesKHR" VKGETRAYTRACINGSHADERGROUPHANDLESKHR)
 VKRESULT (DEVICE VKDEVICE) (PIPELINE VKPIPELINE) (FIRSTGROUP :UINT32)
 (GROUPCOUNT :UINT32) (DATASIZE :SIZE) (PDATA :POINTER))

(VULKAN-DEFCFUN
 ("vkGetRayTracingShaderGroupHandlesNV" VKGETRAYTRACINGSHADERGROUPHANDLESNV)
 VKRESULT (DEVICE VKDEVICE) (PIPELINE VKPIPELINE) (FIRSTGROUP :UINT32)
 (GROUPCOUNT :UINT32) (DATASIZE :SIZE) (PDATA :POINTER))

(VULKAN-DEFCFUN
 ("vkGetAccelerationStructureHandleNV" VKGETACCELERATIONSTRUCTUREHANDLENV)
 VKRESULT (DEVICE VKDEVICE) (ACCELERATIONSTRUCTURE VKACCELERATIONSTRUCTURENV)
 (DATASIZE :SIZE) (PDATA :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdWriteAccelerationStructuresPropertiesNV"
  VKCMDWRITEACCELERATIONSTRUCTURESPROPERTIESNV)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (ACCELERATIONSTRUCTURECOUNT :UINT32)
 (PACCELERATIONSTRUCTURES :POINTER) (QUERYTYPE VKQUERYTYPE)
 (QUERYPOOL VKQUERYPOOL) (FIRSTQUERY :UINT32))

(VULKAN-DEFCFUN ("vkCompileDeferredNV" VKCOMPILEDEFERREDNV) VKRESULT
 (DEVICE VKDEVICE) (PIPELINE VKPIPELINE) (SHADER :UINT32))

(VULKAN-DEFCFUN
 ("vkGetMemoryHostPointerPropertiesEXT" VKGETMEMORYHOSTPOINTERPROPERTIESEXT)
 VKRESULT (DEVICE VKDEVICE) (HANDLETYPE VKEXTERNALMEMORYHANDLETYPEFLAGBITS)
 (PHOSTPOINTER :POINTER) (PMEMORYHOSTPOINTERPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkCmdWriteBufferMarkerAMD" VKCMDWRITEBUFFERMARKERAMD) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PIPELINESTAGE VKPIPELINESTAGEFLAGBITS)
 (DSTBUFFER VKBUFFER) (DSTOFFSET VKDEVICESIZE) (MARKER :UINT32))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceCalibrateableTimeDomainsEXT"
  VKGETPHYSICALDEVICECALIBRATEABLETIMEDOMAINSEXT)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PTIMEDOMAINCOUNT :POINTER)
 (PTIMEDOMAINS :POINTER))

(VULKAN-DEFCFUN ("vkGetCalibratedTimestampsEXT" VKGETCALIBRATEDTIMESTAMPSEXT)
 VKRESULT (DEVICE VKDEVICE) (TIMESTAMPCOUNT :UINT32) (PTIMESTAMPINFOS :POINTER)
 (PTIMESTAMPS :POINTER) (PMAXDEVIATION :POINTER))

(VULKAN-DEFCFUN ("vkCmdDrawMeshTasksNV" VKCMDDRAWMESHTASKSNV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (TASKCOUNT :UINT32) (FIRSTTASK :UINT32))

(VULKAN-DEFCFUN ("vkCmdDrawMeshTasksIndirectNV" VKCMDDRAWMESHTASKSINDIRECTNV)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (DRAWCOUNT :UINT32) (STRIDE :UINT32))

(VULKAN-DEFCFUN
 ("vkCmdDrawMeshTasksIndirectCountNV" VKCMDDRAWMESHTASKSINDIRECTCOUNTNV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (BUFFER VKBUFFER) (OFFSET VKDEVICESIZE)
 (COUNTBUFFER VKBUFFER) (COUNTBUFFEROFFSET VKDEVICESIZE) (MAXDRAWCOUNT :UINT32)
 (STRIDE :UINT32))

(VULKAN-DEFCFUN ("vkCmdSetExclusiveScissorNV" VKCMDSETEXCLUSIVESCISSORNV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTEXCLUSIVESCISSOR :UINT32)
 (EXCLUSIVESCISSORCOUNT :UINT32) (PEXCLUSIVESCISSORS :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetCheckpointNV" VKCMDSETCHECKPOINTNV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PCHECKPOINTMARKER :POINTER))

(VULKAN-DEFCFUN ("vkGetQueueCheckpointDataNV" VKGETQUEUECHECKPOINTDATANV) :VOID
 (QUEUE VKQUEUE) (PCHECKPOINTDATACOUNT :POINTER) (PCHECKPOINTDATA :POINTER))

(VULKAN-DEFCFUN
 ("vkInitializePerformanceApiINTEL" VKINITIALIZEPERFORMANCEAPIINTEL) VKRESULT
 (DEVICE VKDEVICE) (PINITIALIZEINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkUninitializePerformanceApiINTEL" VKUNINITIALIZEPERFORMANCEAPIINTEL) :VOID
 (DEVICE VKDEVICE))

(VULKAN-DEFCFUN
 ("vkCmdSetPerformanceMarkerINTEL" VKCMDSETPERFORMANCEMARKERINTEL) VKRESULT
 (COMMANDBUFFER VKCOMMANDBUFFER) (PMARKERINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdSetPerformanceStreamMarkerINTEL" VKCMDSETPERFORMANCESTREAMMARKERINTEL)
 VKRESULT (COMMANDBUFFER VKCOMMANDBUFFER) (PMARKERINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdSetPerformanceOverrideINTEL" VKCMDSETPERFORMANCEOVERRIDEINTEL) VKRESULT
 (COMMANDBUFFER VKCOMMANDBUFFER) (POVERRIDEINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkAcquirePerformanceConfigurationINTEL"
  VKACQUIREPERFORMANCECONFIGURATIONINTEL)
 VKRESULT (DEVICE VKDEVICE) (PACQUIREINFO :POINTER) (PCONFIGURATION :POINTER))

(VULKAN-DEFCFUN
 ("vkReleasePerformanceConfigurationINTEL"
  VKRELEASEPERFORMANCECONFIGURATIONINTEL)
 VKRESULT (DEVICE VKDEVICE) (CONFIGURATION VKPERFORMANCECONFIGURATIONINTEL))

(VULKAN-DEFCFUN
 ("vkQueueSetPerformanceConfigurationINTEL"
  VKQUEUESETPERFORMANCECONFIGURATIONINTEL)
 VKRESULT (QUEUE VKQUEUE) (CONFIGURATION VKPERFORMANCECONFIGURATIONINTEL))

(VULKAN-DEFCFUN
 ("vkGetPerformanceParameterINTEL" VKGETPERFORMANCEPARAMETERINTEL) VKRESULT
 (DEVICE VKDEVICE) (PARAMETER VKPERFORMANCEPARAMETERTYPEINTEL)
 (PVALUE :POINTER))

(VULKAN-DEFCFUN ("vkSetLocalDimmingAMD" VKSETLOCALDIMMINGAMD) :VOID
 (DEVICE VKDEVICE) (SWAPCHAIN VKSWAPCHAINKHR) (LOCALDIMMINGENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkGetBufferDeviceAddressEXT" VKGETBUFFERDEVICEADDRESSEXT)
 VKDEVICEADDRESS (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceToolPropertiesEXT" VKGETPHYSICALDEVICETOOLPROPERTIESEXT)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PTOOLCOUNT :POINTER)
 (PTOOLPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceCooperativeMatrixPropertiesNV"
  VKGETPHYSICALDEVICECOOPERATIVEMATRIXPROPERTIESNV)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PPROPERTYCOUNT :POINTER)
 (PPROPERTIES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV"
  VKGETPHYSICALDEVICESUPPORTEDFRAMEBUFFERMIXEDSAMPLESCOMBINATIONSNV)
 VKRESULT (PHYSICALDEVICE VKPHYSICALDEVICE) (PCOMBINATIONCOUNT :POINTER)
 (PCOMBINATIONS :POINTER))

(VULKAN-DEFCFUN ("vkCreateHeadlessSurfaceEXT" VKCREATEHEADLESSSURFACEEXT)
 VKRESULT (INSTANCE VKINSTANCE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PSURFACE :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetLineStippleEXT" VKCMDSETLINESTIPPLEEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (LINESTIPPLEFACTOR :UINT32)
 (LINESTIPPLEPATTERN :UINT16))

(VULKAN-DEFCFUN ("vkResetQueryPoolEXT" VKRESETQUERYPOOLEXT) :VOID
 (DEVICE VKDEVICE) (QUERYPOOL VKQUERYPOOL) (FIRSTQUERY :UINT32)
 (QUERYCOUNT :UINT32))

(VULKAN-DEFCFUN ("vkCmdSetCullModeEXT" VKCMDSETCULLMODEEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (CULLMODE VKCULLMODEFLAGS))

(VULKAN-DEFCFUN ("vkCmdSetFrontFaceEXT" VKCMDSETFRONTFACEEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FRONTFACE VKFRONTFACE))

(VULKAN-DEFCFUN ("vkCmdSetPrimitiveTopologyEXT" VKCMDSETPRIMITIVETOPOLOGYEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (PRIMITIVETOPOLOGY VKPRIMITIVETOPOLOGY))

(VULKAN-DEFCFUN ("vkCmdSetViewportWithCountEXT" VKCMDSETVIEWPORTWITHCOUNTEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (VIEWPORTCOUNT :UINT32)
 (PVIEWPORTS :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetScissorWithCountEXT" VKCMDSETSCISSORWITHCOUNTEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (SCISSORCOUNT :UINT32)
 (PSCISSORS :POINTER))

(VULKAN-DEFCFUN ("vkCmdBindVertexBuffers2EXT" VKCMDBINDVERTEXBUFFERS2EXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FIRSTBINDING :UINT32) (BINDINGCOUNT :UINT32)
 (PBUFFERS :POINTER) (POFFSETS :POINTER) (PSIZES :POINTER) (PSTRIDES :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetDepthTestEnableEXT" VKCMDSETDEPTHTESTENABLEEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHTESTENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetDepthWriteEnableEXT" VKCMDSETDEPTHWRITEENABLEEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHWRITEENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetDepthCompareOpEXT" VKCMDSETDEPTHCOMPAREOPEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHCOMPAREOP VKCOMPAREOP))

(VULKAN-DEFCFUN
 ("vkCmdSetDepthBoundsTestEnableEXT" VKCMDSETDEPTHBOUNDSTESTENABLEEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHBOUNDSTESTENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetStencilTestEnableEXT" VKCMDSETSTENCILTESTENABLEEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (STENCILTESTENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetStencilOpEXT" VKCMDSETSTENCILOPEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (FACEMASK VKSTENCILFACEFLAGS)
 (FAILOP VKSTENCILOP) (PASSOP VKSTENCILOP) (DEPTHFAILOP VKSTENCILOP)
 (COMPAREOP VKCOMPAREOP))

(VULKAN-DEFCFUN
 ("vkGetGeneratedCommandsMemoryRequirementsNV"
  VKGETGENERATEDCOMMANDSMEMORYREQUIREMENTSNV)
 :VOID (DEVICE VKDEVICE) (PINFO :POINTER) (PMEMORYREQUIREMENTS :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdPreprocessGeneratedCommandsNV" VKCMDPREPROCESSGENERATEDCOMMANDSNV)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (PGENERATEDCOMMANDSINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdExecuteGeneratedCommandsNV" VKCMDEXECUTEGENERATEDCOMMANDSNV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (ISPREPROCESSED VKBOOL32)
 (PGENERATEDCOMMANDSINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdBindPipelineShaderGroupNV" VKCMDBINDPIPELINESHADERGROUPNV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PIPELINEBINDPOINT VKPIPELINEBINDPOINT)
 (PIPELINE VKPIPELINE) (GROUPINDEX :UINT32))

(VULKAN-DEFCFUN
 ("vkCreateIndirectCommandsLayoutNV" VKCREATEINDIRECTCOMMANDSLAYOUTNV) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PINDIRECTCOMMANDSLAYOUT :POINTER))

(VULKAN-DEFCFUN
 ("vkDestroyIndirectCommandsLayoutNV" VKDESTROYINDIRECTCOMMANDSLAYOUTNV) :VOID
 (DEVICE VKDEVICE) (INDIRECTCOMMANDSLAYOUT VKINDIRECTCOMMANDSLAYOUTNV)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkAcquireDrmDisplayEXT" VKACQUIREDRMDISPLAYEXT) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (DRMFD :INT32) (DISPLAY VKDISPLAYKHR))

(VULKAN-DEFCFUN ("vkGetDrmDisplayEXT" VKGETDRMDISPLAYEXT) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (DRMFD :INT32) (CONNECTORID :UINT32)
 (DISPLAY :POINTER))

(VULKAN-DEFCFUN ("vkCreatePrivateDataSlotEXT" VKCREATEPRIVATEDATASLOTEXT)
 VKRESULT (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PPRIVATEDATASLOT :POINTER))

(VULKAN-DEFCFUN ("vkDestroyPrivateDataSlotEXT" VKDESTROYPRIVATEDATASLOTEXT)
 :VOID (DEVICE VKDEVICE) (PRIVATEDATASLOT VKPRIVATEDATASLOT)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN ("vkSetPrivateDataEXT" VKSETPRIVATEDATAEXT) VKRESULT
 (DEVICE VKDEVICE) (OBJECTTYPE VKOBJECTTYPE) (OBJECTHANDLE :UINT64)
 (PRIVATEDATASLOT VKPRIVATEDATASLOT) (DATA :UINT64))

(VULKAN-DEFCFUN ("vkGetPrivateDataEXT" VKGETPRIVATEDATAEXT) :VOID
 (DEVICE VKDEVICE) (OBJECTTYPE VKOBJECTTYPE) (OBJECTHANDLE :UINT64)
 (PRIVATEDATASLOT VKPRIVATEDATASLOT) (PDATA :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdSetFragmentShadingRateEnumNV" VKCMDSETFRAGMENTSHADINGRATEENUMNV) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (SHADINGRATE VKFRAGMENTSHADINGRATENV)
 (COMBINEROPS VKFRAGMENTSHADINGRATECOMBINEROPKHR))

(VULKAN-DEFCFUN
 ("vkGetImageSubresourceLayout2EXT" VKGETIMAGESUBRESOURCELAYOUT2EXT) :VOID
 (DEVICE VKDEVICE) (IMAGE VKIMAGE) (PSUBRESOURCE :POINTER) (PLAYOUT :POINTER))

(VULKAN-DEFCFUN ("vkAcquireWinrtDisplayNV" VKACQUIREWINRTDISPLAYNV) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (DISPLAY VKDISPLAYKHR))

(VULKAN-DEFCFUN ("vkGetWinrtDisplayNV" VKGETWINRTDISPLAYNV) VKRESULT
 (PHYSICALDEVICE VKPHYSICALDEVICE) (DEVICERELATIVEID :UINT32)
 (PDISPLAY :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetVertexInputEXT" VKCMDSETVERTEXINPUTEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (VERTEXBINDINGDESCRIPTIONCOUNT :UINT32)
 (PVERTEXBINDINGDESCRIPTIONS :POINTER)
 (VERTEXATTRIBUTEDESCRIPTIONCOUNT :UINT32)
 (PVERTEXATTRIBUTEDESCRIPTIONS :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI"
  VKGETDEVICESUBPASSSHADINGMAXWORKGROUPSIZEHUAWEI)
 VKRESULT (DEVICE VKDEVICE) (RENDERPASS VKRENDERPASS)
 (PMAXWORKGROUPSIZE :POINTER))

(VULKAN-DEFCFUN ("vkCmdSubpassShadingHUAWEI" VKCMDSUBPASSSHADINGHUAWEI) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER))

(VULKAN-DEFCFUN ("vkCmdBindInvocationMaskHUAWEI" VKCMDBINDINVOCATIONMASKHUAWEI)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (IMAGEVIEW VKIMAGEVIEW)
 (IMAGELAYOUT VKIMAGELAYOUT))

(VULKAN-DEFCFUN ("vkGetMemoryRemoteAddressNV" VKGETMEMORYREMOTEADDRESSNV)
 VKRESULT (DEVICE VKDEVICE) (PMEMORYGETREMOTEADDRESSINFO :POINTER)
 (PADDRESS :POINTER))

(VULKAN-DEFCFUN ("vkGetPipelinePropertiesEXT" VKGETPIPELINEPROPERTIESEXT)
 VKRESULT (DEVICE VKDEVICE) (PPIPELINEINFO :POINTER)
 (PPIPELINEPROPERTIES :POINTER))

(VULKAN-DEFCFUN ("vkCmdSetPatchControlPointsEXT" VKCMDSETPATCHCONTROLPOINTSEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (PATCHCONTROLPOINTS :UINT32))

(VULKAN-DEFCFUN
 ("vkCmdSetRasterizerDiscardEnableEXT" VKCMDSETRASTERIZERDISCARDENABLEEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (RASTERIZERDISCARDENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetDepthBiasEnableEXT" VKCMDSETDEPTHBIASENABLEEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DEPTHBIASENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetLogicOpEXT" VKCMDSETLOGICOPEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (LOGICOP VKLOGICOP))

(VULKAN-DEFCFUN
 ("vkCmdSetPrimitiveRestartEnableEXT" VKCMDSETPRIMITIVERESTARTENABLEEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRIMITIVERESTARTENABLE VKBOOL32))

(VULKAN-DEFCFUN ("vkCmdSetColorWriteEnableEXT" VKCMDSETCOLORWRITEENABLEEXT)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (ATTACHMENTCOUNT :UINT32)
 (PCOLORWRITEENABLES :POINTER))

(VULKAN-DEFCFUN ("vkCmdDrawMultiEXT" VKCMDDRAWMULTIEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DRAWCOUNT :UINT32) (PVERTEXINFO :POINTER)
 (INSTANCECOUNT :UINT32) (FIRSTINSTANCE :UINT32) (STRIDE :UINT32))

(VULKAN-DEFCFUN ("vkCmdDrawMultiIndexedEXT" VKCMDDRAWMULTIINDEXEDEXT) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (DRAWCOUNT :UINT32) (PINDEXINFO :POINTER)
 (INSTANCECOUNT :UINT32) (FIRSTINSTANCE :UINT32) (STRIDE :UINT32)
 (PVERTEXOFFSET :POINTER))

(VULKAN-DEFCFUN ("vkSetDeviceMemoryPriorityEXT" VKSETDEVICEMEMORYPRIORITYEXT)
 :VOID (DEVICE VKDEVICE) (MEMORY VKDEVICEMEMORY) (PRIORITY :FLOAT))

(VULKAN-DEFCFUN
 ("vkGetDescriptorSetLayoutHostMappingInfoVALVE"
  VKGETDESCRIPTORSETLAYOUTHOSTMAPPINGINFOVALVE)
 :VOID (DEVICE VKDEVICE) (PBINDINGREFERENCE :POINTER) (PHOSTMAPPING :POINTER))

(VULKAN-DEFCFUN
 ("vkGetDescriptorSetHostMappingVALVE" VKGETDESCRIPTORSETHOSTMAPPINGVALVE)
 :VOID (DEVICE VKDEVICE) (DESCRIPTORSET VKDESCRIPTORSET) (PPDATA :POINTER))

(VULKAN-DEFCFUN
 ("vkCreateAccelerationStructureKHR" VKCREATEACCELERATIONSTRUCTUREKHR) VKRESULT
 (DEVICE VKDEVICE) (PCREATEINFO :POINTER) (PALLOCATOR :POINTER)
 (PACCELERATIONSTRUCTURE :POINTER))

(VULKAN-DEFCFUN
 ("vkDestroyAccelerationStructureKHR" VKDESTROYACCELERATIONSTRUCTUREKHR) :VOID
 (DEVICE VKDEVICE) (ACCELERATIONSTRUCTURE VKACCELERATIONSTRUCTUREKHR)
 (PALLOCATOR :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdBuildAccelerationStructuresKHR" VKCMDBUILDACCELERATIONSTRUCTURESKHR)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (INFOCOUNT :UINT32) (PINFOS :POINTER)
 (PPBUILDRANGEINFOS :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdBuildAccelerationStructuresIndirectKHR"
  VKCMDBUILDACCELERATIONSTRUCTURESINDIRECTKHR)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (INFOCOUNT :UINT32) (PINFOS :POINTER)
 (PINDIRECTDEVICEADDRESSES :POINTER) (PINDIRECTSTRIDES :POINTER)
 (PPMAXPRIMITIVECOUNTS :POINTER))

(VULKAN-DEFCFUN
 ("vkBuildAccelerationStructuresKHR" VKBUILDACCELERATIONSTRUCTURESKHR) VKRESULT
 (DEVICE VKDEVICE) (DEFERREDOPERATION VKDEFERREDOPERATIONKHR)
 (INFOCOUNT :UINT32) (PINFOS :POINTER) (PPBUILDRANGEINFOS :POINTER))

(VULKAN-DEFCFUN
 ("vkCopyAccelerationStructureKHR" VKCOPYACCELERATIONSTRUCTUREKHR) VKRESULT
 (DEVICE VKDEVICE) (DEFERREDOPERATION VKDEFERREDOPERATIONKHR) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCopyAccelerationStructureToMemoryKHR"
  VKCOPYACCELERATIONSTRUCTURETOMEMORYKHR)
 VKRESULT (DEVICE VKDEVICE) (DEFERREDOPERATION VKDEFERREDOPERATIONKHR)
 (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCopyMemoryToAccelerationStructureKHR"
  VKCOPYMEMORYTOACCELERATIONSTRUCTUREKHR)
 VKRESULT (DEVICE VKDEVICE) (DEFERREDOPERATION VKDEFERREDOPERATIONKHR)
 (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkWriteAccelerationStructuresPropertiesKHR"
  VKWRITEACCELERATIONSTRUCTURESPROPERTIESKHR)
 VKRESULT (DEVICE VKDEVICE) (ACCELERATIONSTRUCTURECOUNT :UINT32)
 (PACCELERATIONSTRUCTURES :POINTER) (QUERYTYPE VKQUERYTYPE) (DATASIZE :SIZE)
 (PDATA :POINTER) (STRIDE :SIZE))

(VULKAN-DEFCFUN
 ("vkCmdCopyAccelerationStructureKHR" VKCMDCOPYACCELERATIONSTRUCTUREKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdCopyAccelerationStructureToMemoryKHR"
  VKCMDCOPYACCELERATIONSTRUCTURETOMEMORYKHR)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdCopyMemoryToAccelerationStructureKHR"
  VKCMDCOPYMEMORYTOACCELERATIONSTRUCTUREKHR)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkGetAccelerationStructureDeviceAddressKHR"
  VKGETACCELERATIONSTRUCTUREDEVICEADDRESSKHR)
 VKDEVICEADDRESS (DEVICE VKDEVICE) (PINFO :POINTER))

(VULKAN-DEFCFUN
 ("vkCmdWriteAccelerationStructuresPropertiesKHR"
  VKCMDWRITEACCELERATIONSTRUCTURESPROPERTIESKHR)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (ACCELERATIONSTRUCTURECOUNT :UINT32)
 (PACCELERATIONSTRUCTURES :POINTER) (QUERYTYPE VKQUERYTYPE)
 (QUERYPOOL VKQUERYPOOL) (FIRSTQUERY :UINT32))

(VULKAN-DEFCFUN
 ("vkGetDeviceAccelerationStructureCompatibilityKHR"
  VKGETDEVICEACCELERATIONSTRUCTURECOMPATIBILITYKHR)
 :VOID (DEVICE VKDEVICE) (PVERSIONINFO :POINTER) (PCOMPATIBILITY :POINTER))

(VULKAN-DEFCFUN
 ("vkGetAccelerationStructureBuildSizesKHR"
  VKGETACCELERATIONSTRUCTUREBUILDSIZESKHR)
 :VOID (DEVICE VKDEVICE) (BUILDTYPE VKACCELERATIONSTRUCTUREBUILDTYPEKHR)
 (PBUILDINFO :POINTER) (PMAXPRIMITIVECOUNTS :POINTER) (PSIZEINFO :POINTER))

(VULKAN-DEFCFUN ("vkCmdTraceRaysKHR" VKCMDTRACERAYSKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRAYGENSHADERBINDINGTABLE :POINTER)
 (PMISSSHADERBINDINGTABLE :POINTER) (PHITSHADERBINDINGTABLE :POINTER)
 (PCALLABLESHADERBINDINGTABLE :POINTER) (WIDTH :UINT32) (HEIGHT :UINT32)
 (DEPTH :UINT32))

(VULKAN-DEFCFUN
 ("vkCreateRayTracingPipelinesKHR" VKCREATERAYTRACINGPIPELINESKHR) VKRESULT
 (DEVICE VKDEVICE) (DEFERREDOPERATION VKDEFERREDOPERATIONKHR)
 (PIPELINECACHE VKPIPELINECACHE) (CREATEINFOCOUNT :UINT32)
 (PCREATEINFOS :POINTER) (PALLOCATOR :POINTER) (PPIPELINES :POINTER))

(VULKAN-DEFCFUN
 ("vkGetRayTracingCaptureReplayShaderGroupHandlesKHR"
  VKGETRAYTRACINGCAPTUREREPLAYSHADERGROUPHANDLESKHR)
 VKRESULT (DEVICE VKDEVICE) (PIPELINE VKPIPELINE) (FIRSTGROUP :UINT32)
 (GROUPCOUNT :UINT32) (DATASIZE :SIZE) (PDATA :POINTER))

(VULKAN-DEFCFUN ("vkCmdTraceRaysIndirectKHR" VKCMDTRACERAYSINDIRECTKHR) :VOID
 (COMMANDBUFFER VKCOMMANDBUFFER) (PRAYGENSHADERBINDINGTABLE :POINTER)
 (PMISSSHADERBINDINGTABLE :POINTER) (PHITSHADERBINDINGTABLE :POINTER)
 (PCALLABLESHADERBINDINGTABLE :POINTER) (INDIRECTDEVICEADDRESS VKDEVICEADDRESS))

(VULKAN-DEFCFUN
 ("vkGetRayTracingShaderGroupStackSizeKHR"
  VKGETRAYTRACINGSHADERGROUPSTACKSIZEKHR)
 VKDEVICESIZE (DEVICE VKDEVICE) (PIPELINE VKPIPELINE) (GROUP :UINT32)
 (GROUPSHADER VKSHADERGROUPSHADERKHR))

(VULKAN-DEFCFUN
 ("vkCmdSetRayTracingPipelineStackSizeKHR"
  VKCMDSETRAYTRACINGPIPELINESTACKSIZEKHR)
 :VOID (COMMANDBUFFER VKCOMMANDBUFFER) (PIPELINESTACKSIZE :UINT32))