
(in-package :cvk)

(defmacro create-pointer (slot slot-arg)
  `(setf ,slot (or ,slot-arg (cffi-sys:null-pointer))))

(defmacro get-pointer (slot)
  `(if (cffi-sys:null-pointer-p ,slot)
       nil
       ,slot))

(defmacro set-pointer (slot new-value)
  `(setf ,slot (or ,new-value (cffi-sys:null-pointer))))

(defmacro create-string (slot slot-arg &key (dynamic nil))
  (if dynamic
      `(setf ,slot
             (if ,slot-arg
		 (cffi:foreign-string-alloc ,slot-arg)
		 (cffi-sys:null-pointer)))
      (let ((str-sym (gensym)))
	`(cffi:with-foreign-string (,str-sym ,slot-arg)
	   (mcffi:copy ,slot ,str-sym :char (1+ (length ,slot-arg)))))))

(defmacro destroy-string (slot)
  `(when (not (cffi-sys:null-pointer-p ,slot))
     (cffi:foreign-string-free ,slot)))

(defmacro get-string (slot)
  `(cffi:foreign-string-to-lisp ,slot))

(defmacro set-string (slot new-value &key (dynamic nil))
  `(progn
     ,(when dynamic
	`(destroy-string ,slot))
     (create-string ,slot ,new-value)))

(defmacro create-array (type slot slot-arg &key (dynamic nil) (pointers nil))
  `(progn
    ,@(when dynamic
        `((setf ,slot
                  (if ,slot-arg
                      (cffi:foreign-alloc ',type :count (length ,slot-arg))
                      (cffi-sys:null-pointer)))))
    ,(let ((i (gensym))
	   (elem (gensym)))
       `(iter
          (for ,i from 0 below (length ,slot-arg))
	  (for ,elem in ,slot-arg)
          ,(if pointers
               `(more-cffi:copy (cffi:mem-aptr ,slot ',type ,i) ,elem
                                ',type)
               `(setf (cffi:mem-aref ,slot ',type ,i) ,elem))))))

(defmacro destroy-array (slot)
  `(when (not (cffi-sys:null-pointer-p ,slot)) (cffi-sys:foreign-free ,slot)))

(defmacro get-array (type slot index count &key (pointers nil))
  `(if (cffi-sys:null-pointer-p ,slot)
       nil
       (if ,index
           ,(if pointers
                `(cffi:mem-aptr ,slot ',type ,index)
                `(cffi:mem-aref ,slot ',type ,index))
           ,(let ((i (gensym)))
              `(iter
                 (for ,i from 0 below ,count)
                 (collect
                  ,(if pointers
                       `(cffi:mem-aptr ,slot ',type ,i)
                       `(cffi:mem-aref ,slot ',type ,i))))))))

(defmacro set-array
          (type slot new-value index &key (dynamic nil) (pointers nil))
  `(if ,index
       ,(if pointers
            `(more-cffi:copy (cffi:mem-aptr ,slot ',type ,index) ,new-value
                             ',type)
            `(setf (cffi:mem-aref ,slot ',type ,index) ,new-value))
       (progn
        (destroy-array ,slot)
        (create-array ,type ,slot ,new-value :dynamic ,dynamic :pointers
         ,pointers))))

(defmacro create-array-strings (slot slot-arg &key (dynamic nil))
  `(progn
    ,@(when dynamic
        `((setf ,slot
                  (if ,slot-arg
                      (cffi:foreign-alloc :pointer :count (length ,slot-arg))
                      (cffi-sys:null-pointer)))))
    ,(let ((i (gensym))
	   (elem (gensym)))
       `(iter
          (for ,i from 0 below (length ,slot-arg))
	  (for ,elem in ,slot-arg)
          (setf (cffi:mem-aref ,slot :pointer ,i)
                (cffi:foreign-string-alloc ,elem))))))

(defmacro destroy-array-strings (slot count &key dynamic)
  `(when (not (cffi-sys:null-pointer-p ,slot))
     ,(let ((i (gensym)))
        `(iter
           (for ,i from 0 below ,count)
           (cffi:foreign-string-free (cffi:mem-aref ,slot :pointer ,i))))
     ,(when dynamic `(cffi-sys:foreign-free ,slot))))

(defmacro get-array-strings (slot index count)
  `(if (cffi-sys:null-pointer-p ,slot)
       nil
       (if ,index
           (cffi:foreign-string-to-lisp (cffi:mem-aref ,slot :pointer ,index))
           ,(let ((i (gensym)))
              `(iter
                 (for ,i from 0 below ,count)
                 (collect
                  (cffi:foreign-string-to-lisp
                   (cffi:mem-aref ,slot :pointer ,i))))))))

(defmacro set-array-strings (slot new-value index count &key (dynamic nil))
  `(if ,index
       (progn
        (cffi:foreign-string-free (cffi:mem-aref ,slot :pointer ,index))
        (setf (cffi:mem-aref ,slot :pointer ,index) ,new-value))
       (progn
        (destroy-array-strings ,slot ,count :dynamic ,dynamic)
        (create-array-strings ,slot ,new-value :dynamic ,dynamic))))


(mcffi:with-doc-file (doc-file (asdf:system-relative-pathname "common-vulkan" "docs/api/structs.md"))


  (more-cffi:def-foreign-struct doc-file "VkExtent2D" (extent-2d)
      (:default-create :default-get :default-set)
    (width :name width :type uint32)
    (height :name height :type uint32))

  
  (more-cffi:def-foreign-struct doc-file "VkOffset2D" (offset-2d)
      (:default-create :default-get :default-set)
    (x :name x :type int32)
    (y :name y :type int32))


  (more-cffi:def-foreign-struct doc-file "VkRect2D" (rect-2d)
      (:default-create :default-get :default-set)
    (offset :pointer t :name offset :type "VkOffset2D"
	    :create ((offset-arg)
		     (more-cffi:copy offset offset-arg '(:struct vkoffset2d)))
	    :set ((offset-arg)
		  (more-cffi:copy offset offset-arg '(:struct vkoffset2d))))
    (extent :pointer t :name extent :type "VkExtent2D"
	    :create ((extent-arg)
		     (more-cffi:copy extent extent-arg '(:struct vkextent2d)))
	    :set ((extent-arg)
		  (more-cffi:copy extent extent-arg '(:struct vkextent2d)))))


  (more-cffi:def-foreign-struct doc-file "VkComponentMapping" (component-mapping)
      (:default-create :default-get :default-set)
    (r :name r :type "VkComponentSwizzle")
    (g :name g :type "VkComponentSwizzle")
    (b :name b :type "VkComponentSwizzle")
    (a :name a :type "VkComponentSwizzle"))


  (more-cffi:def-foreign-struct doc-file "VkImageSubresourceRange" (image-subresource-range)
      (:default-create :default-get :default-set)
    (aspectmask :name "aspectMask" :type "VkImageAspectFlags")
    (basemiplevel :name "baseMipLevel" :type uint32)
    (levelcount :name "levelCount" :type uint32)
    (basearraylayer :name "baseArrayLayer" :type uint32)
    (layercount :name "layerCount" :type uint32))
  

  (more-cffi:def-foreign-struct doc-file "VkSpecializationMapEntry" (specialization-map-entry)
      (:default-create :default-get :default-set)
    (antid :name "antID" :type uint32)
    (offset :name offset :type uint32)
    (size :name size :type size))


  (more-cffi:def-foreign-struct doc-file "VkSpecializationInfo" (specialization-info)
      (:default-create :default-get :default-set)
    (mapentrycount :name "mapEntryCount" :type uint32)
    (pmapentries :name "pMapEntries" :type "VkSpecializationMapEntry" :init-form nil
		 :create ((pmapentries-arg)
			  (create-array (:struct vkspecializationmapentry) pmapentries pmapentries-arg :dynamic t :pointers t))
		 :destroy (destroy-array pmapentries)
		 :get ((&optional pmapentries-index)
		       (get-array (:struct vkspecializationmapentry) pmapentries pmapentries-index mapentrycount :pointers t))
		 :set ((pmapentries-arg &optional pmapentries-index)
		       (set-array (:struct vkspecializationmapentry) pmapentries pmapentries-arg pmapentries-index :dynamic t :pointers t)))
    (datasize :name "dataSize" :type size)
    (pdata :name "pData" :type void :init-form nil
	   :create ((pdata-arg)
		    (create-pointer pdata pdata-arg))
	   :get (nil (get-pointer pdata))
	   :set ((pdata-arg)
		 (set-pointer pdata pdata-arg))))


  (more-cffi:def-foreign-struct doc-file "VkViewport" (viewport)
      (:default-create :default-get :default-set)
    (x :name x :type float)
    (y :name y :type float)
    (width :name width :type float)
    (height :name height :type float)
    (mindepth :name "minDepth" :type float)
    (maxdepth :name "maxDepth" :type float))


  (more-cffi:def-foreign-struct doc-file "VkPushConstantRange" (push-constant-range)
      (:default-create :default-get :default-set)
    (stageflags :name "stageFlags" :type "VkShaderStageFlags")
    (offset :name offset :type uint32)
    (size :name size :type uint32))


  (more-cffi:def-foreign-struct doc-file "VkAttachmentDescription" (attachment-description)
      (:default-create :default-get :default-set)
    (flags :name flags :type "VkAttachmentDescriptionFlags")
    (format :name format :type "VkFormat")
    (samples :name samples :type "VkSampleCountFlagBits")
    (loadop :name "loadOp" :type "VkAttachmentLoadOp")
    (storeop :name "storeOp" :type "VkAttachmentStoreOp")
    (stencilloadop :name "stencilLoadOp" :type "VkAttachmentLoadOp")
    (stencilstoreop :name "stencilStoreOp" :type "VkAttachmentStoreOp")
    (initiallayout :name "initialLayout" :type "VkImageLayout")
    (finallayout :name "finalLayout" :type "VkImageLayout"))
  

  (more-cffi:def-foreign-struct doc-file "VkAttachmentReference" (attachment-reference)
      (:default-create :default-get :default-set)
    (attachment :name attachment :type uint32)
    (layout :name layout :type "VkImageLayout"))


  (more-cffi:def-foreign-struct doc-file "VkSubpassDescription" (subpass-description)
      (:default-create :default-get :default-set)
    (flags :name flags :type "VkSubpassDescriptionFlags")
    (pipelinebindpoint :name "pipelineBindPoint" :type "VkPipelineBindPoint")
    (inputattachmentcount :name "inputAttachmentCount" :type uint32)
    (pinputattachments :name "pInputAttachments" :type (list "VkAttachmentReference") :init-form nil
		       :create ((pinputattachments-arg)
				(create-array (:struct vkattachmentreference) pinputattachments pinputattachments-arg :dynamic t :pointers t))
		       :destroy (destroy-array pinputattachments)
		       :get ((&optional pinputattachments-index)
			     (get-array (:struct vkattachmentreference) pinputattachments pinputattachments-index inputattachmentcount :pointers t))
		       :set ((pinputattachments-arg &optional pinputattachments-index)
			     (set-array (:struct vkattachmentreference) pinputattachments pinputattachments-arg pinputattachments-index :dynamic t :pointers t)))
    (colorattachmentcount :name "colorAttachmentCount" :type uint32)
    (pcolorattachments :name "pColorAttachments" :type (list "VkAttachmentReference") :init-form nil
		       :create ((pcolorattachments-arg)
				(create-array (:struct vkattachmentreference) pcolorattachments pcolorattachments-arg :dynamic t :pointers t))
		       :destroy (destroy-array pcolorattachments)
		       :get ((&optional pcolorattachments-index)
			     (get-array (:struct vkattachmentreference) pcolorattachments pcolorattachments-index colorattachmentcount :pointers t))
		       :set ((pcolorattachments-arg &optional pcolorattachments-index)
			     (set-array (:struct vkattachmentreference) pcolorattachments pcolorattachments-arg pcolorattachments-index :dynamic t :pointers t)))
    (presolveattachments :name "pResolveAttachments" :type "VkAttachmentReference" :init-form nil
			 :create ((presolveattachments-arg)
				(create-array (:struct vkattachmentreference) presolveattachments presolveattachments-arg :dynamic t :pointers t))
		       :destroy (destroy-array presolveattachments)
		       :get ((&optional presolveattachments-index)
			     (get-array (:struct vkattachmentreference) presolveattachments presolveattachments-index colorattachmentcount :pointers t))
		       :set ((presolveattachments-arg &optional presolveattachments-index)
			     (set-array (:struct vkattachmentreference) presolveattachments presolveattachments-arg presolveattachments-index :dynamic t :pointers t)))
    (pdepthstencilattachment :name "pDepthStencilAttachment" :type "VkAttachmentReference" :init-form nil
			     :create ((pdepthstencilattachment-arg)
				      (create-pointer pdepthstencilattachment pdepthstencilattachment-arg))
			     :get (nil (get-pointer pdepthstencilattachment))
			     :set ((pdepthstencilattachment-arg)
				   (set-pointer pdepthstencilattachment pdepthstencilattachment-arg)))
    (preserveattachmentcount :name "preserveAttachmentCount" :type uint32)
    (ppreserveattachments :name "pPreserveAttachments" :type uint32 :init-form nil
			  :create ((ppreserveattachments-arg)
				   (create-array :uint32 ppreserveattachments ppreserveattachments-arg :dynamic t :pointers nil))
			  :destroy (destroy-array ppreserveattachments)
			  :get ((&optional ppreserveattachments-index)
				(get-array :uint32 ppreserveattachments ppreserveattachments-index preserveattachmentcount :pointers nil))
			  :set ((ppreserveattachments-arg &optional ppreserveattachments-index)
				(set-array :uint32 ppreserveattachments ppreserveattachments-arg ppreserveattachments-index :dynamic t :pointers nil))))


  (more-cffi:def-foreign-struct doc-file "VkSubpassDependency" (subpass-dependency)
      (:default-create :default-get :default-set)
    (srcsubpass :name "srcSubpass" :type uint32)
    (dstsubpass :name "dstSubpass" :type uint32)
    (srcstagemask :name "srcStageMask" :type "VkPipelineStageFlags")
    (dststagemask :name "dstStageMask" :type "VkPipelineStageFlags")
    (srcaccessmask :name "srcAccessMask" :type "VkAccessFlags")
    (dstaccessmask :name "dstAccessMask" :type "VkAccessFlags")
    (dependencyflags :name "dependencyFlags" :type "VkDependencyFlags"))

  
  (mcffi:def-foreign-struct doc-file "VkApplicationInfo" application-info
      (:default-create :default-get :default-set)
    (sType              :name "sType" :type "VkStructureType" :init-form VK_STRUCTURE_TYPE_APPLICATION_INFO)
    (pNext              :name "pNext" :type "vulkan object" :init-form nil
	                :create ((pNext-arg)
				 (create-pointer pNext pNext-arg))
			:get (() (get-pointer pNext))
			:set ((pNext-arg)
			      (set-pointer pNext pNext-arg)))
    (pApplicationName   :name "pApplicationName" :type string :init-form nil
		        :create ((pApplicationName-arg)
				 (create-string pApplicationName pApplicationName-arg :dynamic t))
		        :destroy (destroy-string pApplicationName)
		        :get (() (get-string pApplicationName))
		        :set ((pApplicationName-arg)
			      (set-string pApplicationName pApplicationName-arg :dynamic t)))
    (applicationVersion :name "applicationVersion" :type uint32 :init-form 0)
    (pEngineName        :name "pEngineName" :type string :init-form nil
		        :create ((pEngineName-arg)
				 (create-string pEngineName pEngineName-arg :dynamic t))
		        :destroy (destroy-string pEngineName)
		        :get (() (get-string pEngineName))
		        :set ((pEngineName-arg)
			      (set-string pEngineName pEngineName-arg :dynamic t)))
    (engineVersion      :name "engineVersion" :type uint32 :init-form 0)
    (apiVersion         :name "apiVersion" :type uint32 :init-form 0))


  (mcffi:def-foreign-struct doc-file "VkInstanceCreateInfo" instance-create-info 
      (:default-create :default-get :default-set)
    (sType                   :name "sType" :type "VkStructureType"
			     :init-form VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO)
    (pNext                   :name "pNext" :type "vulkan object" :init-form nil
	                     :create ((pNext-arg)
				      (create-pointer pNext pNext-arg))
			     :get (() (get-pointer pNext))
			     :set ((pNext-arg)
				   (set-pointer pNext pNext-arg)))
    (flags                   :type "VkInstanceCreateFlags")
    (pApplicationInfo        :name "pApplicationInfo" :type "VkApplicationInfo" :init-form nil
		             :create ((pApplicationInfo-arg)
				      (create-pointer pApplicationInfo pApplicationInfo-arg))
			     :get (() (get-pointer pApplicationInfo))
			     :set ((pApplicationInfo-arg)
				   (set-pointer pApplicationInfo pApplicationInfo-arg)))
    (enabledLayerCount       :name "enabledLayerCount" :type uint32)
    (ppEnabledLayerNames     :name "ppEnabledLayerNames" :type (list string) :init-form nil
			     :create ((ppEnabledLayerNames-arg)
				      (create-array-strings ppEnabledLayerNames ppEnabledLayerNames-arg :dynamic t))
			     :destroy (destroy-array-strings ppEnabledLayerNames enabledLayerCount :dynamic t)
			     :get ((&optional (index nil))
				   (get-array-strings ppEnabledLayerNames index enabledLayerCount))
			     :set ((ppEnabledLayerNames-arg &optional (index nil))
				   (set-array-strings ppEnabledLayerNames ppEnabledLayerNames-arg index enabledLayerCount :dynamic t)))
    (enabledExtensionCount   :name "enabledExtensionCount" :type uint32)
    (ppEnabledExtensionNames :name "ppEnabledExtensionNames" :type (list string) :init-form nil
			     :create ((ppEnabledExtensionNames-arg)
				      (create-array-strings ppEnabledExtensionNames ppEnabledExtensionNames-arg :dynamic t))
			     :destroy (destroy-array-strings ppEnabledExtensionNames enabledLayerCount :dynamic t)
			     :get ((&optional (index nil))
				   (get-array-strings ppEnabledExtensionNames index enabledExtensionCount))
			     :set ((ppEnabledExtensionNames-arg &optional (index nil))
				   (set-array-strings ppEnabledExtensionNames ppEnabledExtensionNames-arg index enabledExtensionCount :dynamic t))))


  (mcffi:def-foreign-struct doc-file "VkExtensionProperties" extension-properties 
      (:default-create :default-get :default-set)
    (extensionName :name "extensionName" :type string :init-form nil
		   :create ((extensionName-arg)
			    (create-string extensionName extensionName-arg :dynamic nil))
		   :get (() (get-string extensionName))
		   :set ((extensionName-arg)
			 (set-string extensionName extensionName-arg :dynamic nil)))
    (specVersion   :name "specVersion" :type uint32))


  (mcffi:def-foreign-struct doc-file "VkLayerProperties" layer-properties  
      (:default-create :default-get :default-set)
    (layerName             :name "layerName" :type string :init-form nil
	                   :create ((layerName-arg)
				    (create-string layerName layerName-arg :dynamic nil))
			   :get (() (get-string layerName))
			   :set ((layerName-arg)
				 (set-string layerName layerName-arg :dynamic nil)))
    (specVersion           :name "specVersion" :type uint32)
    (implementationVersion :name "implementationVersion" :type uint32)
    (description           :type string :init-form nil
		           :create ((description-arg)
				    (create-string description description-arg :dynamic nil))
			   :get (() (get-string description))
			   :set ((description-arg)
				 (set-string description description-arg :dynamic nil))))

  
  (more-cffi:def-foreign-struct doc-file "VkDebugUtilsMessengerCreateInfoEXT" (debug-utils-messenger-create-info-ext)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg) (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkDebugUtilsMessengerCreateFlagsEXT")
    (messageseverity :name "messageSeverity" :type "VkDebugUtilsMessageSeverityFlagsEXT")
    (messagetype :name "messageType" :type "VkDebugUtilsMessageTypeFlagsEXT")
    (pfnusercallback :name "pfnUserCallback" :type callback :init-form nil
		     :create ((pfnUserCallback-arg)
			      (setf pfnUserCallback (if pfnUserCallback-arg
							(if (symbolp pfnUserCallback-arg)
							    (cffi:get-callback pfnUserCallback-arg)
							    pfnUserCallback-arg)
							(cffi:null-pointer))))
		     :set ((new-value)			   
			   (if new-value
			       (if (symbolp new-value)
				   (setf pfnUserCallback (cffi:get-callback new-value))
				   (setf pfnUserCallback new-value))
			       (setf pfnUserCallback (cffi:null-pointer)))))
    (puserdata :name "pUserData" :type "lisp object" :init-form nil
	       :create ((pUserData-arg)
			(setf pUserData (if pUserData-arg
					    (prog2
						(setf (gethash *debug-utils-messenger-callback-next-address* *debug-utils-messenger-callback-user-data*) pUserData-arg)
						(cffi:make-pointer *debug-utils-messenger-callback-next-address*)
					      (setf *debug-utils-messenger-callback-next-address* (1+ *debug-utils-messenger-callback-next-address*)))
					    (cffi:null-pointer))))
	       :get (() (gethash (cffi:pointer-address pUserData) *debug-utils-messenger-callback-user-data*))
	       :set ((new-value)
		     (if (cffi:null-pointer-p pUserData)
			 (if new-value
			     (progn
			       (setf (gethash *debug-utils-messenger-callback-next-address* *debug-utils-messenger-callback-user-data*) new-value)
			       (setf pUserData (cffi:make-pointer *debug-utils-messenger-callback-next-address*))
			       (setf *debug-utils-messenger-callback-next-address* (1+ *debug-utils-messenger-callback-next-address*))))
			 (if new-value
			     (setf (gethash (cffi:pointer-address pUserData) *debug-utils-messenger-callback-user-data*) new-value)
			     (progn
			       (remhash (cffi:pointer-address pUserData) *debug-utils-messenger-callback-user-data*)
			       (setf pUserData (cffi:null-pointer))))))))


  (more-cffi:def-foreign-struct doc-file "VkDebugUtilsMessengerCallbackDataEXT" (debug-utils-messenger-callback-data-ext)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (() (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkDebugUtilsMessengerCallbackDataFlagsEXT")
    (pmessageidname :name "pMessageIdName" :type string :init-form nil
		    :create ((pmessageidname-arg)
			     (create-string pmessageidname pmessageidname-arg :dynamic t))
		    :destroy (destroy-string pmessageidname)
		    :get (nil (get-string pmessageidname))
		    :set ((pmessageidname-arg)
			  (set-string pmessageidname pmessageidname-arg :dynamic t)))
    (messageidnumber :name "messageIdNumber" :type int32)
    (pmessage :name "pMessage" :type string :init-form nil
	      :create ((pmessage-arg)
		       (create-string pmessage pmessage-arg :dynamic t))
	      :destroy (destroy-string pmessage)
	      :get (() (get-string pmessage))
	      :set ((pmessage-arg)
		    (set-string pmessage pmessage-arg :dynamic t)))
    (queuelabelcount :name "queueLabelCount" :type uint32)
    (pqueuelabels :name "pQueueLabels" :type (list "VkDebugUtilsLabelEXT") :init-form nil
		  :create ((pqueuelabels-arg)
			   (create-array (:struct vkdebugutilslabelext) pqueuelabels pqueuelabels-arg :dynamic t :pointers t))
		  :destroy (destroy-array pqueuelabels)
		  :get ((&optional pqueuelabels-index)
			(get-array (:struct vkdebugutilslabelext) pqueuelabels pqueuelabels-index queuelabelcount :pointers t))
		  :set ((pqueuelabels-arg &optional pqueuelabels-index)
			(set-array (:struct vkdebugutilslabelext) pqueuelabels pqueuelabels-arg pqueuelabels-index :dynamic t :pointers t)))
    (cmdbuflabelcount :name "cmdBufLabelCount" :type uint32)
    (pcmdbuflabels :name "pCmdBufLabels" :type (list "VkDebugUtilsLabelEXT") :init-form nil
		   :create ((pcmdbuflabels-arg)
			    (create-array (:struct vkdebugutilslabelext) pcmdbuflabels pcmdbuflabels-arg :dynamic t :pointers t))
		   :destroy (destroy-array pcmdbuflabels)
		   :get ((&optional pcmdbuflabels-index)
			 (get-array (:struct vkdebugutilslabelext) pcmdbuflabels pcmdbuflabels-index cmdbuflabelcount :pointers t))
		   :set ((pcmdbuflabels-arg &optional pcmdbuflabels-index)
			 (set-array (:struct vkdebugutilslabelext) pcmdbuflabels pcmdbuflabels-arg pcmdbuflabels-index :dynamic t :pointers t)))
    (objectcount :name "objectCount" :type uint32)
    (pobjects :name "pObjects" :type (list "VkDebugUtilsObjectNameInfoEXT") :init-form nil
	      :create ((pobjects-arg)
		       (create-array (:struct vkdebugutilsobjectnameinfoext) pobjects pobjects-arg :dynamic t :pointers t))
	      :destroy (destroy-array pobjects)
	      :get ((&optional pobjects-index)
		    (get-array (:struct vkdebugutilsobjectnameinfoext) pobjects pobjects-index objectcount :pointers t))
	      :set ((pobjects-arg &optional pobjects-index)
		    (set-array (:struct vkdebugutilsobjectnameinfoext) pobjects pobjects-arg pobjects-index :dynamic t :pointers t))))


  (more-cffi:def-foreign-struct doc-file "VkDebugUtilsLabelEXT" (debug-utils-label-ext)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (plabelname :name "pLabelName" :type string :init-form nil
		:create ((plabelname-arg)
			 (create-string plabelname plabelname-arg :dynamic t))
		:destroy (destroy-string plabelname)
		:get (nil (get-string plabelname))
		:set ((plabelname-arg) (set-string plabelname plabelname-arg :dynamic t)))
    (color :name color :type (list float) :init-form '(0.0 0.0 0.0 0.0)
	   :create ((color-arg)
		    (create-array :float color color-arg :dynamic nil :pointers nil))
	   :get ((&optional color-index)
		 (get-array :float color color-index 4 :pointers nil))
	   :set ((color-arg &optional color-index)
		 (set-array :float color color-arg color-index :dynamic nil :pointers nil))))


  (more-cffi:def-foreign-struct doc-file "VkDebugUtilsObjectNameInfoEXT" (debug-utils-object-name-info-ext)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (objecttype :name "objectType" :type "VkObjectType")
    (objecthandle :name "objectHandle" :type uint64)
    (pobjectname :name "pObjectName" :type string :init-form nil
		 :create ((pobjectname-arg)
			  (create-string pobjectname pobjectname-arg :dynamic t))
		 :destroy (destroy-string pobjectname)
		 :get (nil (get-string pobjectname))
		 :set ((pobjectname-arg)
		       (set-string pobjectname pobjectname-arg :dynamic t))))


  (more-cffi:def-foreign-struct doc-file "VkPhysicalDeviceProperties" (physical-device-properties)
      (:default-create :default-get :default-set)
    (apiversion :name "apiVersion" :type uint32)
    (driverversion :name "driverVersion" :type uint32)
    (vendorid :name "vendorID" :type uint32)
    (deviceid :name "deviceID" :type uint32)
    (devicetype :name "deviceType" :type "VkPhysicalDeviceType")
    (devicename :name "deviceName" :type string
		:create ((devicename-arg)
			 (create-string devicename devicename-arg :dynamic nil))
		:get (nil (get-string devicename))
		:set ((devicename-arg)
		      (set-string devicename devicename-arg :dynamic nil)))
    (pipelinecacheuuid :name "pipelineCacheUUID" :type (list uint8)
		       :create ((pipelinecacheuuid-arg)
				(create-array :uint8 pipelinecacheuuid pipelinecacheuuid-arg :dynamic nil :pointers nil))
		       :get ((&optional pipelinecacheuuid-index)
			     (get-array :uint8 pipelinecacheuuid pipelinecacheuuid-index VK_UUID_SIZE :pointers nil))
		       :set ((pipelinecacheuuid-arg &optional pipelinecacheuuid-index)
			     (set-array :uint8 pipelinecacheuuid pipelinecacheuuid-arg pipelinecacheuuid-index :dynamic nil :pointers nil)))
    (limits :pointer t :name limits :type "VkPhysicalDeviceLimits"
	    :create ((limits-arg)
		     (more-cffi:copy limits limits-arg '(:struct vkphysicaldevicelimits)))
	    :set ((limits-arg)
		  (more-cffi:copy limits limits-arg '(:struct vkphysicaldevicelimits))))
    (sparseproperties :pointer t :name "sparseProperties" :type "VkPhysicalDeviceSparseProperties"
		      :create ((sparseproperties-arg)
			       (more-cffi:copy sparseproperties sparseproperties-arg '(:struct vkphysicaldevicesparseproperties)))
		      :set ((sparseproperties-arg)
			    (more-cffi:copy sparseproperties sparseproperties-arg '(:struct vkphysicaldevicesparseproperties)))))


  (more-cffi:def-foreign-struct doc-file "VkPhysicalDeviceLimits" (physical-device-limits)
      (:default-create :default-get :default-set)
    (maximagedimension1d :name "maxImageDimension1D" :type uint32)
    (maximagedimension2d :name "maxImageDimension2D" :type uint32)
    (maximagedimension3d :name "maxImageDimension3D" :type uint32)
    (maximagedimensioncube :name "maxImageDimensionCube" :type uint32)
    (maximagearraylayers :name "maxImageArrayLayers" :type uint32)
    (maxtexelbufferelements :name "maxTexelBufferElements" :type uint32)
    (maxuniformbufferrange :name "maxUniformBufferRange" :type uint32)
    (maxstoragebufferrange :name "maxStorageBufferRange" :type uint32)
    (maxpushconstantssize :name "maxPushConstantsSize" :type uint32)
    (maxmemoryallocationcount :name "maxMemoryAllocationCount" :type uint32)
    (maxsamplerallocationcount :name "maxSamplerAllocationCount" :type uint32)
    (bufferimagegranularity :name "bufferImageGranularity" :type "VkDeviceSize")
    (sparseaddressspacesize :name "sparseAddressSpaceSize" :type "VkDeviceSize")
    (maxbounddescriptorsets :name "maxBoundDescriptorSets" :type uint32)
    (maxperstagedescriptorsamplers :name "maxPerStageDescriptorSamplers" :type uint32)
    (maxperstagedescriptoruniformbuffers :name "maxPerStageDescriptorUniformBuffers" :type uint32)
    (maxperstagedescriptorstoragebuffers :name "maxPerStageDescriptorStorageBuffers" :type uint32)
    (maxperstagedescriptorsampledimages :name "maxPerStageDescriptorSampledImages" :type uint32)
    (maxperstagedescriptorstorageimages :name "maxPerStageDescriptorStorageImages" :type uint32)
    (maxperstagedescriptorinputattachments :name "maxPerStageDescriptorInputAttachments" :type uint32)
    (maxperstageresources :name "maxPerStageResources" :type uint32)
    (maxdescriptorsetsamplers :name "maxDescriptorSetSamplers" :type uint32)
    (maxdescriptorsetuniformbuffers :name "maxDescriptorSetUniformBuffers" :type uint32)
    (maxdescriptorsetuniformbuffersdynamic :name "maxDescriptorSetUniformBuffersDynamic" :type uint32)
    (maxdescriptorsetstoragebuffers :name "maxDescriptorSetStorageBuffers" :type uint32)
    (maxdescriptorsetstoragebuffersdynamic :name "maxDescriptorSetStorageBuffersDynamic" :type uint32)
    (maxdescriptorsetsampledimages :name "maxDescriptorSetSampledImages" :type uint32)
    (maxdescriptorsetstorageimages :name "maxDescriptorSetStorageImages" :type uint32)
    (maxdescriptorsetinputattachments :name "maxDescriptorSetInputAttachments" :type uint32)
    (maxvertexinputattributes :name "maxVertexInputAttributes" :type uint32)
    (maxvertexinputbindings :name "maxVertexInputBindings" :type uint32)
    (maxvertexinputattributeoffset :name "maxVertexInputAttributeOffset" :type uint32)
    (maxvertexinputbindingstride :name "maxVertexInputBindingStride" :type uint32)
    (maxvertexoutputcomponents :name "maxVertexOutputComponents" :type uint32)
    (maxtessellationgenerationlevel :name "maxTessellationGenerationLevel" :type uint32)
    (maxtessellationpatchsize :name "maxTessellationPatchSize" :type uint32)
    (maxtessellationcontrolpervertexinputcomponents :name "maxTessellationControlPerVertexInputComponents" :type uint32)
    (maxtessellationcontrolpervertexoutputcomponents :name "maxTessellationControlPerVertexOutputComponents" :type uint32)
    (maxtessellationcontrolperpatchoutputcomponents :name "maxTessellationControlPerPatchOutputComponents" :type uint32)
    (maxtessellationcontroltotaloutputcomponents :name "maxTessellationControlTotalOutputComponents" :type uint32)
    (maxtessellationevaluationinputcomponents :name "maxTessellationEvaluationInputComponents" :type uint32)
    (maxtessellationevaluationoutputcomponents :name "maxTessellationEvaluationOutputComponents" :type uint32)
    (maxgeometryshaderinvocations :name "maxGeometryShaderInvocations" :type uint32)
    (maxgeometryinputcomponents :name "maxGeometryInputComponents" :type uint32)
    (maxgeometryoutputcomponents :name "maxGeometryOutputComponents" :type uint32)
    (maxgeometryoutputvertices :name "maxGeometryOutputVertices" :type uint32)
    (maxgeometrytotaloutputcomponents :name "maxGeometryTotalOutputComponents" :type uint32)
    (maxfragmentinputcomponents :name "maxFragmentInputComponents" :type uint32)
    (maxfragmentoutputattachments :name "maxFragmentOutputAttachments" :type uint32)
    (maxfragmentdualsrcattachments :name "maxFragmentDualSrcAttachments" :type uint32)
    (maxfragmentcombinedoutputresources :name "maxFragmentCombinedOutputResources" :type uint32)
    (maxcomputesharedmemorysize :name "maxComputeSharedMemorySize" :type uint32)
    (maxcomputeworkgroupcount :name "maxComputeWorkGroupCount" :type uint32
			      :create ((maxcomputeworkgroupcount-arg)
				       (create-array :uint32 maxcomputeworkgroupcount maxcomputeworkgroupcount-arg :dynamic nil :pointers nil))
			      :get ((&optional maxcomputeworkgroupcount-index)
				    (get-array :uint32 maxcomputeworkgroupcount maxcomputeworkgroupcount-index 3 :pointers nil))
			      :set ((maxcomputeworkgroupcount-arg &optional maxcomputeworkgroupcount-index)
				    (set-array :uint32 maxcomputeworkgroupcount maxcomputeworkgroupcount-arg maxcomputeworkgroupcount-index :dynamic nil :pointers nil)))
    (maxcomputeworkgroupinvocations :name "maxComputeWorkGroupInvocations" :type uint32)
    (maxcomputeworkgroupsize :name "maxComputeWorkGroupSize" :type uint32
			     :create ((maxcomputeworkgroupsize-arg)
				      (create-array :uint32 maxcomputeworkgroupsize maxcomputeworkgroupsize-arg :dynamic nil :pointers nil))
			     :get ((&optional maxcomputeworkgroupsize-index)
				   (get-array :uint32 maxcomputeworkgroupsize maxcomputeworkgroupsize-index 3 :pointers nil))
			     :set ((maxcomputeworkgroupsize-arg &optional maxcomputeworkgroupsize-index)
				   (set-array :uint32 maxcomputeworkgroupsize maxcomputeworkgroupsize-arg maxcomputeworkgroupsize-index :dynamic nil :pointers nil)))
    (subpixelprecisionbits :name "subPixelPrecisionBits" :type uint32)
    (subtexelprecisionbits :name "subTexelPrecisionBits" :type uint32)
    (mipmapprecisionbits :name "mipmapPrecisionBits" :type uint32)
    (maxdrawindexedindexvalue :name "maxDrawIndexedIndexValue" :type uint32)
    (maxdrawindirectcount :name "maxDrawIndirectCount" :type uint32)
    (maxsamplerlodbias :name "maxSamplerLodBias" :type float)
    (maxsampleranisotropy :name "maxSamplerAnisotropy" :type float)
    (maxviewports :name "maxViewports" :type uint32)
    (maxviewportdimensions :name "maxViewportDimensions" :type uint32
			   :create ((maxviewportdimensions-arg)
				    (create-array :uint32 maxviewportdimensions maxviewportdimensions-arg :dynamic nil :pointers nil))
			   :get ((&optional maxviewportdimensions-index)
				 (get-array :uint32 maxviewportdimensions maxviewportdimensions-index 2 :pointers nil))
			   :set ((maxviewportdimensions-arg &optional maxviewportdimensions-index)
				 (set-array :uint32 maxviewportdimensions maxviewportdimensions-arg maxviewportdimensions-index :dynamic nil :pointers nil)))
    (viewportboundsrange :name "viewportBoundsRange" :type float
			 :create ((viewportboundsrange-arg)
				  (create-array :float viewportboundsrange viewportboundsrange-arg :dynamic nil :pointers nil))
			 :get ((&optional viewportboundsrange-index)
			       (get-array :float viewportboundsrange viewportboundsrange-index 2 :pointers nil))
			 :set ((viewportboundsrange-arg &optional viewportboundsrange-index)
			       (set-array :float viewportboundsrange viewportboundsrange-arg viewportboundsrange-index :dynamic nil :pointers nil)))
    (viewportsubpixelbits :name "viewportSubPixelBits" :type uint32)
    (minmemorymapalignment :name "minMemoryMapAlignment" :type size)
    (mintexelbufferoffsetalignment :name "minTexelBufferOffsetAlignment" :type "VkDeviceSize")
    (minuniformbufferoffsetalignment :name "minUniformBufferOffsetAlignment" :type "VkDeviceSize")
    (minstoragebufferoffsetalignment :name "minStorageBufferOffsetAlignment" :type "VkDeviceSize")
    (mintexeloffset :name "minTexelOffset" :type int32)
    (maxtexeloffset :name "maxTexelOffset" :type uint32)
    (mintexelgatheroffset :name "minTexelGatherOffset" :type int32)
    (maxtexelgatheroffset :name "maxTexelGatherOffset" :type uint32)
    (mininterpolationoffset :name "minInterpolationOffset" :type float)
    (maxinterpolationoffset :name "maxInterpolationOffset" :type float)
    (subpixelinterpolationoffsetbits :name "subPixelInterpolationOffsetBits" :type uint32)
    (maxframebufferwidth :name "maxFramebufferWidth" :type uint32)
    (maxframebufferheight :name "maxFramebufferHeight" :type uint32)
    (maxframebufferlayers :name "maxFramebufferLayers" :type uint32)
    (framebuffercolorsamplecounts :name "framebufferColorSampleCounts" :type "VkSampleCountFlags")
    (framebufferdepthsamplecounts :name "framebufferDepthSampleCounts" :type "VkSampleCountFlags")
    (framebufferstencilsamplecounts :name "framebufferStencilSampleCounts" :type "VkSampleCountFlags")
    (framebuffernoattachmentssamplecounts :name "framebufferNoAttachmentsSampleCounts" :type "VkSampleCountFlags")
    (maxcolorattachments :name "maxColorAttachments" :type uint32)
    (sampledimagecolorsamplecounts :name "sampledImageColorSampleCounts" :type "VkSampleCountFlags")
    (sampledimageintegersamplecounts :name "sampledImageIntegerSampleCounts" :type "VkSampleCountFlags")
    (sampledimagedepthsamplecounts :name "sampledImageDepthSampleCounts" :type "VkSampleCountFlags")
    (sampledimagestencilsamplecounts :name "sampledImageStencilSampleCounts" :type "VkSampleCountFlags")
    (storageimagesamplecounts :name "storageImageSampleCounts" :type "VkSampleCountFlags")
    (maxsamplemaskwords :name "maxSampleMaskWords" :type uint32)
    (timestampcomputeandgraphics :name "timestampComputeAndGraphics" :type "VkBool32")
    (timestampperiod :name "timestampPeriod" :type float)
    (maxclipdistances :name "maxClipDistances" :type uint32)
    (maxculldistances :name "maxCullDistances" :type uint32)
    (maxcombinedclipandculldistances :name "maxCombinedClipAndCullDistances" :type uint32)
    (discretequeuepriorities :name "discreteQueuePriorities" :type uint32)
    (pointsizerange :name "pointSizeRange" :type float
		    :create ((pointsizerange-arg)
			     (create-array :float pointsizerange pointsizerange-arg :dynamic nil :pointers nil))
		    :get ((&optional pointsizerange-index)
			  (get-array :float pointsizerange pointsizerange-index 2 :pointers nil))
		    :set ((pointsizerange-arg &optional pointsizerange-index)
			  (set-array :float pointsizerange pointsizerange-arg pointsizerange-index :dynamic nil :pointers nil)))
    (linewidthrange :name "lineWidthRange" :type float
		    :create ((linewidthrange-arg)
			     (create-array :float linewidthrange linewidthrange-arg :dynamic nil :pointers nil))
		    :get ((&optional linewidthrange-index)
			  (get-array :float linewidthrange linewidthrange-index 2 :pointers nil))
		    :set ((linewidthrange-arg &optional linewidthrange-index)
			  (set-array :float linewidthrange linewidthrange-arg linewidthrange-index :dynamic nil :pointers nil)))
    (pointsizegranularity :name "pointSizeGranularity" :type float)
    (linewidthgranularity :name "lineWidthGranularity" :type float)
    (strictlines :name "strictLines" :type "VkBool32")
    (standardsamplelocations :name "standardSampleLocations" :type "VkBool32")
    (optimalbuffercopyoffsetalignment :name "optimalBufferCopyOffsetAlignment" :type "VkDeviceSize")
    (optimalbuffercopyrowpitchalignment :name "optimalBufferCopyRowPitchAlignment" :type "VkDeviceSize")
    (noncoherentatomsize :name "nonCoherentAtomSize" :type "VkDeviceSize"))


  (more-cffi:def-foreign-struct doc-file "VkPhysicalDeviceSparseProperties" (physical-device-sparse-properties)
      (:default-create :default-get :default-set)
    (residencystandard2dblockshape :name "residencyStandard2DBlockShape" :type "VkBool32")
    (residencystandard2dmultisampleblockshape :name "residencyStandard2DMultisampleBlockShape" :type "VkBool32")
    (residencystandard3dblockshape :name "residencyStandard3DBlockShape" :type "VkBool32")
    (residencyalignedmipsize :name "residencyAlignedMipSize" :type "VkBool32")
    (residencynonresidentstrict :name "residencyNonResidentStrict" :type "VkBool32"))


  (more-cffi:def-foreign-struct doc-file "VkPhysicalDeviceFeatures" (physical-device-features)
      (:default-create :default-get :default-set)
    (robustbufferaccess :name "robustBufferAccess" :type "VkBool32")
    (fulldrawindexuint32 :name "fullDrawIndexUint32" :type "VkBool32")
    (imagecubearray :name "imageCubeArray" :type "VkBool32")
    (independentblend :name "independentBlend" :type "VkBool32")
    (geometryshader :name "geometryShader" :type "VkBool32")
    (tessellationshader :name "tessellationShader" :type "VkBool32")
    (samplerateshading :name "sampleRateShading" :type "VkBool32")
    (dualsrcblend :name "dualSrcBlend" :type "VkBool32")
    (logicop :name "logicOp" :type "VkBool32")
    (multidrawindirect :name "multiDrawIndirect" :type "VkBool32")
    (drawindirectfirstinstance :name "drawIndirectFirstInstance" :type "VkBool32")
    (depthclamp :name "depthClamp" :type "VkBool32")
    (depthbiasclamp :name "depthBiasClamp" :type "VkBool32")
    (fillmodenonsolid :name "fillModeNonSolid" :type "VkBool32")
    (depthbounds :name "depthBounds" :type "VkBool32")
    (widelines :name "wideLines" :type "VkBool32")
    (largepoints :name "largePoints" :type "VkBool32")
    (alphatoone :name "alphaToOne" :type "VkBool32")
    (multiviewport :name "multiViewport" :type "VkBool32")
    (sampleranisotropy :name "samplerAnisotropy" :type "VkBool32")
    (texturecompressionetc2 :name "textureCompressionETC2" :type "VkBool32")
    (texturecompressionastc_ldr :name "textureCompressionASTC_LDR" :type "VkBool32")
    (texturecompressionbc :name "textureCompressionBC" :type "VkBool32")
    (occlusionqueryprecise :name "occlusionQueryPrecise" :type "VkBool32")
    (pipelinestatisticsquery :name "pipelineStatisticsQuery" :type "VkBool32")
    (vertexpipelinestoresandatomics :name "vertexPipelineStoresAndAtomics" :type "VkBool32")
    (fragmentstoresandatomics :name "fragmentStoresAndAtomics" :type "VkBool32")
    (shadertessellationandgeometrypointsize :name "shaderTessellationAndGeometryPointSize" :type "VkBool32")
    (shaderimagegatherextended :name "shaderImageGatherExtended" :type "VkBool32")
    (shaderstorageimageextendedformats :name "shaderStorageImageExtendedFormats" :type "VkBool32")
    (shaderstorageimagemultisample :name "shaderStorageImageMultisample" :type "VkBool32")
    (shaderstorageimagereadwithoutformat :name "shaderStorageImageReadWithoutFormat" :type "VkBool32")
    (shaderstorageimagewritewithoutformat :name "shaderStorageImageWriteWithoutFormat" :type "VkBool32")
    (shaderuniformbufferarraydynamicindexing :name "shaderUniformBufferArrayDynamicIndexing" :type "VkBool32")
    (shadersampledimagearraydynamicindexing :name "shaderSampledImageArrayDynamicIndexing" :type "VkBool32")
    (shaderstoragebufferarraydynamicindexing :name "shaderStorageBufferArrayDynamicIndexing" :type "VkBool32")
    (shaderstorageimagearraydynamicindexing :name "shaderStorageImageArrayDynamicIndexing" :type "VkBool32")
    (shaderclipdistance :name "shaderClipDistance" :type "VkBool32")
    (shaderculldistance :name "shaderCullDistance" :type "VkBool32")
    (shaderfloat64 :name "shaderFloat64" :type "VkBool32")
    (shaderint64 :name "shaderInt64" :type "VkBool32")
    (shaderint16 :name "shaderInt16" :type "VkBool32")
    (shaderresourceresidency :name "shaderResourceResidency" :type "VkBool32")
    (shaderresourceminlod :name "shaderResourceMinLod" :type "VkBool32")
    (sparsebinding :name "sparseBinding" :type "VkBool32")
    (sparseresidencybuffer :name "sparseResidencyBuffer" :type "VkBool32")
    (sparseresidencyimage2d :name "sparseResidencyImage2D" :type "VkBool32")
    (sparseresidencyimage3d :name "sparseResidencyImage3D" :type "VkBool32")
    (sparseresidency2samples :name "sparseResidency2Samples" :type "VkBool32")
    (sparseresidency4samples :name "sparseResidency4Samples" :type "VkBool32")
    (sparseresidency8samples :name "sparseResidency8Samples" :type "VkBool32")
    (sparseresidency16samples :name "sparseResidency16Samples" :type "VkBool32")
    (sparseresidencyaliased :name "sparseResidencyAliased" :type "VkBool32")
    (variablemultisamplerate :name "variableMultisampleRate" :type "VkBool32")
    (inheritedqueries :name "inheritedQueries" :type "VkBool32"))


  (more-cffi:def-foreign-struct doc-file "VkQueueFamilyProperties" (queue-family-properties)
      (:default-create :default-get :default-set)
    (queueflags :name "queueFlags" :type "VkQueueFlags")
    (queuecount :name "queueCount" :type uint32)
    (timestampvalidbits :name "timestampValidBits" :type uint32)
    (minimagetransfergranularity :pointer t :name "minImageTransferGranularity"
				 :type "VkExtent3D"
				 :create ((minimagetransfergranularity-arg)
					  (more-cffi:copy minimagetransfergranularity minimagetransfergranularity-arg '(:struct vkextent3d)))
				 :set ((minimagetransfergranularity-arg)
				       (more-cffi:copy minimagetransfergranularity minimagetransfergranularity-arg '(:struct vkextent3d)))))


  (more-cffi:def-foreign-struct doc-file "VkDeviceQueueCreateInfo" (device-queue-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkDeviceQueueCreateFlags")
    (queuefamilyindex :name "queueFamilyIndex" :type uint32)
    (queuecount :name "queueCount" :type uint32)
    (pqueuepriorities :name "pQueuePriorities" :type (list float) :init-form nil
		      :create ((pqueuepriorities-arg)
			       (create-array :float pqueuepriorities pqueuepriorities-arg :dynamic t :pointers nil))
		      :destroy (destroy-array pqueuepriorities)
		      :get ((&optional pqueuepriorities-index)
			    (get-array :float pqueuepriorities pqueuepriorities-index queuecount :pointers nil))
		      :set ((pqueuepriorities-arg &optional pqueuepriorities-index)
			    (set-array :float pqueuepriorities pqueuepriorities-arg pqueuepriorities-index :dynamic t :pointers nil))))


  (more-cffi:def-foreign-struct doc-file "VkDeviceCreateInfo" (device-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkDeviceCreateFlags")
    (queuecreateinfocount :name "queueCreateInfoCount" :type uint32)
    (pqueuecreateinfos :name "pQueueCreateInfos" :type (list "VkDeviceQueueCreateInfo") :init-form nil
		       :create ((pqueuecreateinfos-arg)
				(create-array (:struct vkdevicequeuecreateinfo) pqueuecreateinfos pqueuecreateinfos-arg :dynamic t :pointers t))
		       :destroy (destroy-array pqueuecreateinfos)
		       :get ((&optional pqueuecreateinfos-index)
			     (get-array (:struct vkdevicequeuecreateinfo) pqueuecreateinfos pqueuecreateinfos-index queuecreateinfocount :pointers t))
		       :set ((pqueuecreateinfos-arg &optional pqueuecreateinfos-index)
			     (set-array (:struct vkdevicequeuecreateinfo) pqueuecreateinfos pqueuecreateinfos-arg pqueuecreateinfos-index :dynamic t :pointers t)))
    (enabledlayercount :name "enabledLayerCount" :type uint32)
    (ppenabledlayernames :name "ppEnabledLayerNames" :type (list string) :init-form nil
			 :create ((ppenabledlayernames-arg)
				  (create-array-strings ppenabledlayernames ppenabledlayernames-arg :dynamic t))
			 :destroy (destroy-array-strings ppenabledlayernames enabledlayercount :dynamic t)
			 :get ((&optional ppenabledlayernames-index)
			       (get-array-strings ppenabledlayernames ppenabledlayernames-index enabledlayercount))
			 :set ((ppenabledlayernames-arg &optional ppenabledlayernames-index)
			       (set-array-strings ppenabledlayernames ppenabledlayernames-arg ppenabledlayernames-index enabledlayercount :dynamic t)))
    (enabledextensioncount :name "enabledExtensionCount" :type uint32)
    (ppenabledextensionnames :name "ppEnabledExtensionNames" :type (list string) :init-form nil
			     :create ((ppenabledextensionnames-arg)
				      (create-array-strings ppenabledextensionnames ppenabledextensionnames-arg :dynamic t))
			     :destroy (destroy-array-strings ppenabledextensionnames enabledextensioncount :dynamic t)
			     :get ((&optional ppenabledextensionnames-index)
				   (get-array-strings ppenabledextensionnames ppenabledextensionnames-index enabledextensioncount))
			     :set ((ppenabledextensionnames-arg &optional ppenabledextensionnames-index)
				   (set-array-strings ppenabledextensionnames ppenabledextensionnames-arg ppenabledextensionnames-index enabledextensioncount :dynamic t)))
    (penabledfeatures :name "pEnabledFeatures" :type "VkPhysicalDeviceFeatures" :init-form nil
		      :create ((penabledfeatures-arg)
			       (create-pointer penabledfeatures penabledfeatures-arg))
		      :get (nil (get-pointer penabledfeatures))
		      :set ((penabledfeatures-arg)
			    (set-pointer penabledfeatures penabledfeatures-arg))))


  (more-cffi:def-foreign-struct doc-file "VkSurfaceCapabilitiesKHR" (surface-capabilities-khr)
      (:default-create :default-get :default-set)
    (minimagecount :name "minImageCount" :type uint32)
    (maximagecount :name "maxImageCount" :type uint32)
    (currentextent :pointer t :name "currentExtent" :type "VkExtent2D"
		   :create ((currentextent-arg)
			    (more-cffi:copy currentextent currentextent-arg '(:struct vkextent2d)))
		   :set ((currentextent-arg)
			 (more-cffi:copy currentextent currentextent-arg '(:struct vkextent2d))))
    (minimageextent :pointer t :name "minImageExtent" :type "VkExtent2D"
		    :create ((minimageextent-arg)
			     (more-cffi:copy minimageextent minimageextent-arg '(:struct vkextent2d)))
		    :set ((minimageextent-arg)
			  (more-cffi:copy minimageextent minimageextent-arg '(:struct vkextent2d))))
    (maximageextent :pointer t :name "maxImageExtent" :type "VkExtent2D"
		    :create ((maximageextent-arg)
			     (more-cffi:copy maximageextent maximageextent-arg '(:struct vkextent2d)))
		    :set ((maximageextent-arg)
			  (more-cffi:copy maximageextent maximageextent-arg '(:struct vkextent2d))))
    (maximagearraylayers :name "maxImageArrayLayers" :type uint32)
    (supportedtransforms :name "supportedTransforms" :type "VkSurfaceTransformFlagsKHR")
    (currenttransform :name "currentTransform" :type "VkSurfaceTransformFlagBitsKHR")
    (supportedcompositealpha :name "supportedCompositeAlpha" :type "VkCompositeAlphaFlagsKHR")
    (supportedusageflags :name "supportedUsageFlags" :type "VkImageUsageFlags"))


  (more-cffi:def-foreign-struct doc-file "VkSurfaceFormatKHR" (surface-format-khr)
      (:default-create :default-get :default-set)
    (format :name format :type "VkFormat")
    (colorspace :name "colorSpace" :type "VkColorSpaceKHR"))


  (more-cffi:def-foreign-struct doc-file "VkShaderModuleCreateInfo" (shader-module-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkShaderModuleCreateFlags")
    (codesize :name "codeSize" :type size)
    (pcode :name "pCode" :type uint32 :init-form nil
	   :create ((pcode-arg)
		    (create-pointer pcode pcode-arg))
	   :get (nil (get-pointer pcode))
	   :set ((pcode-arg)
		 (set-pointer pcode pcode-arg))))


  (more-cffi:def-foreign-struct doc-file "VkImageViewCreateInfo" (image-view-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkImageViewCreateFlags")
    (image :name image :type "VkImage"
	   :create ((image-arg)
		    (create-pointer image image-arg))
	   :get (nil (get-pointer image))
	   :set ((image-arg)
		 (set-pointer image image-arg)))
    (viewtype :name "viewType" :type "VkImageViewType")
    (format :name format :type "VkFormat")
    (components :pointer t :name components :type "VkComponentMapping"
		:create ((components-arg)
			 (more-cffi:copy components components-arg '(:struct vkcomponentmapping)))
		:set ((components-arg)
		      (more-cffi:copy components components-arg '(:struct vkcomponentmapping))))
    (subresourcerange :pointer t :name "subresourceRange" :type "VkImageSubresourceRange"
		      :create ((subresourcerange-arg)
			       (more-cffi:copy subresourcerange subresourcerange-arg '(:struct vkimagesubresourcerange)))
		      :set ((subresourcerange-arg)
			    (more-cffi:copy subresourcerange subresourcerange-arg '(:struct vkimagesubresourcerange)))))


  (more-cffi:def-foreign-struct doc-file "VkSwapchainCreateInfoKHR" (swapchain-create-info-khr)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkSwapchainCreateFlagsKHR")
    (surface :name surface :type "VkSurfaceKHR"
	     :create ((surface-arg)
		      (create-pointer surface surface-arg))
	     :get (nil (get-pointer surface))
	     :set ((surface-arg)
		   (set-pointer surface surface-arg)))
    (minimagecount :name "minImageCount" :type uint32)
    (imageformat :name "imageFormat" :type "VkFormat")
    (imagecolorspace :name "imageColorSpace" :type "VkColorSpaceKHR")
    (imageextent :pointer t :name "imageExtent" :type "VkExtent2D"
		 :create ((imageextent-arg)
			  (more-cffi:copy imageextent imageextent-arg '(:struct vkextent2d)))
		 :set ((imageextent-arg)
		       (more-cffi:copy imageextent imageextent-arg '(:struct vkextent2d))))
    (imagearraylayers :name "imageArrayLayers" :type uint32)
    (imageusage :name "imageUsage" :type "VkImageUsageFlags")
    (imagesharingmode :name "imageSharingMode" :type "VkSharingMode")
    (queuefamilyindexcount :name "queueFamilyIndexCount" :type uint32)
    (pqueuefamilyindices :name "pQueueFamilyIndices" :type (list uint32) :init-form nil
			 :create ((pqueuefamilyindices-arg)
				  (create-array :uint32 pqueuefamilyindices pqueuefamilyindices-arg :dynamic t :pointers nil))
			 :destroy (destroy-array pqueuefamilyindices)
			 :get ((&optional pqueuefamilyindices-index)
			       (get-array :uint32 pqueuefamilyindices pqueuefamilyindices-index queuefamilyindexcount :pointers nil))
			 :set ((pqueuefamilyindices-arg &optional pqueuefamilyindices-index)
			       (set-array :uint32 pqueuefamilyindices pqueuefamilyindices-arg pqueuefamilyindices-index :dynamic t :pointers nil)))
    (pretransform :name "preTransform" :type "VkSurfaceTransformFlagBitsKHR")
    (compositealpha :name "compositeAlpha" :type "VkCompositeAlphaFlagBitsKHR")
    (presentmode :name "presentMode" :type "VkPresentModeKHR")
    (clipped :name clipped :type "VkBool32")
    (oldswapchain :name "oldSwapchain" :type "VkSwapchainKHR"
		  :create ((oldswapchain-arg)
			   (create-pointer oldswapchain oldswapchain-arg))
		  :get (nil (get-pointer oldswapchain))
		  :set ((oldswapchain-arg)
			(set-pointer oldswapchain oldswapchain-arg))))


  (more-cffi:def-foreign-struct doc-file "VkRenderPassCreateInfo" (render-pass-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkRenderPassCreateFlags")
    (attachmentcount :name "attachmentCount" :type uint32)
    (pattachments :name "pAttachments" :type (list "VkAttachmentDescription") :init-form nil
		  :create ((pattachments-arg)
			   (create-array (:struct vkattachmentdescription) pattachments pattachments-arg :dynamic t :pointers t))
		  :destroy (destroy-array pattachments)
		  :get ((&optional pattachments-index)
			(get-array (:struct vkattachmentdescription) pattachments pattachments-index attachmentcount :pointers t))
		  :set ((pattachments-arg &optional pattachments-index)
			(set-array (:struct vkattachmentdescription) pattachments pattachments-arg pattachments-index :dynamic t :pointers t)))
    (subpasscount :name "subpassCount" :type uint32)
    (psubpasses :name "pSubpasses" :type (list "VkSubpassDescription") :init-form nil
		:create ((psubpasses-arg)
			 (create-array (:struct vksubpassdescription) psubpasses psubpasses-arg :dynamic t :pointers t))
		:destroy (destroy-array psubpasses)
		:get ((&optional psubpasses-index)
		      (get-array (:struct vksubpassdescription) psubpasses psubpasses-index subpasscount :pointers t))
		:set ((psubpasses-arg &optional psubpasses-index)
		      (set-array (:struct vksubpassdescription) psubpasses psubpasses-arg psubpasses-index :dynamic t :pointers t)))
    (dependencycount :name "dependencyCount" :type uint32)
    (pdependencies :name "pDependencies" :type (list "VkSubpassDependency") :init-form nil
		   :create ((pdependencies-arg)
			    (create-array (:struct vksubpassdependency) pdependencies pdependencies-arg :dynamic t :pointers t))
		   :destroy (destroy-array pdependencies)
		   :get ((&optional pdependencies-index)
			 (get-array (:struct vksubpassdependency) pdependencies pdependencies-index dependencycount :pointers t))
		   :set ((pdependencies-arg &optional pdependencies-index)
			 (set-array (:struct vksubpassdependency) pdependencies pdependencies-arg pdependencies-index :dynamic t :pointers t))))


  (more-cffi:def-foreign-struct doc-file "VkPipelineShaderStageCreateInfo" (pipeline-shader-stage-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineShaderStageCreateFlags")
    (stage :name stage :type "VkShaderStageFlagBits")
    (module :name module :type "VkShaderModule" :init-form nil
	    :create ((module-arg)
		     (create-pointer module module-arg))
	    :get (nil (get-pointer module))
	    :set ((module-arg)
		  (set-pointer module module-arg)))
    (pname :name "pName" :type string :init-form nil
	   :create ((pname-arg)
		    (create-string pname pname-arg :dynamic t))
	   :destroy (destroy-string pname)
	   :get (nil (get-string pname))
	   :set ((pname-arg)
		 (set-string pname pname-arg :dynamic t)))
    (pspecializationinfo :name "pSpecializationInfo" :type "VkSpecializationInfo" :init-form nil
			 :create ((pspecializationinfo-arg)
				  (create-pointer pspecializationinfo pspecializationinfo-arg))
			 :get (nil (get-pointer pspecializationinfo))
			 :set ((pspecializationinfo-arg)
			       (set-pointer pspecializationinfo pspecializationinfo-arg))))


  (more-cffi:def-foreign-struct doc-file "VkPipelineDynamicStateCreateInfo" (pipeline-dynamic-state-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineDynamicStateCreateFlags")
    (dynamicstatecount :name "dynamicStateCount" :type uint32)
    (pdynamicstates :name "pDynamicStates" :type (list "VkDynamicState") :init-form nil
		    :create ((pdynamicstates-arg)
			     (create-array vkdynamicstate pdynamicstates pdynamicstates-arg :dynamic t :pointers nil))
		    :destroy (destroy-array pdynamicstates)
		    :get ((&optional pdynamicstates-index)
			  (get-array vkdynamicstate pdynamicstates pdynamicstates-index dynamicstatecount :pointers nil))
		    :set ((pdynamicstates-arg &optional pdynamicstates-index)
			  (set-array vkdynamicstate pdynamicstates pdynamicstates-arg pdynamicstates-index :dynamic t :pointers nil))))


  (more-cffi:def-foreign-struct doc-file "VkVertexInputBindingDescription" (vertex-input-binding-description)
      (:default-create :default-get :default-set)
    (binding :name binding :type uint32)
    (stride :name stride :type uint32)
    (inputrate :name "inputRate" :type "VkVertexInputRate"))


  (more-cffi:def-foreign-struct doc-file "VkVertexInputAttributeDescription" (vertex-input-attribute-description)
      (:default-create :default-get :default-set)
    (location :name location :type uint32)
    (binding :name binding :type uint32)
    (format :name format :type "VkFormat")
    (offset :name offset :type uint32))


  (more-cffi:def-foreign-struct doc-file "VkPipelineVertexInputStateCreateInfo" (pipeline-vertex-input-state-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineVertexInputStateCreateFlags")
    (vertexbindingdescriptioncount :name "vertexBindingDescriptionCount" :type uint32)
    (pvertexbindingdescriptions :name "pVertexBindingDescriptions" :type (list "VkVertexInputBindingDescription") :init-form nil
				:create ((pvertexbindingdescriptions-arg)
					 (create-array (:struct vkvertexinputbindingdescription) pvertexbindingdescriptions pvertexbindingdescriptions-arg :dynamic t :pointers t))
				:destroy (destroy-array pvertexbindingdescriptions)
				:get ((&optional pvertexbindingdescriptions-index)
				      (get-array (:struct vkvertexinputbindingdescription) pvertexbindingdescriptions pvertexbindingdescriptions-index vertexbindingdescriptioncount :pointers t))
				:set ((pvertexbindingdescriptions-arg &optional pvertexbindingdescriptions-index)
				      (set-array (:struct vkvertexinputbindingdescription) pvertexbindingdescriptions pvertexbindingdescriptions-arg pvertexbindingdescriptions-index :dynamic t :pointers t)))
    (vertexattributedescriptioncount :name "vertexAttributeDescriptionCount" :type uint32)
    (pvertexattributedescriptions :name "pVertexAttributeDescriptions" :type (list "VkVertexInputAttributeDescription") :init-form nil :create
				  ((pvertexattributedescriptions-arg)
				   (create-array (:struct vkvertexinputattributedescription) pvertexattributedescriptions pvertexattributedescriptions-arg :dynamic t :pointers t))
				  :destroy (destroy-array pvertexattributedescriptions)
				  :get ((&optional pvertexattributedescriptions-index)
					(get-array (:struct vkvertexinputattributedescription) pvertexattributedescriptions pvertexattributedescriptions-index vertexattributedescriptioncount :pointers t))
				  :set ((pvertexattributedescriptions-arg &optional pvertexattributedescriptions-index)
					(set-array (:struct vkvertexinputattributedescription) pvertexattributedescriptions pvertexattributedescriptions-arg pvertexattributedescriptions-index :dynamic t :pointers t))))


  (more-cffi:def-foreign-struct doc-file "VkPipelineInputAssemblyStateCreateInfo" (pipeline-input-assembly-state-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineInputAssemblyStateCreateFlags")
    (topology :name topology :type "VkPrimitiveTopology")
    (primitiverestartenable :name "primitiveRestartEnable" :type "VkBool32"))


  (more-cffi:def-foreign-struct doc-file "VkPipelineViewportStateCreateInfo" (pipeline-viewport-state-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineViewportStateCreateFlags")
    (viewportcount :name "viewportCount" :type uint32)
    (pviewports :name "pViewports" :type (list "VkViewport") :init-form nil
		:create ((pviewports-arg)
			 (create-array (:struct vkviewport) pviewports pviewports-arg :dynamic t :pointers t))
		:destroy (destroy-array pviewports)
		:get ((&optional pviewports-index)
		      (get-array (:struct vkviewport) pviewports pviewports-index viewportcount :pointers t))
		:set ((pviewports-arg &optional pviewports-index)
		      (set-array (:struct vkviewport) pviewports pviewports-arg pviewports-index :dynamic t :pointers t)))
    (scissorcount :name "scissorCount" :type uint32)
    (pscissors :name "pScissors" :type (list "VkRect2D") :init-form nil
	       :create ((pscissors-arg)
			(create-array (:struct vkrect2d) pscissors pscissors-arg :dynamic t :pointers t))
	       :destroy (destroy-array pscissors)
	       :get ((&optional pscissors-index)
		     (get-array (:struct vkrect2d) pscissors pscissors-index scissorcount :pointers t))
	       :set ((pscissors-arg &optional pscissors-index)
		     (set-array (:struct vkrect2d) pscissors pscissors-arg pscissors-index :dynamic t :pointers t))))


  (more-cffi:def-foreign-struct doc-file "VkPipelineRasterizationStateCreateInfo" (pipeline-rasterization-state-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineRasterizationStateCreateFlags")
    (depthclampenable :name "depthClampEnable" :type "VkBool32")
    (rasterizerdiscardenable :name "rasterizerDiscardEnable" :type "VkBool32")
    (polygonmode :name "polygonMode" :type "VkPolygonMode")
    (cullmode :name "cullMode" :type "VkCullModeFlags")
    (frontface :name "frontFace" :type "VkFrontFace")
    (depthbiasenable :name "depthBiasEnable" :type "VkBool32")
    (depthbiasconstantfactor :name "depthBiasConstantFactor" :type float)
    (depthbiasclamp :name "depthBiasClamp" :type float)
    (depthbiasslopefactor :name "depthBiasSlopeFactor" :type float)
    (linewidth :name "lineWidth" :type float))


  (more-cffi:def-foreign-struct doc-file "VkPipelineMultisampleStateCreateInfo" (pipeline-multisample-state-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineMultisampleStateCreateFlags")
    (rasterizationsamples :name "rasterizationSamples" :type "VkSampleCountFlagBits")
    (sampleshadingenable :name "sampleShadingEnable" :type "VkBool32")
    (minsampleshading :name "minSampleShading" :type float)
    (psamplemask :name "pSampleMask" :type "VkSampleMask" :init-form nil
		 :create ((psamplemask-arg)
			  (create-pointer psamplemask psamplemask-arg))
		 :get (nil (get-pointer psamplemask))
		 :set ((psamplemask-arg)
		       (set-pointer psamplemask psamplemask-arg)))
    (alphatocoverageenable :name "alphaToCoverageEnable" :type "VkBool32")
    (alphatooneenable :name "alphaToOneEnable" :type "VkBool32"))


  (more-cffi:def-foreign-struct doc-file "VkPipelineColorBlendAttachmentState" (pipeline-color-blend-attachment-state)
      (:default-create :default-get :default-set)
    (blendenable :name "blendEnable" :type "VkBool32")
    (srccolorblendfactor :name "srcColorBlendFactor" :type "VkBlendFactor")
    (dstcolorblendfactor :name "dstColorBlendFactor" :type "VkBlendFactor")
    (colorblendop :name "colorBlendOp" :type "VkBlendOp")
    (srcalphablendfactor :name "srcAlphaBlendFactor" :type "VkBlendFactor")
    (dstalphablendfactor :name "dstAlphaBlendFactor" :type "VkBlendFactor")
    (alphablendop :name "alphaBlendOp" :type "VkBlendOp")
    (colorwritemask :name "colorWriteMask" :type "VkColorComponentFlags"))


  (more-cffi:def-foreign-struct doc-file "VkPipelineColorBlendStateCreateInfo" (pipeline-color-blend-state-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineColorBlendStateCreateFlags")
    (logicopenable :name "logicOpEnable" :type "VkBool32")
    (logicop :name "logicOp" :type "VkLogicOp")
    (attachmentcount :name "attachmentCount" :type uint32)
    (pattachments :name "pAttachments" :type (list "VkPipelineColorBlendAttachmentState") :init-form nil
		  :create ((pattachments-arg)
			   (create-array (:struct vkpipelinecolorblendattachmentstate) pattachments pattachments-arg :dynamic t :pointers t))
		  :destroy (destroy-array pattachments)
		  :get ((&optional pattachments-index)
			(get-array (:struct vkpipelinecolorblendattachmentstate) pattachments pattachments-index attachmentcount :pointers t))
		  :set ((pattachments-arg &optional pattachments-index) (set-array (:struct vkpipelinecolorblendattachmentstate) pattachments pattachments-arg pattachments-index :dynamic t :pointers t)))
    (blendconstants :name "blendConstants" :type (list float)
		    :create ((blendconstants-arg)
			     (create-array :float blendconstants blendconstants-arg :dynamic nil :pointers nil))
		    :get ((&optional blendconstants-index)
			  (get-array :float blendconstants blendconstants-index 4 :pointers nil))
		    :set ((blendconstants-arg &optional blendconstants-index)
			  (set-array :float blendconstants blendconstants-arg blendconstants-index :dynamic nil :pointers nil))))


  (more-cffi:def-foreign-struct doc-file "VkPipelineLayoutCreateInfo" (pipeline-layout-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineLayoutCreateFlags")
    (setlayoutcount :name "setLayoutCount" :type uint32)
    (psetlayouts :name "pSetLayouts" :type (list "VkDescriptorSetLayout") :init-form nil
		 :create ((psetlayouts-arg)
			  (create-array vkdescriptorsetlayout psetlayouts psetlayouts-arg :dynamic t :pointers nil))
		 :destroy (destroy-array psetlayouts)
		 :get ((&optional psetlayouts-index)
		       (get-array vkdescriptorsetlayout psetlayouts psetlayouts-index setlayoutcount :pointers nil))
		 :set ((psetlayouts-arg &optional psetlayouts-index)
		       (set-array vkdescriptorsetlayout psetlayouts psetlayouts-arg psetlayouts-index :dynamic t :pointers nil)))
    (pushconstantrangecount :name "pushConstantRangeCount" :type uint32)
    (ppushconstantranges :name "pPushConstantRanges" :type (list "VkPushConstantRange") :init-form nil
			 :create ((ppushconstantranges-arg)
				  (create-array (:struct vkpushconstantrange) ppushconstantranges ppushconstantranges-arg :dynamic t :pointers t))
			 :destroy (destroy-array ppushconstantranges)
			 :get ((&optional ppushconstantranges-index)
			       (get-array (:struct vkpushconstantrange) ppushconstantranges ppushconstantranges-index pushconstantrangecount :pointers t))
			 :set ((ppushconstantranges-arg &optional ppushconstantranges-index)
			       (set-array (:struct vkpushconstantrange) ppushconstantranges ppushconstantranges-arg ppushconstantranges-index :dynamic t :pointers t))))


  (more-cffi:def-foreign-struct doc-file "VkGraphicsPipelineCreateInfo" (graphics-pipeline-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkPipelineCreateFlags")
    (stagecount :name "stageCount" :type uint32)
    (pstages :name "pStages" :type (list "VkPipelineShaderStageCreateInfo") :init-form nil
	     :create ((pstages-arg)
		      (create-array (:struct vkpipelineshaderstagecreateinfo) pstages pstages-arg :dynamic t :pointers t))
	     :destroy (destroy-array pstages)
	     :get ((&optional pstages-index)
		   (get-array (:struct vkpipelineshaderstagecreateinfo) pstages pstages-index stagecount :pointers t))
	     :set ((pstages-arg &optional pstages-index)
		   (set-array (:struct vkpipelineshaderstagecreateinfo) pstages pstages-arg pstages-index :dynamic t :pointers t)))
    (pvertexinputstate :name "pVertexInputState" :type "VkPipelineVertexInputStateCreateInfo" :init-form nil
		       :create ((pvertexinputstate-arg)
				(create-pointer pvertexinputstate pvertexinputstate-arg))
		       :get (nil (get-pointer pvertexinputstate))
		       :set ((pvertexinputstate-arg)
			     (set-pointer pvertexinputstate pvertexinputstate-arg)))
    (pinputassemblystate :name "pInputAssemblyState" :type "VkPipelineInputAssemblyStateCreateInfo" :init-form nil
			 :create ((pinputassemblystate-arg)
				  (create-pointer pinputassemblystate pinputassemblystate-arg))
			 :get (nil (get-pointer pinputassemblystate))
			 :set ((pinputassemblystate-arg)
			       (set-pointer pinputassemblystate pinputassemblystate-arg)))
    (ptessellationstate :name "pTessellationState" :type "VkPipelineTessellationStateCreateInfo" :init-form nil
			:create ((ptessellationstate-arg)
				 (create-pointer ptessellationstate ptessellationstate-arg))
			:get (nil (get-pointer ptessellationstate))
			:set ((ptessellationstate-arg)
			      (set-pointer ptessellationstate ptessellationstate-arg)))
    (pviewportstate :name "pViewportState" :type "VkPipelineViewportStateCreateInfo" :init-form nil
		    :create ((pviewportstate-arg)
			     (create-pointer pviewportstate pviewportstate-arg))
		    :get (nil (get-pointer pviewportstate))
		    :set ((pviewportstate-arg) (set-pointer pviewportstate pviewportstate-arg)))
    (prasterizationstate :name "pRasterizationState" :type "VkPipelineRasterizationStateCreateInfo" :init-form nil
			 :create ((prasterizationstate-arg)
				  (create-pointer prasterizationstate prasterizationstate-arg))
			 :get (nil (get-pointer prasterizationstate))
			 :set ((prasterizationstate-arg)
			       (set-pointer prasterizationstate prasterizationstate-arg)))
    (pmultisamplestate :name "pMultisampleState" :type "VkPipelineMultisampleStateCreateInfo" :init-form nil
		       :create ((pmultisamplestate-arg)
				(create-pointer pmultisamplestate pmultisamplestate-arg))
		       :get (nil (get-pointer pmultisamplestate))
		       :set ((pmultisamplestate-arg)
			     (set-pointer pmultisamplestate pmultisamplestate-arg)))
    (pdepthstencilstate :name "pDepthStencilState" :type "VkPipelineDepthStencilStateCreateInfo" :init-form nil
			:create ((pdepthstencilstate-arg)
				 (create-pointer pdepthstencilstate pdepthstencilstate-arg))
			:get (nil (get-pointer pdepthstencilstate))
			:set ((pdepthstencilstate-arg)
			      (set-pointer pdepthstencilstate pdepthstencilstate-arg)))
    (pcolorblendstate :name "pColorBlendState" :type "VkPipelineColorBlendStateCreateInfo" :init-form nil
		      :create ((pcolorblendstate-arg)
			       (create-pointer pcolorblendstate pcolorblendstate-arg))
		      :get (nil (get-pointer pcolorblendstate))
		      :set ((pcolorblendstate-arg)
			    (set-pointer pcolorblendstate pcolorblendstate-arg)))
    (pdynamicstate :name "pDynamicState" :type "VkPipelineDynamicStateCreateInfo" :init-form nil
		   :create ((pdynamicstate-arg)
			    (create-pointer pdynamicstate pdynamicstate-arg))
		   :get (nil (get-pointer pdynamicstate))
		   :set ((pdynamicstate-arg)
			 (set-pointer pdynamicstate pdynamicstate-arg)))
    (layout :name layout :type "VkPipelineLayout" :init-form nil
	    :create ((layout-arg) (create-pointer layout layout-arg))
	    :get (nil (get-pointer layout))
	    :set ((layout-arg)
		  (set-pointer layout layout-arg)))
    (renderpass :name "renderPass" :type "VkRenderPass" :init-form nil
		:create ((renderpass-arg)
			 (create-pointer renderpass renderpass-arg))
		:get (nil (get-pointer renderpass))
		:set ((renderpass-arg)
		      (set-pointer renderpass renderpass-arg)))
    (subpass :name subpass :type uint32)
    (basepipelinehandle :name "basePipelineHandle" :type "VkPipeline" :init-form nil
			:create ((basepipelinehandle-arg)
				 (create-pointer basepipelinehandle basepipelinehandle-arg))
			:get (nil (get-pointer basepipelinehandle))
			:set ((basepipelinehandle-arg)
			      (set-pointer basepipelinehandle basepipelinehandle-arg)))
    (basepipelineindex :name "basePipelineIndex" :type int32))


  (more-cffi:def-foreign-struct doc-file "VkFramebufferCreateInfo" (framebuffer-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkFramebufferCreateFlags")
    (renderpass :name "renderPass" :type "VkRenderPass"
		:create ((renderpass-arg)
			 (create-pointer renderpass renderpass-arg))
		:get (nil (get-pointer renderpass))
		:set ((renderpass-arg)
		      (set-pointer renderpass renderpass-arg)))
    (attachmentcount :name "attachmentCount" :type uint32)
    (pattachments :name "pAttachments" :type (list "VkImageView") :init-form nil
		  :create ((pattachments-arg)
			   (create-array vkimageview pattachments pattachments-arg :dynamic t :pointers nil))
		  :destroy (destroy-array pattachments)
		  :get ((&optional pattachments-index)
			(get-array vkimageview pattachments pattachments-index attachmentcount :pointers nil))
		  :set ((pattachments-arg &optional pattachments-index)
			(set-array vkimageview pattachments pattachments-arg pattachments-index :dynamic t :pointers nil)))
    (width :name width :type uint32)
    (height :name height :type uint32)
    (layers :name layers :type uint32))


  (more-cffi:def-foreign-struct doc-file "VkCommandPoolCreateInfo" (command-pool-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkCommandPoolCreateFlags")
    (queuefamilyindex :name "queueFamilyIndex" :type uint32))


  (more-cffi:def-foreign-struct doc-file "VkCommandBufferAllocateInfo" (command-buffer-allocate-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (commandpool :name "commandPool" :type "VkCommandPool"
		 :create ((commandpool-arg)
			  (create-pointer commandpool commandpool-arg))
		 :get (nil (get-pointer commandpool))
		 :set ((commandpool-arg)
		       (set-pointer commandpool commandpool-arg)))
    (level :name level :type "VkCommandBufferLevel")
    (commandbuffercount :name "commandBufferCount" :type uint32))


  (more-cffi:def-foreign-struct doc-file "VkCommandBufferInheritanceInfo" (command-buffer-inheritance-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (renderpass :name "renderPass" :type "VkRenderPass"
		:create ((renderpass-arg)
			 (create-pointer renderpass renderpass-arg))
		:get (nil (get-pointer renderpass))
		:set ((renderpass-arg)
		      (set-pointer renderpass renderpass-arg)))
    (subpass :name subpass :type uint32)
    (framebuffer :name framebuffer :type "VkFramebuffer"
		 :create ((framebuffer-arg)
			  (create-pointer framebuffer framebuffer-arg))
		 :get (nil (get-pointer framebuffer))
		 :set ((framebuffer-arg)
		       (set-pointer framebuffer framebuffer-arg)))
    (occlusionqueryenable :name "occlusionQueryEnable" :type "VkBool32")
    (queryflags :name "queryFlags" :type "VkQueryControlFlags")
    (pipelinestatistics :name "pipelineStatistics" :type "VkQueryPipelineStatisticFlags"))


  (more-cffi:def-foreign-struct doc-file "VkCommandBufferBeginInfo" (command-buffer-begin-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkCommandBufferUsageFlags")
    (pinheritanceinfo :name "pInheritanceInfo" :type "VkCommandBufferInheritanceInfo" :init-form nil
		      :create ((pinheritanceinfo-arg)
			       (create-pointer pinheritanceinfo pinheritanceinfo-arg))
		      :get (nil (get-pointer pinheritanceinfo))
		      :set ((pinheritanceinfo-arg)
			    (set-pointer pinheritanceinfo pinheritanceinfo-arg))))


  (more-cffi:def-foreign-union doc-file "VkClearColorValue" (clear-color-value)
      (:default-create :default-get :default-set)
    (float32 :name float32 :type (list float)
	     :create ((float32-arg)
		      (create-array :float float32 float32-arg :dynamic nil :pointers nil))
	     :get ((&optional float32-index)
		   (get-array :float float32 float32-index 4 :pointers nil))
	     :set ((float32-arg &optional float32-index)
		   (set-array :float float32 float32-arg float32-index :dynamic nil :pointers nil)))
    (int32 :name int32 :type (list int32)
	   :create ((int32-arg)
		    (create-array :int32 int32 int32-arg :dynamic nil :pointers nil))
	   :get ((&optional int32-index)
		 (get-array :int32 int32 int32-index 4 :pointers nil))
	   :set ((int32-arg &optional int32-index)
		 (set-array :int32 int32 int32-arg int32-index :dynamic nil :pointers nil)))
    (uint32 :name uint32 :type (list uint32)
	    :create ((uint32-arg)
		     (create-array :uint32 uint32 uint32-arg :dynamic nil :pointers nil))
	    :get ((&optional uint32-index)
		  (get-array :uint32 uint32 uint32-index 4 :pointers nil))
	    :set ((uint32-arg &optional uint32-index)
		  (set-array :uint32 uint32 uint32-arg uint32-index :dynamic nil :pointers nil))))


  (more-cffi:def-foreign-struct doc-file "VkClearDepthStencilValue" (clear-depth-stencil-value)
      (:default-create :default-get :default-set)
    (depth :name depth :type float)
    (stencil :name stencil :type uint32))

  
  (more-cffi:def-foreign-union doc-file "VkClearValue" (clear-value)
      (:default-create :default-get :default-set)
    (color :pointer t :name color :type "VkClearColorValue"
	   :create ((color-arg)
		    (more-cffi:copy color color-arg '(:union vkclearcolorvalue)))
	   :set ((color-arg)
		 (more-cffi:copy color color-arg '(:union vkclearcolorvalue))))
    (depthstencil :pointer t :name "depthStencil" :type "VkClearDepthStencilValue"
		  :create ((depthstencil-arg)
			   (more-cffi:copy depthstencil depthstencil-arg '(:struct vkcleardepthstencilvalue)))
		  :set ((depthstencil-arg)
			(more-cffi:copy depthstencil depthstencil-arg '(:struct vkcleardepthstencilvalue)))))
  

  (more-cffi:def-foreign-struct doc-file "VkRenderPassBeginInfo" (render-pass-begin-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (renderpass :name "renderPass" :type "VkRenderPass"
		:create ((renderpass-arg)
			 (create-pointer renderpass renderpass-arg))
		:get (nil (get-pointer renderpass))
		:set ((renderpass-arg)
		      (set-pointer renderpass renderpass-arg)))
    (framebuffer :name framebuffer :type "VkFramebuffer"
		 :create ((framebuffer-arg)
			  (create-pointer framebuffer framebuffer-arg))
		 :get (nil (get-pointer framebuffer))
		 :set ((framebuffer-arg)
		       (set-pointer framebuffer framebuffer-arg)))
    (renderarea :pointer t :name "renderArea" :type "VkRect2D"
		:create ((renderarea-arg)
			 (more-cffi:copy renderarea renderarea-arg '(:struct vkrect2d)))
		:set ((renderarea-arg)
		      (more-cffi:copy renderarea renderarea-arg '(:struct vkrect2d))))
    (clearvaluecount :name "clearValueCount" :type uint32)
    (pclearvalues :name "pClearValues" :type (list "VkClearValue") :init-form nil
		  :create ((pclearvalues-arg)
			   (create-array (:union vkclearvalue) pclearvalues pclearvalues-arg :dynamic t :pointers ("VkClearValue")))
		  :destroy (destroy-array pclearvalues)
		  :get ((&optional pclearvalues-index)
			(get-array (:union vkclearvalue) pclearvalues pclearvalues-index clearvaluecount :pointers ("VkClearValue")))
		  :set ((pclearvalues-arg &optional pclearvalues-index)
			(set-array (:union vkclearvalue) pclearvalues pclearvalues-arg pclearvalues-index :dynamic t :pointers ("VkClearValue")))))


  (more-cffi:def-foreign-struct doc-file "VkSemaphoreCreateInfo" (semaphore-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (flags :name flags :type "VkSemaphoreCreateFlags"))


  (more-cffi:def-foreign-struct doc-file "VkExportFenceCreateInfo" (export-fence-create-info-khr export-fence-create-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (handletypes :name "handleTypes" :type "VkExternalFenceHandleTypeFlags"))


  (more-cffi:def-foreign-struct doc-file "VkSubmitInfo" (submit-info)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (waitsemaphorecount :name "waitSemaphoreCount" :type uint32)
    (pwaitsemaphores :name "pWaitSemaphores" :type (list "VkSemaphore") :init-form nil
		     :create ((pwaitsemaphores-arg)
			      (create-array vksemaphore pwaitsemaphores pwaitsemaphores-arg :dynamic t :pointers nil))
		     :destroy (destroy-array pwaitsemaphores)
		     :get ((&optional pwaitsemaphores-index)
			   (get-array vksemaphore pwaitsemaphores pwaitsemaphores-index waitsemaphorecount :pointers nil))
		     :set ((pwaitsemaphores-arg &optional pwaitsemaphores-index)
			   (set-array vksemaphore pwaitsemaphores pwaitsemaphores-arg pwaitsemaphores-index :dynamic t :pointers nil)))
    (pwaitdststagemask :name "pWaitDstStageMask" :type (list "VkPipelineStageFlags") :init-form nil
		       :create ((pwaitdststagemask-arg)
				(create-array VkPipelineStageFlags pwaitdststagemask pwaitdststagemask-arg :dynamic t :pointers nil))
		       :destroy (destroy-array pwaitdststagemask)
		       :get ((&optional pwaitdststagemask-index)
			     (get-array VkPipelineStageFlags pwaitdststagemask pwaitdststagemask-index waitsemaphorecount :pointers nil))
		       :set ((pwaitdststagemask-arg &optional pwaitdststagemask-index)
			     (set-array VkPipelineStageFlags pwaitdststagemask pwaitdststagemask-arg pwaitdststagemask-index :dynamic t :pointers nil)))
    (commandbuffercount :name "commandBufferCount" :type uint32)
    (pcommandbuffers :name "pCommandBuffers" :type (list "VkCommandBuffer") :init-form nil
		     :create ((pcommandbuffers-arg)
			      (create-array vkcommandbuffer pcommandbuffers pcommandbuffers-arg :dynamic t :pointers nil))
		     :destroy (destroy-array pcommandbuffers)
		     :get ((&optional pcommandbuffers-index)
			   (get-array vkcommandbuffer pcommandbuffers pcommandbuffers-index commandbuffercount :pointers nil))
		     :set ((pcommandbuffers-arg &optional pcommandbuffers-index)
			   (set-array vkcommandbuffer pcommandbuffers pcommandbuffers-arg pcommandbuffers-index :dynamic t :pointers nil)))
    (signalsemaphorecount :name "signalSemaphoreCount" :type uint32)
    (psignalsemaphores :name "pSignalSemaphores" :type (list "VkSemaphore") :init-form nil
		       :create ((psignalsemaphores-arg)
				(create-array vksemaphore psignalsemaphores psignalsemaphores-arg :dynamic t :pointers nil))
		       :destroy (destroy-array psignalsemaphores)
		       :get ((&optional psignalsemaphores-index)
			     (get-array vksemaphore psignalsemaphores psignalsemaphores-index signalsemaphorecount :pointers nil))
		       :set ((psignalsemaphores-arg &optional psignalsemaphores-index)
			     (set-array vksemaphore psignalsemaphores psignalsemaphores-arg psignalsemaphores-index :dynamic t :pointers nil))))


  (more-cffi:def-foreign-struct doc-file "VkSubpassDependency" (subpass-dependency)
      (:default-create :default-get :default-set)
    (srcsubpass :name "srcSubpass" :type uint32)
    (dstsubpass :name "dstSubpass" :type uint32)
    (srcstagemask :name "srcStageMask" :type "VkPipelineStageFlags")
    (dststagemask :name "dstStageMask" :type "VkPipelineStageFlags")
    (srcaccessmask :name "srcAccessMask" :type "VkAccessFlags")
    (dstaccessmask :name "dstAccessMask" :type "VkAccessFlags")
    (dependencyflags :name "dependencyFlags" :type "VkDependencyFlags"))


  (more-cffi:def-foreign-struct doc-file "VkPresentInfoKHR" (present-info-khr)
      (:default-create :default-get :default-set)
    (stype :name "sType" :type "VkStructureType")
    (pnext :name "pNext" :type "Vulkan object" :init-form nil
	   :create ((pnext-arg)
		    (create-pointer pnext pnext-arg))
	   :get (nil (get-pointer pnext))
	   :set ((pnext-arg)
		 (set-pointer pnext pnext-arg)))
    (waitsemaphorecount :name "waitSemaphoreCount" :type uint32)
    (pwaitsemaphores :name "pWaitSemaphores" :type (list "VkSemaphore") :init-form nil
		     :create ((pwaitsemaphores-arg)
			      (create-array vksemaphore pwaitsemaphores pwaitsemaphores-arg :dynamic t :pointers nil))
		     :destroy (destroy-array pwaitsemaphores)
		     :get ((&optional pwaitsemaphores-index)
			   (get-array vksemaphore pwaitsemaphores pwaitsemaphores-index waitsemaphorecount :pointers nil))
		     :set ((pwaitsemaphores-arg &optional pwaitsemaphores-index)
			   (set-array vksemaphore pwaitsemaphores pwaitsemaphores-arg pwaitsemaphores-index :dynamic t :pointers nil)))
    (swapchaincount :name "swapchainCount" :type uint32)
    (pswapchains :name "pSwapchains" :type (list "VkSwapchainKHR") :init-form nil
		 :create ((pswapchains-arg)
			  (create-array vkswapchainkhr pswapchains pswapchains-arg :dynamic t :pointers nil))
		 :destroy (destroy-array pswapchains)
		 :get ((&optional pswapchains-index)
		       (get-array vkswapchainkhr pswapchains pswapchains-index swapchaincount :pointers nil))
		 :set ((pswapchains-arg &optional pswapchains-index)
		       (set-array vkswapchainkhr pswapchains pswapchains-arg pswapchains-index :dynamic t :pointers nil)))
    (pimageindices :name "pImageIndices" :type (list uint32) :init-form nil
		   :create ((pimageindices-arg)
			    (create-array :uint32 pimageindices pimageindices-arg :dynamic t :pointers nil))
		   :destroy (destroy-array pimageindices)
		   :get ((&optional pimageindices-index)
			 (get-array :uint32 pimageindices pimageindices-index swapchaincount :pointers nil))
		   :set ((pimageindices-arg &optional pimageindices-index)
			 (set-array :uint32 pimageindices pimageindices-arg pimageindices-index :dynamic t :pointers nil)))
    (presults :name "pResults" :type "VkResult" :init-form nil
	      :create ((presults-arg)
		       (create-array VkResult presults presults-arg :dynamic t :pointers nil))
	      :destroy (destroy-array presults)
	      :get ((&optional presults-index)
		    (get-array VkResult presults presults-index swapchaincount :pointers nil))
	      :set ((presults-arg &optional presults-index)
		    (set-array VkResult presults presults-arg presults-index :dynamic t :pointers nil)))))
